// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_BitmapInterpolationMode = require('./BitmapInterpolationMode');
const _m_BitmapFlip = require('./BitmapFlip');
const _m_BitmapRotation = require('./BitmapRotation');

const IID_IBitmapTransform = WinGuid.parse('ae755344-e268-4d35-adcf-e995d31a8d34');

const _IBitmapTransform = DynWinRtType.registerInterface(
    "IBitmapTransform", IID_IBitmapTransform)
    .addMethod("get_ScaledWidth", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_ScaledWidth", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_ScaledHeight", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_ScaledHeight", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_InterpolationMode", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapInterpolationMode', ['NearestNeighbor', 'Linear', 'Cubic', 'Fant'], [0, 1, 2, 3])))
    .addMethod("put_InterpolationMode", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapInterpolationMode', ['NearestNeighbor', 'Linear', 'Cubic', 'Fant'], [0, 1, 2, 3])))
    .addMethod("get_Flip", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapFlip', ['None', 'Horizontal', 'Vertical'], [0, 1, 2])))
    .addMethod("put_Flip", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapFlip', ['None', 'Horizontal', 'Vertical'], [0, 1, 2])))
    .addMethod("get_Rotation", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapRotation', ['None', 'Clockwise90Degrees', 'Clockwise180Degrees', 'Clockwise270Degrees'], [0, 1, 2, 3])))
    .addMethod("put_Rotation", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapRotation', ['None', 'Clockwise90Degrees', 'Clockwise180Degrees', 'Clockwise270Degrees'], [0, 1, 2, 3])))
    .addMethod("get_Bounds", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Graphics.Imaging.BitmapBounds', [DynWinRtType.u32(), DynWinRtType.u32(), DynWinRtType.u32(), DynWinRtType.u32()])))
    .addMethod("put_Bounds", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Graphics.Imaging.BitmapBounds', [DynWinRtType.u32(), DynWinRtType.u32(), DynWinRtType.u32(), DynWinRtType.u32()])));

function _unpackBitmapBounds(v) {
    const s = v.asStruct();
    return { x: s.getU32(0), y: s.getU32(1), width: s.getU32(2), height: s.getU32(3) };
}
const _BitmapBounds_Type = DynWinRtType.structType('Windows.Graphics.Imaging.BitmapBounds', [DynWinRtType.u32(), DynWinRtType.u32(), DynWinRtType.u32(), DynWinRtType.u32()]);
function _packBitmapBounds(v) {
    const s = DynWinRtStruct.create(_BitmapBounds_Type);
    s.setU32(0, v.x);
    s.setU32(1, v.y);
    s.setU32(2, v.width);
    s.setU32(3, v.height);
    return s;
}

class BitmapTransform {

    constructor(obj) {
        this._obj = obj.cast(IID_IBitmapTransform);
    }

    static create() {
        return new BitmapTransform(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Windows.Graphics.Imaging.BitmapTransform'), []));
    }

    get scaledWidth() {
        return _IBitmapTransform.method(6).invoke(this._obj, []).toNumber();
    }

    set scaledWidth(value) {
        _IBitmapTransform.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get scaledHeight() {
        return _IBitmapTransform.method(8).invoke(this._obj, []).toNumber();
    }

    set scaledHeight(value) {
        _IBitmapTransform.method(9).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get interpolationMode() {
        return _IBitmapTransform.method(10).invoke(this._obj, []).toNumber();
    }

    set interpolationMode(value) {
        _IBitmapTransform.method(11).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get flip() {
        return _IBitmapTransform.method(12).invoke(this._obj, []).toNumber();
    }

    set flip(value) {
        _IBitmapTransform.method(13).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get rotation() {
        return _IBitmapTransform.method(14).invoke(this._obj, []).toNumber();
    }

    set rotation(value) {
        _IBitmapTransform.method(15).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get bounds() {
        return _unpackBitmapBounds(_IBitmapTransform.method(16).invoke(this._obj, []));
    }

    set bounds(value) {
        _IBitmapTransform.method(17).invoke(this._obj, [_packBitmapBounds(value).toValue()]);
    }
}
module.exports = { BitmapTransform };
