// Generated by winrt-meta — do not edit

const BitmapPixelFormat = Object.freeze({ Unknown: 0, Rgba16: 12, Rgba8: 30, Gray16: 57, Gray8: 62, Bgra8: 87, Nv12: 103, P010: 104, Yuy2: 107 });
module.exports = { BitmapPixelFormat };
