// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');


class BitmapPropertySet {

    constructor(obj) {
        this._obj = obj;
    }

    static create() {
        return new BitmapPropertySet(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Windows.Graphics.Imaging.BitmapPropertySet'), []));
    }
}
module.exports = { BitmapPropertySet };
