// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { IID_IMemoryBufferReference } = require('./IMemoryBufferReference');
const _m_IMemoryBufferReference = require('./IMemoryBufferReference');

const IID_IBitmapBuffer = WinGuid.parse('a53e04c4-399c-438c-b28f-a63a6b83d1a1');
const IID_IMemoryBuffer = WinGuid.parse('fbc4dd2a-245b-11e4-af98-689423260cf8');
const IID_IClosable = WinGuid.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e');

const _IBitmapBuffer = DynWinRtType.registerInterface(
    "IBitmapBuffer", IID_IBitmapBuffer)
    .addMethod("GetPlaneCount", new DynWinRtMethodSig().addOut(DynWinRtType.i32()))
    .addMethod("GetPlaneDescription", new DynWinRtMethodSig().addIn(DynWinRtType.i32()).addOut(DynWinRtType.structType('Windows.Graphics.Imaging.BitmapPlaneDescription', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()])));

const _IMemoryBuffer = DynWinRtType.registerInterface(
    "IMemoryBuffer", IID_IMemoryBuffer)
    .addMethod("CreateReference", new DynWinRtMethodSig().addOut(DynWinRtType.interface(WinGuid.parse('fbc4dd29-245b-11e4-af98-689423260cf8'))));

const _IClosable = DynWinRtType.registerInterface(
    "IClosable", IID_IClosable)
    .addMethod("Close", new DynWinRtMethodSig());

function _unpackBitmapPlaneDescription(v) {
    const s = v.asStruct();
    return { startIndex: s.getI32(0), width: s.getI32(1), height: s.getI32(2), stride: s.getI32(3) };
}
const _BitmapPlaneDescription_Type = DynWinRtType.structType('Windows.Graphics.Imaging.BitmapPlaneDescription', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()]);
function _packBitmapPlaneDescription(v) {
    const s = DynWinRtStruct.create(_BitmapPlaneDescription_Type);
    s.setI32(0, v.startIndex);
    s.setI32(1, v.width);
    s.setI32(2, v.height);
    s.setI32(3, v.stride);
    return s;
}

class BitmapBuffer {

    constructor(obj) {
        this._obj = obj.cast(IID_IBitmapBuffer);
    }

    getPlaneCount() {
        return _IBitmapBuffer.method(6).invoke(this._obj, []).toNumber();
    }

    getPlaneDescription(value) {
        return _unpackBitmapPlaneDescription(_IBitmapBuffer.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IMemoryBuffer {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IMemoryBuffer(obj.cast(IID_IMemoryBuffer));
    }

    createReference() {
        return new _m_IMemoryBufferReference.IMemoryBufferReference(_IMemoryBuffer.method(6).invoke(this._obj, []));
    }
}

class IClosable {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IClosable(obj.cast(IID_IClosable));
    }

    close() {
        _IClosable.method(6).invoke(this._obj, []);
    }
}
module.exports = { BitmapBuffer, IMemoryBuffer, IClosable };
