// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IIterable_String = require('./IIterable_String');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_BitmapPropertySet = require('./BitmapPropertySet');

const IID_IBitmapPropertiesView = WinGuid.parse('7e0fe87a-3a70-48f8-9c55-196cf5a545f5');

const _IBitmapPropertiesView = DynWinRtType.registerInterface(
    "IBitmapPropertiesView", IID_IBitmapPropertiesView)
    .addMethod("GetPropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.hstring()])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.object())));

class BitmapPropertiesView {

    constructor(obj) {
        this._obj = obj.cast(IID_IBitmapPropertiesView);
    }

    async getPropertiesAsync(asyncInfo) {
        return new _m_BitmapPropertySet.BitmapPropertySet((await _IBitmapPropertiesView.method(6).invoke(this._obj, [asyncInfo._obj || asyncInfo]).toPromise()));
    }
}
module.exports = { BitmapPropertiesView };
