// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVectorView_String } = require('./IVectorView_String');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IBitmapCodecInformation = WinGuid.parse('400caaf2-c4b0-4392-a3b0-6f6f9ba95cb4');

const _IBitmapCodecInformation = DynWinRtType.registerInterface(
    "IBitmapCodecInformation", IID_IBitmapCodecInformation)
    .addMethod("get_CodecId", new DynWinRtMethodSig().addOut(DynWinRtType.guidType()))
    .addMethod("get_FileExtensions", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])))
    .addMethod("get_FriendlyName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_MimeTypes", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])));

class BitmapCodecInformation {

    constructor(obj) {
        this._obj = obj.cast(IID_IBitmapCodecInformation);
    }

    get codecId() {
        return _IBitmapCodecInformation.method(6).invoke(this._obj, []).toString();
    }

    get fileExtensions() {
        return new IVectorView_String(_IBitmapCodecInformation.method(7).invoke(this._obj, []));
    }

    get friendlyName() {
        return _IBitmapCodecInformation.method(8).invoke(this._obj, []).toString();
    }

    get mimeTypes() {
        return new IVectorView_String(_IBitmapCodecInformation.method(9).invoke(this._obj, []));
    }
}
module.exports = { BitmapCodecInformation };
