// Generated by winrt-meta — do not edit

const BitmapRotation = Object.freeze({ None: 0, Clockwise90Degrees: 1, Clockwise180Degrees: 2, Clockwise270Degrees: 3 });
module.exports = { BitmapRotation };
