// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { PixelDataProvider } = require('./PixelDataProvider');
const { SoftwareBitmap } = require('./SoftwareBitmap');
const { BitmapAlphaMode } = require('./BitmapAlphaMode');
const { ExifOrientationMode } = require('./ExifOrientationMode');
const { BitmapPropertiesView } = require('./BitmapPropertiesView');
const { BitmapPixelFormat } = require('./BitmapPixelFormat');
const { ColorManagementMode } = require('./ColorManagementMode');
const { ImageStream } = require('./ImageStream');
const { BitmapTransform } = require('./BitmapTransform');

const IID_IBitmapFrame = WinGuid.parse('72a49a1c-8081-438d-91bc-94ecfc8185c6');
const IID_IBitmapFrameWithSoftwareBitmap = WinGuid.parse('fe287c9a-420c-4963-87ad-691436e08383');

const _IBitmapFrame = DynWinRtType.registerInterface(
    "IBitmapFrame", IID_IBitmapFrame)
    .addMethod("GetThumbnailAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.ImageStream', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
    .addMethod("get_BitmapProperties", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.BitmapPropertiesView', WinGuid.parse('7e0fe87a-3a70-48f8-9c55-196cf5a545f5'))))
    .addMethod("get_BitmapPixelFormat", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])))
    .addMethod("get_BitmapAlphaMode", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])))
    .addMethod("get_DpiX", new DynWinRtMethodSig().addOut(DynWinRtType.f64()))
    .addMethod("get_DpiY", new DynWinRtMethodSig().addOut(DynWinRtType.f64()))
    .addMethod("get_PixelWidth", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_PixelHeight", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_OrientedPixelWidth", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_OrientedPixelHeight", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("GetPixelDataAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.PixelDataProvider', WinGuid.parse('dd831f25-185c-4595-9fb9-ccbe6ec18a6f')))))
    .addMethod("GetPixelDataTransformedAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])).addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.BitmapTransform', WinGuid.parse('ae755344-e268-4d35-adcf-e995d31a8d34'))).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.ExifOrientationMode', ['IgnoreExifOrientation', 'RespectExifOrientation'], [0, 1])).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.ColorManagementMode', ['DoNotColorManage', 'ColorManageToSRgb'], [0, 1])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.PixelDataProvider', WinGuid.parse('dd831f25-185c-4595-9fb9-ccbe6ec18a6f')))));

const _IBitmapFrameWithSoftwareBitmap = DynWinRtType.registerInterface(
    "IBitmapFrameWithSoftwareBitmap", IID_IBitmapFrameWithSoftwareBitmap)
    .addMethod("GetSoftwareBitmapAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073')))))
    .addMethod("GetSoftwareBitmapConvertedAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073')))))
    .addMethod("GetSoftwareBitmapTransformedAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])).addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.BitmapTransform', WinGuid.parse('ae755344-e268-4d35-adcf-e995d31a8d34'))).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.ExifOrientationMode', ['IgnoreExifOrientation', 'RespectExifOrientation'], [0, 1])).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.ColorManagementMode', ['DoNotColorManage', 'ColorManageToSRgb'], [0, 1])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073')))));

class BitmapFrame {

    constructor(obj) {
        this._obj = obj;
    }

    async getThumbnailAsync() {
        return new ImageStream((await _IBitmapFrame.method(6).invoke(this._obj, []).toPromise()));
    }

    get bitmapProperties() {
        return new BitmapPropertiesView(_IBitmapFrame.method(7).invoke(this._obj, []));
    }

    get bitmapPixelFormat() {
        return _IBitmapFrame.method(8).invoke(this._obj, []).toNumber();
    }

    get bitmapAlphaMode() {
        return _IBitmapFrame.method(9).invoke(this._obj, []).toNumber();
    }

    get dpiX() {
        return _IBitmapFrame.method(10).invoke(this._obj, []).toF64();
    }

    get dpiY() {
        return _IBitmapFrame.method(11).invoke(this._obj, []).toF64();
    }

    get pixelWidth() {
        return _IBitmapFrame.method(12).invoke(this._obj, []).toNumber();
    }

    get pixelHeight() {
        return _IBitmapFrame.method(13).invoke(this._obj, []).toNumber();
    }

    get orientedPixelWidth() {
        return _IBitmapFrame.method(14).invoke(this._obj, []).toNumber();
    }

    get orientedPixelHeight() {
        return _IBitmapFrame.method(15).invoke(this._obj, []).toNumber();
    }

    async getPixelDataAsync() {
        return new PixelDataProvider((await _IBitmapFrame.method(16).invoke(this._obj, []).toPromise()));
    }

    async getPixelDataTransformedAsync(asyncInfo, pixelFormat, alphaMode, transform, exifOrientationMode) {
        return new PixelDataProvider((await _IBitmapFrame.method(17).invoke(this._obj, [DynWinRtValue.i32(asyncInfo), DynWinRtValue.i32(pixelFormat), alphaMode._obj || alphaMode, DynWinRtValue.i32(transform), DynWinRtValue.i32(exifOrientationMode)]).toPromise()));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IBitmapFrameWithSoftwareBitmap {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IBitmapFrameWithSoftwareBitmap(obj.cast(IID_IBitmapFrameWithSoftwareBitmap));
    }

    async getSoftwareBitmapAsync() {
        return new SoftwareBitmap((await _IBitmapFrameWithSoftwareBitmap.method(6).invoke(this._obj, []).toPromise()));
    }

    async getSoftwareBitmapConvertedAsync(value, pixelFormat) {
        return new SoftwareBitmap((await _IBitmapFrameWithSoftwareBitmap.method(7).invoke(this._obj, [DynWinRtValue.i32(value), DynWinRtValue.i32(pixelFormat)]).toPromise()));
    }

    async getSoftwareBitmapTransformedAsync(value, pixelFormat, alphaMode, transform, exifOrientationMode) {
        return new SoftwareBitmap((await _IBitmapFrameWithSoftwareBitmap.method(8).invoke(this._obj, [DynWinRtValue.i32(value), DynWinRtValue.i32(pixelFormat), alphaMode._obj || alphaMode, DynWinRtValue.i32(transform), DynWinRtValue.i32(exifOrientationMode)]).toPromise()));
    }
}
module.exports = { BitmapFrame, IBitmapFrameWithSoftwareBitmap };
