// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_CatalogModelInstance = require('./CatalogModelInstance');
const _m_CatalogModelInstanceStatus = require('./CatalogModelInstanceStatus');

const IID_ICatalogModelInstanceResult = WinGuid.parse('b3701b71-61fa-5185-a2ce-8df6e6a5c66d');

const _ICatalogModelInstanceResult = DynWinRtType.registerInterface(
    "ICatalogModelInstanceResult", IID_ICatalogModelInstanceResult)
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.MachineLearning.CatalogModelInstanceStatus', ['Available', 'InProgress', 'Unavailable'], [0, 1, 2])))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.HResult', [DynWinRtType.i32()])))
    .addMethod("get_DiagnosticText", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("GetInstance", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInstance', WinGuid.parse('9e920521-5e06-5c30-b0c2-8af313efb756'))));

class CatalogModelInstanceResult {

    constructor(obj) {
        this._obj = obj.cast(IID_ICatalogModelInstanceResult);
    }

    get status() {
        return _ICatalogModelInstanceResult.method(6).invoke(this._obj, []).toNumber();
    }

    get extendedError() {
        return _ICatalogModelInstanceResult.method(7).invoke(this._obj, []).toNumber();
    }

    get diagnosticText() {
        return _ICatalogModelInstanceResult.method(8).invoke(this._obj, []).toString();
    }

    getInstance() {
        return new _m_CatalogModelInstance.CatalogModelInstance(_ICatalogModelInstanceResult.method(9).invoke(this._obj, []));
    }
}
module.exports = { CatalogModelInstanceResult };
