// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IVectorView_String = require('./IVectorView_String');
const _m_CatalogModelInfo = require('./CatalogModelInfo');

const IID_ICatalogModelInstance = WinGuid.parse('9e920521-5e06-5c30-b0c2-8af313efb756');
const IID_IClosable = WinGuid.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e');

const _ICatalogModelInstance = DynWinRtType.registerInterface(
    "ICatalogModelInstance", IID_ICatalogModelInstance)
    .addMethod("get_ModelPaths", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])))
    .addMethod("get_ModelInfo", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))));

const _IClosable = DynWinRtType.registerInterface(
    "IClosable", IID_IClosable)
    .addMethod("Close", new DynWinRtMethodSig());

class CatalogModelInstance {

    constructor(obj) {
        this._obj = obj.cast(IID_ICatalogModelInstance);
    }

    get modelPaths() {
        return new _m_IVectorView_String.IVectorView_String(_ICatalogModelInstance.method(6).invoke(this._obj, []));
    }

    get modelInfo() {
        return new _m_CatalogModelInfo.CatalogModelInfo(_ICatalogModelInstance.method(7).invoke(this._obj, []));
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IClosable {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IClosable(obj.cast(IID_IClosable));
    }

    close() {
        _IClosable.method(6).invoke(this._obj, []);
    }
}
module.exports = { CatalogModelInstance, IClosable };
