// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const { ImageContentFilterSeverity } = require('./ImageContentFilterSeverity');
const { TextContentFilterSeverity } = require('./TextContentFilterSeverity');

const IID_IContentFilterOptions = WinGuid.parse('6808be9f-80d2-5136-8a8a-1f5c52c824ad');

const _IContentFilterOptions = DynWinRtType.registerInterface(
    "IContentFilterOptions", IID_IContentFilterOptions)
    .addMethod("get_PromptMaxAllowedSeverityLevel", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.TextContentFilterSeverity', WinGuid.parse('68c1ee47-c35c-5f4c-a647-b0c0f64aa0d5'))))
    .addMethod("put_PromptMaxAllowedSeverityLevel", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.TextContentFilterSeverity', WinGuid.parse('68c1ee47-c35c-5f4c-a647-b0c0f64aa0d5'))))
    .addMethod("get_ResponseMaxAllowedSeverityLevel", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.TextContentFilterSeverity', WinGuid.parse('68c1ee47-c35c-5f4c-a647-b0c0f64aa0d5'))))
    .addMethod("put_ResponseMaxAllowedSeverityLevel", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.TextContentFilterSeverity', WinGuid.parse('68c1ee47-c35c-5f4c-a647-b0c0f64aa0d5'))))
    .addMethod("get_ImageMaxAllowedSeverityLevel", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.ImageContentFilterSeverity', WinGuid.parse('f1563582-c66a-5861-9995-1440b05191ac'))))
    .addMethod("put_ImageMaxAllowedSeverityLevel", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.ImageContentFilterSeverity', WinGuid.parse('f1563582-c66a-5861-9995-1440b05191ac'))));

class ContentFilterOptions {

    constructor(obj) {
        this._obj = obj;
    }

    static create() {
        return new ContentFilterOptions(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Microsoft.Windows.AI.ContentSafety.ContentFilterOptions'), []));
    }

    get promptMaxAllowedSeverityLevel() {
        return new TextContentFilterSeverity(_IContentFilterOptions.method(6).invoke(this._obj, []));
    }

    set promptMaxAllowedSeverityLevel(value) {
        _IContentFilterOptions.method(7).invoke(this._obj, [value._obj || value]);
    }

    get responseMaxAllowedSeverityLevel() {
        return new TextContentFilterSeverity(_IContentFilterOptions.method(8).invoke(this._obj, []));
    }

    set responseMaxAllowedSeverityLevel(value) {
        _IContentFilterOptions.method(9).invoke(this._obj, [value._obj || value]);
    }

    get imageMaxAllowedSeverityLevel() {
        return new ImageContentFilterSeverity(_IContentFilterOptions.method(10).invoke(this._obj, []));
    }

    set imageMaxAllowedSeverityLevel(value) {
        _IContentFilterOptions.method(11).invoke(this._obj, [value._obj || value]);
    }
}
module.exports = { ContentFilterOptions };
