// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));

const IID_IConversationItem = WinGuid.parse('957b0b85-4d7e-5788-baae-af7cf256bb8e');

const _IConversationItem = DynWinRtType.registerInterface(
    "IConversationItem", IID_IConversationItem)
    .addMethod("get_Participant", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Participant", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Message", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Message", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()));

class ConversationItem {

    constructor(obj) {
        this._obj = obj;
    }

    static create() {
        return new ConversationItem(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Microsoft.Windows.AI.Text.ConversationItem'), []));
    }

    get participant() {
        return _IConversationItem.method(6).invoke(this._obj, []).toString();
    }

    set participant(value) {
        _IConversationItem.method(7).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get message() {
        return _IConversationItem.method(8).invoke(this._obj, []).toString();
    }

    set message(value) {
        _IConversationItem.method(9).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
}
module.exports = { ConversationItem };
