// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const { InputKind } = require('./InputKind');

const IID_IConversationSummaryOptions = WinGuid.parse('360bce9f-fd14-5d0e-bd24-fd78ed3038e6');

const _IConversationSummaryOptions = DynWinRtType.registerInterface(
    "IConversationSummaryOptions", IID_IConversationSummaryOptions)
    .addMethod("get_InputKind", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.Text.InputKind', ['GeneralConversation', 'Email'], [0, 1])))
    .addMethod("put_InputKind", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Microsoft.Windows.AI.Text.InputKind', ['GeneralConversation', 'Email'], [0, 1])))
    .addMethod("get_IncludeMessageCitations", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("put_IncludeMessageCitations", new DynWinRtMethodSig().addIn(DynWinRtType.boolType()))
    .addMethod("get_IncludeParticipantAttribution", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("put_IncludeParticipantAttribution", new DynWinRtMethodSig().addIn(DynWinRtType.boolType()))
    .addMethod("get_MaxKeyPoints", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_MaxKeyPoints", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Language", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Language", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()));

class ConversationSummaryOptions {

    constructor(obj) {
        this._obj = obj;
    }

    static create() {
        return new ConversationSummaryOptions(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Microsoft.Windows.AI.Text.ConversationSummaryOptions'), []));
    }

    get inputKind() {
        return _IConversationSummaryOptions.method(6).invoke(this._obj, []).toNumber();
    }

    set inputKind(value) {
        _IConversationSummaryOptions.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get includeMessageCitations() {
        return _IConversationSummaryOptions.method(8).invoke(this._obj, []).toBool();
    }

    set includeMessageCitations(value) {
        _IConversationSummaryOptions.method(9).invoke(this._obj, [DynWinRtValue.boolValue(value)]);
    }

    get includeParticipantAttribution() {
        return _IConversationSummaryOptions.method(10).invoke(this._obj, []).toBool();
    }

    set includeParticipantAttribution(value) {
        _IConversationSummaryOptions.method(11).invoke(this._obj, [DynWinRtValue.boolValue(value)]);
    }

    get maxKeyPoints() {
        return _IConversationSummaryOptions.method(12).invoke(this._obj, []).toNumber();
    }

    set maxKeyPoints(value) {
        _IConversationSummaryOptions.method(13).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get language() {
        return _IConversationSummaryOptions.method(14).invoke(this._obj, []).toString();
    }

    set language(value) {
        _IConversationSummaryOptions.method(15).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
}
module.exports = { ConversationSummaryOptions };
