// Generated by winrt-meta — do not edit

const CreationCollisionOption = Object.freeze({ GenerateUniqueName: 0, ReplaceExisting: 1, FailIfExists: 2, OpenIfExists: 3 });
module.exports = { CreationCollisionOption };
