// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');

const IID_IEmbeddingVector = WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c');
const IID_IEmbeddingVectorFactory = WinGuid.parse('16b72758-2b69-5e97-b865-6a6a71683dd0');

const _IEmbeddingVector = DynWinRtType.registerInterface(
    "IEmbeddingVector", IID_IEmbeddingVector)
    .addMethod("GetValues", new DynWinRtMethodSig().addOutFill(DynWinRtType.arrayType(DynWinRtType.f32())))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_VectorSpaceId", new DynWinRtMethodSig().addOut(DynWinRtType.guidType()));

const _IEmbeddingVectorFactory = DynWinRtType.registerInterface(
    "IEmbeddingVectorFactory", IID_IEmbeddingVectorFactory)
    .addMethod("CreateInstance", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.f32())).addIn(DynWinRtType.guidType()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))));

class EmbeddingVector {
    static _f_IEmbeddingVectorFactory;
    static f_IEmbeddingVectorFactory() { return EmbeddingVector._f_IEmbeddingVectorFactory ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Foundation.EmbeddingVector').cast(IID_IEmbeddingVectorFactory); }

    constructor(obj) {
        this._obj = obj.cast(IID_IEmbeddingVector);
    }

    static createInstance(value, data) {
        return new EmbeddingVector(_IEmbeddingVectorFactory.method(6).invoke(EmbeddingVector.f_IEmbeddingVectorFactory(), [value.toValue(), DynWinRtValue.guid(WinGuid.parse(data))]));
    }

    getValues(values) {
        return _IEmbeddingVector.method(6).invoke(this._obj, [values.toValue()]).asArray().toF32Vec();
    }

    get size() {
        return _IEmbeddingVector.method(7).invoke(this._obj, []).toNumber();
    }

    get vectorSpaceId() {
        return _IEmbeddingVector.method(8).invoke(this._obj, []).toString();
    }
}
module.exports = { EmbeddingVector };
