// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { ExecutionProviderReadyResultState } = require('./ExecutionProviderReadyResultState');

const IID_IExecutionProviderReadyResult = WinGuid.parse('91c1724d-93c7-5284-adbe-ba2bd7be7c79');

const _IExecutionProviderReadyResult = DynWinRtType.registerInterface(
    "IExecutionProviderReadyResult", IID_IExecutionProviderReadyResult)
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.MachineLearning.ExecutionProviderReadyResultState', ['InProgress', 'Success', 'Failure'], [0, 1, 2])))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.HResult', [DynWinRtType.i32()])))
    .addMethod("get_DiagnosticText", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

class ExecutionProviderReadyResult {

    constructor(obj) {
        this._obj = obj.cast(IID_IExecutionProviderReadyResult);
    }

    get status() {
        return _IExecutionProviderReadyResult.method(6).invoke(this._obj, []).toNumber();
    }

    get extendedError() {
        return _IExecutionProviderReadyResult.method(7).invoke(this._obj, []).toNumber();
    }

    get diagnosticText() {
        return _IExecutionProviderReadyResult.method(8).invoke(this._obj, []).toString();
    }
}
module.exports = { ExecutionProviderReadyResult };
