// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVector_ExecutionProvider } = require('./IVector_ExecutionProvider');
const { ExecutionProvider } = require('./ExecutionProvider');

const IID_IExecutionProviderCatalog = WinGuid.parse('aa9bfe14-2222-5921-8002-4d2a205ea03c');
const IID_IExecutionProviderCatalogStatics = WinGuid.parse('550def98-2611-5433-afb8-43673b610848');

const _IExecutionProviderCatalog = DynWinRtType.registerInterface(
    "IExecutionProviderCatalog", IID_IExecutionProviderCatalog)
    .addMethod("FindAllProviders", new DynWinRtMethodSig().addOut(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff')))))
    .addMethod("EnsureAndRegisterCertifiedAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))]), DynWinRtType.f64())))
    .addMethod("RegisterCertifiedAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))]), DynWinRtType.f64())));

const _IExecutionProviderCatalogStatics = DynWinRtType.registerInterface(
    "IExecutionProviderCatalogStatics", IID_IExecutionProviderCatalogStatics)
    .addMethod("GetDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProviderCatalog', WinGuid.parse('aa9bfe14-2222-5921-8002-4d2a205ea03c'))));

class ExecutionProviderCatalog {
    static _s_IExecutionProviderCatalogStatics;
    static s_IExecutionProviderCatalogStatics() { return ExecutionProviderCatalog._s_IExecutionProviderCatalogStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.MachineLearning.ExecutionProviderCatalog').cast(IID_IExecutionProviderCatalogStatics); }

    constructor(obj) {
        this._obj = obj;
    }

    static getDefault() {
        return new ExecutionProviderCatalog(_IExecutionProviderCatalogStatics.method(6).invoke(ExecutionProviderCatalog.s_IExecutionProviderCatalogStatics(), []));
    }

    findAllProviders() {
        return _IExecutionProviderCatalog.method(6).invoke(this._obj, []).asArray().toValues().map(v => new ExecutionProvider(v));
    }

    async ensureAndRegisterCertifiedAsync() {
        return new IVector_ExecutionProvider((await _IExecutionProviderCatalog.method(7).invoke(this._obj, []).toPromise()));
    }

    async registerCertifiedAsync() {
        return new IVector_ExecutionProvider((await _IExecutionProviderCatalog.method(8).invoke(this._obj, []).toPromise()));
    }
}
module.exports = { ExecutionProviderCatalog };
