// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_BitmapTransform = require('./BitmapTransform');
const _m_ColorManagementMode = require('./ColorManagementMode');
const _m_BitmapPixelFormat = require('./BitmapPixelFormat');
const _m_SoftwareBitmap = require('./SoftwareBitmap');
const _m_BitmapAlphaMode = require('./BitmapAlphaMode');
const _m_ExifOrientationMode = require('./ExifOrientationMode');

const IID_IBitmapFrameWithSoftwareBitmap = WinGuid.parse('fe287c9a-420c-4963-87ad-691436e08383');

const _IBitmapFrameWithSoftwareBitmap = DynWinRtType.registerInterface(
    "IBitmapFrameWithSoftwareBitmap", IID_IBitmapFrameWithSoftwareBitmap)
    .addMethod("GetSoftwareBitmapAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073')))))
    .addMethod("GetSoftwareBitmapConvertedAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073')))))
    .addMethod("GetSoftwareBitmapTransformedAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])).addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.BitmapTransform', WinGuid.parse('ae755344-e268-4d35-adcf-e995d31a8d34'))).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.ExifOrientationMode', ['IgnoreExifOrientation', 'RespectExifOrientation'], [0, 1])).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.ColorManagementMode', ['DoNotColorManage', 'ColorManageToSRgb'], [0, 1])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073')))));

class IBitmapFrameWithSoftwareBitmap {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IBitmapFrameWithSoftwareBitmap(obj.cast(IID_IBitmapFrameWithSoftwareBitmap));
    }

    async getSoftwareBitmapAsync() {
        return new _m_SoftwareBitmap.SoftwareBitmap((await _IBitmapFrameWithSoftwareBitmap.method(6).invoke(this._obj, []).toPromise()));
    }

    async getSoftwareBitmapConvertedAsync(value, pixelFormat) {
        return new _m_SoftwareBitmap.SoftwareBitmap((await _IBitmapFrameWithSoftwareBitmap.method(7).invoke(this._obj, [DynWinRtValue.i32(value), DynWinRtValue.i32(pixelFormat)]).toPromise()));
    }

    async getSoftwareBitmapTransformedAsync(value, pixelFormat, alphaMode, transform, exifOrientationMode) {
        return new _m_SoftwareBitmap.SoftwareBitmap((await _IBitmapFrameWithSoftwareBitmap.method(8).invoke(this._obj, [DynWinRtValue.i32(value), DynWinRtValue.i32(pixelFormat), alphaMode._obj || alphaMode, DynWinRtValue.i32(transform), DynWinRtValue.i32(exifOrientationMode)]).toPromise()));
    }
}
module.exports = { IID_IBitmapFrameWithSoftwareBitmap, IBitmapFrameWithSoftwareBitmap };
