// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IBuffer = WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da');

const _IBuffer = DynWinRtType.registerInterface(
    "IBuffer", IID_IBuffer)
    .addMethod("get_Capacity", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Length", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Length", new DynWinRtMethodSig().addIn(DynWinRtType.u32()));

class IBuffer {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IBuffer(obj.cast(IID_IBuffer));
    }

    get capacity() {
        return _IBuffer.method(6).invoke(this._obj, []).toNumber();
    }

    get length() {
        return _IBuffer.method(7).invoke(this._obj, []).toNumber();
    }

    set length(value) {
        _IBuffer.method(8).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }
}
module.exports = { IID_IBuffer, IBuffer };
