// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');

const IID_IIterator_Object = DynWinRtType.parameterized(WinGuid.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRtType.object()]).iid();

const _IIterator_Object = DynWinRtType.registerInterface(
    "IIterator_Object", IID_IIterator_Object)
    .addMethod("get_Current", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
    .addMethod("get_HasCurrent", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("MoveNext", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addOutFill(DynWinRtType.arrayType(DynWinRtType.object())).addOut(DynWinRtType.u32()));

class IIterator_Object {
    constructor(obj) {
        this._obj = obj.cast(IID_IIterator_Object);
    }

    static from(obj) {
        return new IIterator_Object(obj.cast(IID_IIterator_Object));
    }

    get current() {
        return _IIterator_Object.method(6).invoke(this._obj, []);
    }

    get hasCurrent() {
        return _IIterator_Object.method(7).invoke(this._obj, []).toBool();
    }

    moveNext() {
        return _IIterator_Object.method(8).invoke(this._obj, []).toBool();
    }

    getMany(items) {
        return _IIterator_Object.method(9).invoke(this._obj, [items.toValue()]).toNumber();
    }
}
module.exports = { IID_IIterator_Object, IIterator_Object };
