// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IIterator_Object } = require('./IIterator_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');

const IID_IIterable_IKeyValuePair_String_Object = DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.object()])]).iid();

const _IIterable_IKeyValuePair_String_Object = DynWinRtType.registerInterface(
    "IIterable_IKeyValuePair_String_Object", IID_IIterable_IKeyValuePair_String_Object)
    .addMethod("First", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRtType.object()])));

class IIterable_IKeyValuePair_String_Object {
    constructor(obj) {
        this._obj = obj.cast(IID_IIterable_IKeyValuePair_String_Object);
    }

    static from(obj) {
        return new IIterable_IKeyValuePair_String_Object(obj.cast(IID_IIterable_IKeyValuePair_String_Object));
    }

    first() {
        return new IIterator_Object(_IIterable_IKeyValuePair_String_Object.method(6).invoke(this._obj, []));
    }
}
module.exports = { IID_IIterable_IKeyValuePair_String_Object, IIterable_IKeyValuePair_String_Object };
