// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IIterator_String } = require('./IIterator_String');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IIterable_String = DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.hstring()]).iid();

const _IIterable_String = DynWinRtType.registerInterface(
    "IIterable_String", IID_IIterable_String)
    .addMethod("First", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRtType.hstring()])));

class IIterable_String {
    constructor(obj) {
        this._obj = obj.cast(IID_IIterable_String);
    }

    static from(obj) {
        return new IIterable_String(obj.cast(IID_IIterable_String));
    }

    first() {
        return new IIterator_String(_IIterable_String.method(6).invoke(this._obj, []));
    }
}
module.exports = { IID_IIterable_String, IIterable_String };
