// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IIterator_Object } = require('./IIterator_Object');

const IID_IIterable_IKeyValuePair_String_String = DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.hstring()])]).iid();

const _IIterable_IKeyValuePair_String_String = DynWinRtType.registerInterface(
    "IIterable_IKeyValuePair_String_String", IID_IIterable_IKeyValuePair_String_String)
    .addMethod("First", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRtType.object()])));

class IIterable_IKeyValuePair_String_String {
    constructor(obj) {
        this._obj = obj.cast(IID_IIterable_IKeyValuePair_String_String);
    }

    static from(obj) {
        return new IIterable_IKeyValuePair_String_String(obj.cast(IID_IIterable_IKeyValuePair_String_String));
    }

    first() {
        return new IIterator_Object(_IIterable_IKeyValuePair_String_String.method(6).invoke(this._obj, []));
    }
}
module.exports = { IID_IIterable_IKeyValuePair_String_String, IIterable_IKeyValuePair_String_String };
