// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_EmbeddingVector = require('./EmbeddingVector');

const IID_IIterator_EmbeddingVector = DynWinRtType.parameterized(WinGuid.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))]).iid();

const _IIterator_EmbeddingVector = DynWinRtType.registerInterface(
    "IIterator_EmbeddingVector", IID_IIterator_EmbeddingVector)
    .addMethod("get_Current", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))))
    .addMethod("get_HasCurrent", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("MoveNext", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c')))).addOut(DynWinRtType.u32()));

class IIterator_EmbeddingVector {
    constructor(obj) {
        this._obj = obj.cast(IID_IIterator_EmbeddingVector);
    }

    static from(obj) {
        return new IIterator_EmbeddingVector(obj.cast(IID_IIterator_EmbeddingVector));
    }

    get current() {
        return new _m_EmbeddingVector.EmbeddingVector(_IIterator_EmbeddingVector.method(6).invoke(this._obj, []));
    }

    get hasCurrent() {
        return _IIterator_EmbeddingVector.method(7).invoke(this._obj, []).toBool();
    }

    moveNext() {
        return _IIterator_EmbeddingVector.method(8).invoke(this._obj, []).toBool();
    }

    getMany(items) {
        return _IIterator_EmbeddingVector.method(9).invoke(this._obj, [items.toValue()]).toNumber();
    }
}
module.exports = { IID_IIterator_EmbeddingVector, IIterator_EmbeddingVector };
