// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');

const IID_IKeyValuePair_String_String = DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.hstring()]).iid();

const _IKeyValuePair_String_String = DynWinRtType.registerInterface(
    "IKeyValuePair_String_String", IID_IKeyValuePair_String_String)
    .addMethod("get_Key", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Value", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

class IKeyValuePair_String_String {
    constructor(obj) {
        this._obj = obj.cast(IID_IKeyValuePair_String_String);
    }

    static from(obj) {
        return new IKeyValuePair_String_String(obj.cast(IID_IKeyValuePair_String_String));
    }

    get key() {
        return _IKeyValuePair_String_String.method(6).invoke(this._obj, []).toString();
    }

    get value() {
        return _IKeyValuePair_String_String.method(7).invoke(this._obj, []).toString();
    }
}
module.exports = { IID_IKeyValuePair_String_String, IKeyValuePair_String_String };
