// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');

const IID_IKeyValuePair_String_Object = DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.object()]).iid();

const _IKeyValuePair_String_Object = DynWinRtType.registerInterface(
    "IKeyValuePair_String_Object", IID_IKeyValuePair_String_Object)
    .addMethod("get_Key", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Value", new DynWinRtMethodSig().addOut(DynWinRtType.object()));

class IKeyValuePair_String_Object {
    constructor(obj) {
        this._obj = obj.cast(IID_IKeyValuePair_String_Object);
    }

    static from(obj) {
        return new IKeyValuePair_String_Object(obj.cast(IID_IKeyValuePair_String_Object));
    }

    get key() {
        return _IKeyValuePair_String_Object.method(6).invoke(this._obj, []).toString();
    }

    get value() {
        return _IKeyValuePair_String_Object.method(7).invoke(this._obj, []);
    }
}
module.exports = { IID_IKeyValuePair_String_Object, IKeyValuePair_String_Object };
