// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_SoftwareBitmap = require('./SoftwareBitmap');
const _m_AIFeatureReadyResult = require('./AIFeatureReadyResult');
const _m_AIFeatureReadyState = require('./AIFeatureReadyState');
const _m_ImageBuffer = require('./ImageBuffer');
const { IID_IClosable } = require('./IClosable');
const _m_IClosable = require('./IClosable');

const IID_IImageObjectRemover = WinGuid.parse('cfa20faf-5ae1-5b8c-b0d8-e7c64db59d26');
const IID_IImageObjectRemoverStatics = WinGuid.parse('cbcbd7e1-5b81-503f-8fcb-66ae1d6e5b9c');

const _IImageObjectRemover = DynWinRtType.registerInterface(
    "IImageObjectRemover", IID_IImageObjectRemover)
    .addMethod("RemoveFromSoftwareBitmap", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))).addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("RemoveFromImageBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addOut(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))));

const _IImageObjectRemoverStatics = DynWinRtType.registerInterface(
    "IImageObjectRemoverStatics", IID_IImageObjectRemoverStatics)
    .addMethod("GetReadyState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.AIFeatureReadyState', ['Ready', 'NotReady', 'NotSupportedOnCurrentSystem', 'DisabledByUser'], [0, 1, 2, 3])))
    .addMethod("EnsureReadyAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.AIFeatureReadyResult', WinGuid.parse('936a78a6-c242-5937-9814-e512d4193a6d')), DynWinRtType.f64())))
    .addMethod("CreateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageObjectRemover', WinGuid.parse('cfa20faf-5ae1-5b8c-b0d8-e7c64db59d26')))));

class ImageObjectRemover {
    static _s_IImageObjectRemoverStatics;
    static s_IImageObjectRemoverStatics() { return ImageObjectRemover._s_IImageObjectRemoverStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Imaging.ImageObjectRemover').cast(IID_IImageObjectRemoverStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_IImageObjectRemover);
    }

    static getReadyState() {
        return _IImageObjectRemoverStatics.method(6).invoke(ImageObjectRemover.s_IImageObjectRemoverStatics(), []).toNumber();
    }

    static ensureReadyAsync() {
        const _op = _IImageObjectRemoverStatics.method(7).invoke(ImageObjectRemover.s_IImageObjectRemoverStatics(), []);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_AIFeatureReadyResult.AIFeatureReadyResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    static async createAsync() {
        return new ImageObjectRemover((await _IImageObjectRemoverStatics.method(8).invoke(ImageObjectRemover.s_IImageObjectRemoverStatics(), []).toPromise()));
    }

    removeFromSoftwareBitmap(result, softwareBitmap) {
        return new _m_SoftwareBitmap.SoftwareBitmap(_IImageObjectRemover.method(6).invoke(this._obj, [result._obj || result, softwareBitmap._obj || softwareBitmap]));
    }

    removeFromImageBuffer(result, imageBuffer) {
        return new _m_ImageBuffer.ImageBuffer(_IImageObjectRemover.method(7).invoke(this._obj, [result._obj || result, imageBuffer._obj || imageBuffer]));
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { ImageObjectRemover };
