// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { IID_IBuffer } = require('./IBuffer');
const _m_IBuffer = require('./IBuffer');
const _m_ImageBufferPixelFormat = require('./ImageBufferPixelFormat');
const _m_SoftwareBitmap = require('./SoftwareBitmap');
const { IID_IClosable } = require('./IClosable');
const _m_IClosable = require('./IClosable');

const IID_IImageBuffer = WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461');
const IID_IImageBufferStatics = WinGuid.parse('35b17bd3-f346-529f-8c0f-3bf96c56eb13');

const _IImageBuffer = DynWinRtType.registerInterface(
    "IImageBuffer", IID_IImageBuffer)
    .addMethod("get_Buffer", new DynWinRtMethodSig().addOut(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("get_PixelFormat", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Graphics.Imaging.ImageBufferPixelFormat', ['Rgb8', 'Rgba8', 'Argb8', 'Bgra8', 'Gray8'], [137224, 30, 2498570, 87, 62])))
    .addMethod("get_PixelHeight", new DynWinRtMethodSig().addOut(DynWinRtType.i32()))
    .addMethod("get_PixelWidth", new DynWinRtMethodSig().addOut(DynWinRtType.i32()))
    .addMethod("get_RowStride", new DynWinRtMethodSig().addOut(DynWinRtType.i32()))
    .addMethod("CopyToByteArray", new DynWinRtMethodSig().addOutFill(DynWinRtType.arrayType(DynWinRtType.u8())))
    .addMethod("CopyToSoftwareBitmap", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))));

const _IImageBufferStatics = DynWinRtType.registerInterface(
    "IImageBufferStatics", IID_IImageBufferStatics)
    .addMethod("CreateForBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))).addIn(DynWinRtType.enumType('Microsoft.Graphics.Imaging.ImageBufferPixelFormat', ['Rgb8', 'Rgba8', 'Argb8', 'Bgra8', 'Gray8'], [137224, 30, 2498570, 87, 62])).addIn(DynWinRtType.i32()).addIn(DynWinRtType.i32()).addIn(DynWinRtType.i32()).addOut(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))))
    .addMethod("CreateForSoftwareBitmap", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))).addOut(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))));

class ImageBuffer {
    static _s_IImageBufferStatics;
    static s_IImageBufferStatics() { return ImageBuffer._s_IImageBufferStatics ??= DynWinRtValue.activationFactory('Microsoft.Graphics.Imaging.ImageBuffer').cast(IID_IImageBufferStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_IImageBuffer);
    }

    static createForBuffer(result, buffer, pixelFormat, width, height) {
        return new ImageBuffer(_IImageBufferStatics.method(6).invoke(ImageBuffer.s_IImageBufferStatics(), [result._obj || result, DynWinRtValue.i32(buffer), DynWinRtValue.i32(pixelFormat), DynWinRtValue.i32(width), DynWinRtValue.i32(height)]));
    }

    static createForSoftwareBitmap(result) {
        return new ImageBuffer(_IImageBufferStatics.method(7).invoke(ImageBuffer.s_IImageBufferStatics(), [result._obj || result]));
    }

    get buffer() {
        return new _m_IBuffer.IBuffer(_IImageBuffer.method(6).invoke(this._obj, []));
    }

    get pixelFormat() {
        return _IImageBuffer.method(7).invoke(this._obj, []).toNumber();
    }

    get pixelHeight() {
        return _IImageBuffer.method(8).invoke(this._obj, []).toNumber();
    }

    get pixelWidth() {
        return _IImageBuffer.method(9).invoke(this._obj, []).toNumber();
    }

    get rowStride() {
        return _IImageBuffer.method(10).invoke(this._obj, []).toNumber();
    }

    copyToByteArray(values) {
        return _IImageBuffer.method(11).invoke(this._obj, [values.toValue()]).asArray().toU8Vec();
    }

    copyToSoftwareBitmap() {
        return new _m_SoftwareBitmap.SoftwareBitmap(_IImageBuffer.method(12).invoke(this._obj, []));
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { ImageBuffer };
