// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { IID_IBuffer, IBuffer } = require('./IBuffer');
const { InputStreamOptions } = require('./InputStreamOptions');
const { IID_IInputStream, IInputStream } = require('./IInputStream');
const { IID_IOutputStream, IOutputStream } = require('./IOutputStream');
const { IID_IRandomAccessStream, IRandomAccessStream } = require('./IRandomAccessStream');

const IID_IRandomAccessStreamWithContentType = WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038');
const IID_IContentTypeProvider = WinGuid.parse('97d098a5-3b99-4de9-88a5-e11d2f50c795');
const IID_IClosable = WinGuid.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e');

const _IRandomAccessStreamWithContentType = DynWinRtType.registerInterface(
    "IRandomAccessStreamWithContentType", IID_IRandomAccessStreamWithContentType);

const _IContentTypeProvider = DynWinRtType.registerInterface(
    "IContentTypeProvider", IID_IContentTypeProvider)
    .addMethod("get_ContentType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

const _IRandomAccessStream = DynWinRtType.registerInterface(
    "IRandomAccessStream", IID_IRandomAccessStream)
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u64()))
    .addMethod("put_Size", new DynWinRtMethodSig().addIn(DynWinRtType.u64()))
    .addMethod("GetInputStreamAt", new DynWinRtMethodSig().addIn(DynWinRtType.u64()).addOut(DynWinRtType.interface(WinGuid.parse('905a0fe2-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("GetOutputStreamAt", new DynWinRtMethodSig().addIn(DynWinRtType.u64()).addOut(DynWinRtType.interface(WinGuid.parse('905a0fe6-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("get_Position", new DynWinRtMethodSig().addOut(DynWinRtType.u64()))
    .addMethod("Seek", new DynWinRtMethodSig().addIn(DynWinRtType.u64()))
    .addMethod("CloneStream", new DynWinRtMethodSig().addOut(DynWinRtType.interface(WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("get_CanRead", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_CanWrite", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));

const _IOutputStream = DynWinRtType.registerInterface(
    "IOutputStream", IID_IOutputStream)
    .addMethod("WriteAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.u32(), DynWinRtType.u32())))
    .addMethod("FlushAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.boolType())));

const _IClosable = DynWinRtType.registerInterface(
    "IClosable", IID_IClosable)
    .addMethod("Close", new DynWinRtMethodSig());

const _IInputStream = DynWinRtType.registerInterface(
    "IInputStream", IID_IInputStream)
    .addMethod("ReadAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))).addIn(DynWinRtType.u32()).addIn(DynWinRtType.enumType('Windows.Storage.Streams.InputStreamOptions', ['None', 'Partial', 'ReadAhead'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da')), DynWinRtType.u32())));

class ImageStream {

    constructor(obj) {
        this._obj = obj.cast(IID_IRandomAccessStreamWithContentType);
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IContentTypeProvider {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IContentTypeProvider(obj.cast(IID_IContentTypeProvider));
    }

    get contentType() {
        return _IContentTypeProvider.method(6).invoke(this._obj, []).toString();
    }
}

class IClosable {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IClosable(obj.cast(IID_IClosable));
    }

    close() {
        _IClosable.method(6).invoke(this._obj, []);
    }
}
module.exports = { ImageStream, IContentTypeProvider, IRandomAccessStream, IOutputStream, IClosable, IInputStream };
