// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IIterable_IKeyValuePair_String_Object } = require('./IIterable_IKeyValuePair_String_Object');
const { IIterable_String } = require('./IIterable_String');
const { IKeyValuePair_String_Object } = require('./IKeyValuePair_String_Object');
const { IMap_String_Object } = require('./IMap_String_Object');
const { IReference_Double } = require('./IReference_Double');
const { IVectorView_String } = require('./IVectorView_String');
const { IVector_String } = require('./IVector_String');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { PhotoOrientation } = require('./PhotoOrientation');

const IID_IImageProperties = WinGuid.parse('523c9424-fcff-4275-afee-ecdb9ab47973');
const IID_IStorageItemExtraProperties = WinGuid.parse('c54361b2-54cd-432b-bdbc-4b19c4b470d7');

const _IImageProperties = DynWinRtType.registerInterface(
    "IImageProperties", IID_IImageProperties)
    .addMethod("get_Rating", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Rating", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Keywords", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_DateTaken", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("put_DateTaken", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("get_Width", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Height", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Title", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Title", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Latitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_Longitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_CameraManufacturer", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_CameraManufacturer", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_CameraModel", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_CameraModel", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Orientation", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileProperties.PhotoOrientation', ['Unspecified', 'Normal', 'FlipHorizontal', 'Rotate180', 'FlipVertical', 'Transpose', 'Rotate270', 'Transverse', 'Rotate90'], [0, 1, 2, 3, 4, 5, 6, 7, 8])))
    .addMethod("get_PeopleNames", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])));

const _IStorageItemExtraProperties = DynWinRtType.registerInterface(
    "IStorageItemExtraProperties", IID_IStorageItemExtraProperties)
    .addMethod("RetrievePropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.hstring()])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('3c2925fe-8519-45c1-aa79-197b6718c1c1'), [DynWinRtType.hstring(), DynWinRtType.object()]))))
    .addMethod("SavePropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.object()])])).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("SavePropertiesAsyncOverloadDefault", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()));

function _unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
function _packDateTime(v) {
    const s = DynWinRtStruct.create(_DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}

class ImageProperties {

    constructor(obj) {
        this._obj = obj.cast(IID_IImageProperties);
    }

    get rating() {
        return _IImageProperties.method(6).invoke(this._obj, []).toNumber();
    }

    set rating(value) {
        _IImageProperties.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get keywords() {
        return new IVector_String(_IImageProperties.method(8).invoke(this._obj, []));
    }

    get dateTaken() {
        return _unpackDateTime(_IImageProperties.method(9).invoke(this._obj, []));
    }

    set dateTaken(value) {
        _IImageProperties.method(10).invoke(this._obj, [_packDateTime(value).toValue()]);
    }

    get width() {
        return _IImageProperties.method(11).invoke(this._obj, []).toNumber();
    }

    get height() {
        return _IImageProperties.method(12).invoke(this._obj, []).toNumber();
    }

    get title() {
        return _IImageProperties.method(13).invoke(this._obj, []).toString();
    }

    set title(value) {
        _IImageProperties.method(14).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get latitude() {
        return new IReference_Double(_IImageProperties.method(15).invoke(this._obj, []));
    }

    get longitude() {
        return new IReference_Double(_IImageProperties.method(16).invoke(this._obj, []));
    }

    get cameraManufacturer() {
        return _IImageProperties.method(17).invoke(this._obj, []).toString();
    }

    set cameraManufacturer(value) {
        _IImageProperties.method(18).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get cameraModel() {
        return _IImageProperties.method(19).invoke(this._obj, []).toString();
    }

    set cameraModel(value) {
        _IImageProperties.method(20).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get orientation() {
        return _IImageProperties.method(21).invoke(this._obj, []).toNumber();
    }

    get peopleNames() {
        return new IVectorView_String(_IImageProperties.method(22).invoke(this._obj, []));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IStorageItemExtraProperties {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageItemExtraProperties(obj.cast(IID_IStorageItemExtraProperties));
    }

    async retrievePropertiesAsync(operation) {
        return new IMap_String_Object((await _IStorageItemExtraProperties.method(6).invoke(this._obj, [operation._obj || operation]).toPromise()));
    }

    async savePropertiesAsync(operation) {
        return (await _IStorageItemExtraProperties.method(7).invoke(this._obj, [operation._obj || operation]).toPromise());
    }

    async savePropertiesAsyncOverloadDefault() {
        return (await _IStorageItemExtraProperties.method(8).invoke(this._obj, []).toPromise());
    }
}
module.exports = { ImageProperties, IStorageItemExtraProperties };
