// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_ImageBuffer = require('./ImageBuffer');
const _m_AIFeatureReadyResult = require('./AIFeatureReadyResult');
const _m_SoftwareBitmap = require('./SoftwareBitmap');
const _m_AIFeatureReadyState = require('./AIFeatureReadyState');

const IID_IImageForegroundExtractor = WinGuid.parse('231cbec4-9aa1-53ba-8340-2cdba192946e');
const IID_IImageForegroundExtractorStatics = WinGuid.parse('ffe2e9f1-d6ce-53b7-aaa1-cf1ec9039868');
const IID_IClosable = WinGuid.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e');

const _IImageForegroundExtractor = DynWinRtType.registerInterface(
    "IImageForegroundExtractor", IID_IImageForegroundExtractor)
    .addMethod("GetMaskFromSoftwareBitmap", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("GetMaskFromImageBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addOut(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))));

const _IImageForegroundExtractorStatics = DynWinRtType.registerInterface(
    "IImageForegroundExtractorStatics", IID_IImageForegroundExtractorStatics)
    .addMethod("GetReadyState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.AIFeatureReadyState', ['Ready', 'NotReady', 'NotSupportedOnCurrentSystem', 'DisabledByUser'], [0, 1, 2, 3])))
    .addMethod("EnsureReadyAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.AIFeatureReadyResult', WinGuid.parse('936a78a6-c242-5937-9814-e512d4193a6d')), DynWinRtType.f64())))
    .addMethod("CreateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageForegroundExtractor', WinGuid.parse('231cbec4-9aa1-53ba-8340-2cdba192946e')))));

const _IClosable = DynWinRtType.registerInterface(
    "IClosable", IID_IClosable)
    .addMethod("Close", new DynWinRtMethodSig());

class ImageForegroundExtractor {
    static _s_IImageForegroundExtractorStatics;
    static s_IImageForegroundExtractorStatics() { return ImageForegroundExtractor._s_IImageForegroundExtractorStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Imaging.ImageForegroundExtractor').cast(IID_IImageForegroundExtractorStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_IImageForegroundExtractor);
    }

    static getReadyState() {
        return _IImageForegroundExtractorStatics.method(6).invoke(ImageForegroundExtractor.s_IImageForegroundExtractorStatics(), []).toNumber();
    }

    static async ensureReadyAsync() {
        return new _m_AIFeatureReadyResult.AIFeatureReadyResult((await _IImageForegroundExtractorStatics.method(7).invoke(ImageForegroundExtractor.s_IImageForegroundExtractorStatics(), []).toPromise()));
    }

    static async createAsync() {
        return new ImageForegroundExtractor((await _IImageForegroundExtractorStatics.method(8).invoke(ImageForegroundExtractor.s_IImageForegroundExtractorStatics(), []).toPromise()));
    }

    getMaskFromSoftwareBitmap(result) {
        return new _m_SoftwareBitmap.SoftwareBitmap(_IImageForegroundExtractor.method(6).invoke(this._obj, [result._obj || result]));
    }

    getMaskFromImageBuffer(result) {
        return new _m_ImageBuffer.ImageBuffer(_IImageForegroundExtractor.method(7).invoke(this._obj, [result._obj || result]));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IClosable {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IClosable(obj.cast(IID_IClosable));
    }

    close() {
        _IClosable.method(6).invoke(this._obj, []);
    }
}
module.exports = { ImageForegroundExtractor, IClosable };
