// Generated by winrt-meta — do not edit

const ImageDescriptionResultStatus = Object.freeze({ Complete: 0, InProgress: 1, BlockedByPolicy: 2, ImageBlockedByContentModeration: 3, TextInImageBlockedByContentModeration: 4, DescriptionTextBlockedByContentModeration: 5, ImageHasTooMuchText: 6, InternalError: 7 });
module.exports = { ImageDescriptionResultStatus };
