// Generated by winrt-meta — do not edit

const ImageGeneratorResultStatus = Object.freeze({ Success: 0, BlockedByPolicy: 1, TextBlockedByContentModeration: 2, ImageBlockedByContentModeration: 3, UnableToGenerate: 4 });
module.exports = { ImageGeneratorResultStatus };
