// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { ImageFromTextGenerationStyle } = require('./ImageFromTextGenerationStyle');

const IID_IImageFromTextGenerationOptions = WinGuid.parse('904d72dc-7356-5dde-9110-f5971c77425c');

const _IImageFromTextGenerationOptions = DynWinRtType.registerInterface(
    "IImageFromTextGenerationOptions", IID_IImageFromTextGenerationOptions)
    .addMethod("get_Style", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.Imaging.ImageFromTextGenerationStyle', ['Default', 'ColoringBook'], [0, 1])))
    .addMethod("put_Style", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Microsoft.Windows.AI.Imaging.ImageFromTextGenerationStyle', ['Default', 'ColoringBook'], [0, 1])));

class ImageFromTextGenerationOptions {

    constructor(obj) {
        this._obj = obj.cast(IID_IImageFromTextGenerationOptions);
    }

    static create() {
        return new ImageFromTextGenerationOptions(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Microsoft.Windows.AI.Imaging.ImageFromTextGenerationOptions'), []));
    }

    get style() {
        return _IImageFromTextGenerationOptions.method(6).invoke(this._obj, []).toNumber();
    }

    set style(value) {
        _IImageFromTextGenerationOptions.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }
}
module.exports = { ImageFromTextGenerationOptions };
