// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IIterable_IKeyValuePair_String_Object = require('./IIterable_IKeyValuePair_String_Object');
const _m_IIterable_String = require('./IIterable_String');
const _m_IKeyValuePair_String_Object = require('./IKeyValuePair_String_Object');
const _m_IMap_String_Object = require('./IMap_String_Object');
const _m_IReference_Double = require('./IReference_Double');
const _m_IVectorView_String = require('./IVectorView_String');
const _m_IVector_String = require('./IVector_String');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const _m_PhotoOrientation = require('./PhotoOrientation');
const { IID_IStorageItemExtraProperties } = require('./IStorageItemExtraProperties');
const _m_IStorageItemExtraProperties = require('./IStorageItemExtraProperties');

const IID_IImageProperties = WinGuid.parse('523c9424-fcff-4275-afee-ecdb9ab47973');

const _IImageProperties = DynWinRtType.registerInterface(
    "IImageProperties", IID_IImageProperties)
    .addMethod("get_Rating", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Rating", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Keywords", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_DateTaken", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("put_DateTaken", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("get_Width", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Height", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Title", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Title", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Latitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_Longitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_CameraManufacturer", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_CameraManufacturer", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_CameraModel", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_CameraModel", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Orientation", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileProperties.PhotoOrientation', ['Unspecified', 'Normal', 'FlipHorizontal', 'Rotate180', 'FlipVertical', 'Transpose', 'Rotate270', 'Transverse', 'Rotate90'], [0, 1, 2, 3, 4, 5, 6, 7, 8])))
    .addMethod("get_PeopleNames", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])));

function _unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
function _packDateTime(v) {
    const s = DynWinRtStruct.create(_DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}

class ImageProperties {

    constructor(obj) {
        this._obj = obj.cast(IID_IImageProperties);
    }

    get rating() {
        return _IImageProperties.method(6).invoke(this._obj, []).toNumber();
    }

    set rating(value) {
        _IImageProperties.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get keywords() {
        return new _m_IVector_String.IVector_String(_IImageProperties.method(8).invoke(this._obj, []));
    }

    get dateTaken() {
        return _unpackDateTime(_IImageProperties.method(9).invoke(this._obj, []));
    }

    set dateTaken(value) {
        _IImageProperties.method(10).invoke(this._obj, [_packDateTime(value).toValue()]);
    }

    get width() {
        return _IImageProperties.method(11).invoke(this._obj, []).toNumber();
    }

    get height() {
        return _IImageProperties.method(12).invoke(this._obj, []).toNumber();
    }

    get title() {
        return _IImageProperties.method(13).invoke(this._obj, []).toString();
    }

    set title(value) {
        _IImageProperties.method(14).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get latitude() {
        return new _m_IReference_Double.IReference_Double(_IImageProperties.method(15).invoke(this._obj, []));
    }

    get longitude() {
        return new _m_IReference_Double.IReference_Double(_IImageProperties.method(16).invoke(this._obj, []));
    }

    get cameraManufacturer() {
        return _IImageProperties.method(17).invoke(this._obj, []).toString();
    }

    set cameraManufacturer(value) {
        _IImageProperties.method(18).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get cameraModel() {
        return _IImageProperties.method(19).invoke(this._obj, []).toString();
    }

    set cameraModel(value) {
        _IImageProperties.method(20).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get orientation() {
        return _IImageProperties.method(21).invoke(this._obj, []).toNumber();
    }

    get peopleNames() {
        return new _m_IVectorView_String.IVectorView_String(_IImageProperties.method(22).invoke(this._obj, []));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { ImageProperties };
