// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { ImageFromImageGenerationStyle } = require('./ImageFromImageGenerationStyle');

const IID_IImageFromImageGenerationOptions = WinGuid.parse('f8046d25-4c20-5399-a01e-78fb84014888');

const _IImageFromImageGenerationOptions = DynWinRtType.registerInterface(
    "IImageFromImageGenerationOptions", IID_IImageFromImageGenerationOptions)
    .addMethod("get_Style", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.Imaging.ImageFromImageGenerationStyle', ['Default', 'Restyle'], [0, 1])))
    .addMethod("put_Style", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Microsoft.Windows.AI.Imaging.ImageFromImageGenerationStyle', ['Default', 'Restyle'], [0, 1])))
    .addMethod("get_ColorPreservation", new DynWinRtMethodSig().addOut(DynWinRtType.f32()))
    .addMethod("put_ColorPreservation", new DynWinRtMethodSig().addIn(DynWinRtType.f32()));

class ImageFromImageGenerationOptions {

    constructor(obj) {
        this._obj = obj;
    }

    static create() {
        return new ImageFromImageGenerationOptions(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Microsoft.Windows.AI.Imaging.ImageFromImageGenerationOptions'), []));
    }

    get style() {
        return _IImageFromImageGenerationOptions.method(6).invoke(this._obj, []).toNumber();
    }

    set style(value) {
        _IImageFromImageGenerationOptions.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get colorPreservation() {
        return _IImageFromImageGenerationOptions.method(8).invoke(this._obj, []).toF64();
    }

    set colorPreservation(value) {
        _IImageFromImageGenerationOptions.method(9).invoke(this._obj, [DynWinRtValue.f32(value)]);
    }
}
module.exports = { ImageFromImageGenerationOptions };
