// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { AIFeatureReadyResult } = require('./AIFeatureReadyResult');
const { ImageFromImageGenerationOptions } = require('./ImageFromImageGenerationOptions');
const { ImageGenerationOptions } = require('./ImageGenerationOptions');
const { ImageGeneratorResult } = require('./ImageGeneratorResult');
const { ImageBuffer } = require('./ImageBuffer');
const { ImageFromTextGenerationOptions } = require('./ImageFromTextGenerationOptions');
const { AIFeatureReadyState } = require('./AIFeatureReadyState');

const IID_IImageGenerator = WinGuid.parse('8ff81d0b-80d5-5fbb-950c-299f892acf6a');
const IID_IImageGeneratorStatics = WinGuid.parse('38eb37d2-bb6b-5424-a010-58b1d975e6ba');
const IID_IImageGenerator2 = WinGuid.parse('c8f9afdd-f09d-5964-b7fc-8fa49d4f8637');
const IID_IClosable = WinGuid.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e');

const _IImageGenerator = DynWinRtType.registerInterface(
    "IImageGenerator", IID_IImageGenerator)
    .addMethod("GenerateImageFromTextPrompt", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGenerationOptions', WinGuid.parse('cdf68067-aa0e-5416-be24-ea65808c0e39'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGeneratorResult', WinGuid.parse('b4167692-697d-58cf-9e51-76b6f9b4e384'))))
    .addMethod("GenerateImageFromImageBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGenerationOptions', WinGuid.parse('cdf68067-aa0e-5416-be24-ea65808c0e39'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGeneratorResult', WinGuid.parse('b4167692-697d-58cf-9e51-76b6f9b4e384'))))
    .addMethod("GenerateImageFromImageBufferAndMask", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGenerationOptions', WinGuid.parse('cdf68067-aa0e-5416-be24-ea65808c0e39'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGeneratorResult', WinGuid.parse('b4167692-697d-58cf-9e51-76b6f9b4e384'))));

const _IImageGeneratorStatics = DynWinRtType.registerInterface(
    "IImageGeneratorStatics", IID_IImageGeneratorStatics)
    .addMethod("GetReadyState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.AIFeatureReadyState', ['Ready', 'NotReady', 'NotSupportedOnCurrentSystem', 'DisabledByUser'], [0, 1, 2, 3])))
    .addMethod("EnsureReadyAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.AIFeatureReadyResult', WinGuid.parse('936a78a6-c242-5937-9814-e512d4193a6d')), DynWinRtType.f64())))
    .addMethod("CreateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGenerator', WinGuid.parse('8ff81d0b-80d5-5fbb-950c-299f892acf6a')))));

const _IImageGenerator2 = DynWinRtType.registerInterface(
    "IImageGenerator2", IID_IImageGenerator2)
    .addMethod("GenerateImageFromTextPrompt", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGenerationOptions', WinGuid.parse('cdf68067-aa0e-5416-be24-ea65808c0e39'))).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageFromTextGenerationOptions', WinGuid.parse('904d72dc-7356-5dde-9110-f5971c77425c'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGeneratorResult', WinGuid.parse('b4167692-697d-58cf-9e51-76b6f9b4e384'))))
    .addMethod("GenerateImageFromImageBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGenerationOptions', WinGuid.parse('cdf68067-aa0e-5416-be24-ea65808c0e39'))).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageFromImageGenerationOptions', WinGuid.parse('f8046d25-4c20-5399-a01e-78fb84014888'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageGeneratorResult', WinGuid.parse('b4167692-697d-58cf-9e51-76b6f9b4e384'))));

const _IClosable = DynWinRtType.registerInterface(
    "IClosable", IID_IClosable)
    .addMethod("Close", new DynWinRtMethodSig());

class ImageGenerator {
    static _s_IImageGeneratorStatics;
    static s_IImageGeneratorStatics() { return ImageGenerator._s_IImageGeneratorStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Imaging.ImageGenerator').cast(IID_IImageGeneratorStatics); }

    constructor(obj) {
        this._obj = obj;
    }

    static getReadyState() {
        return _IImageGeneratorStatics.method(6).invoke(ImageGenerator.s_IImageGeneratorStatics(), []).toNumber();
    }

    static async ensureReadyAsync() {
        return new AIFeatureReadyResult((await _IImageGeneratorStatics.method(7).invoke(ImageGenerator.s_IImageGeneratorStatics(), []).toPromise()));
    }

    static async createAsync() {
        return new ImageGenerator((await _IImageGeneratorStatics.method(8).invoke(ImageGenerator.s_IImageGeneratorStatics(), []).toPromise()));
    }

    generateImageFromTextPrompt(result, textPrompt) {
        return new ImageGeneratorResult(_IImageGenerator.method(6).invoke(this._obj, [DynWinRtValue.hstring(result), textPrompt._obj || textPrompt]));
    }

    generateImageFromImageBuffer(result, image, textPrompt) {
        return new ImageGeneratorResult(_IImageGenerator.method(7).invoke(this._obj, [result._obj || result, DynWinRtValue.hstring(image), textPrompt._obj || textPrompt]));
    }

    generateImageFromImageBufferAndMask(result, image, mask, textPrompt) {
        return new ImageGeneratorResult(_IImageGenerator.method(8).invoke(this._obj, [result._obj || result, image._obj || image, DynWinRtValue.hstring(mask), textPrompt._obj || textPrompt]));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IImageGenerator2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IImageGenerator2(obj.cast(IID_IImageGenerator2));
    }

    generateImageFromTextPrompt(result, textPrompt, options) {
        return new ImageGeneratorResult(_IImageGenerator2.method(6).invoke(this._obj, [DynWinRtValue.hstring(result), textPrompt._obj || textPrompt, options._obj || options]));
    }

    generateImageFromImageBuffer(result, image, textPrompt, options) {
        return new ImageGeneratorResult(_IImageGenerator2.method(7).invoke(this._obj, [result._obj || result, DynWinRtValue.hstring(image), textPrompt._obj || textPrompt, options._obj || options]));
    }
}

class IClosable {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IClosable(obj.cast(IID_IClosable));
    }

    close() {
        _IClosable.method(6).invoke(this._obj, []);
    }
}
module.exports = { ImageGenerator, IImageGenerator2, IClosable };
