// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_ImageBuffer = require('./ImageBuffer');
const _m_AIFeatureReadyResult = require('./AIFeatureReadyResult');
const _m_ContentFilterOptions = require('./ContentFilterOptions');
const _m_ImageDescriptionKind = require('./ImageDescriptionKind');
const _m_ImageDescriptionResult = require('./ImageDescriptionResult');
const _m_AIFeatureReadyState = require('./AIFeatureReadyState');
const { IID_IClosable } = require('./IClosable');
const _m_IClosable = require('./IClosable');

const IID_IImageDescriptionGenerator = WinGuid.parse('576b989e-9829-5682-91b0-a7110fa7d51e');
const IID_IImageDescriptionGeneratorStatics = WinGuid.parse('5fb50b2a-5700-55a7-b413-6073b4b7f175');

const _IImageDescriptionGenerator = DynWinRtType.registerInterface(
    "IImageDescriptionGenerator", IID_IImageDescriptionGenerator)
    .addMethod("DescribeAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addIn(DynWinRtType.enumType('Microsoft.Windows.AI.Imaging.ImageDescriptionKind', ['BriefDescription', 'DetailedDescription', 'DiagramDescription', 'AccessibleDescription'], [0, 1, 2, 3])).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.ContentFilterOptions', WinGuid.parse('6808be9f-80d2-5136-8a8a-1f5c52c824ad'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageDescriptionResult', WinGuid.parse('a066dd0c-110b-5275-a635-52bed7519a2f')), DynWinRtType.hstring())));

const _IImageDescriptionGeneratorStatics = DynWinRtType.registerInterface(
    "IImageDescriptionGeneratorStatics", IID_IImageDescriptionGeneratorStatics)
    .addMethod("GetReadyState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.AIFeatureReadyState', ['Ready', 'NotReady', 'NotSupportedOnCurrentSystem', 'DisabledByUser'], [0, 1, 2, 3])))
    .addMethod("EnsureReadyAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.AIFeatureReadyResult', WinGuid.parse('936a78a6-c242-5937-9814-e512d4193a6d')), DynWinRtType.f64())))
    .addMethod("CreateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageDescriptionGenerator', WinGuid.parse('576b989e-9829-5682-91b0-a7110fa7d51e')))));

class ImageDescriptionGenerator {
    static _s_IImageDescriptionGeneratorStatics;
    static s_IImageDescriptionGeneratorStatics() { return ImageDescriptionGenerator._s_IImageDescriptionGeneratorStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Imaging.ImageDescriptionGenerator').cast(IID_IImageDescriptionGeneratorStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_IImageDescriptionGenerator);
    }

    static getReadyState() {
        return _IImageDescriptionGeneratorStatics.method(6).invoke(ImageDescriptionGenerator.s_IImageDescriptionGeneratorStatics(), []).toNumber();
    }

    static ensureReadyAsync() {
        const _op = _IImageDescriptionGeneratorStatics.method(7).invoke(ImageDescriptionGenerator.s_IImageDescriptionGeneratorStatics(), []);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_AIFeatureReadyResult.AIFeatureReadyResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    static async createAsync() {
        return new ImageDescriptionGenerator((await _IImageDescriptionGeneratorStatics.method(8).invoke(ImageDescriptionGenerator.s_IImageDescriptionGeneratorStatics(), []).toPromise()));
    }

    describeAsync(operation, image, kind) {
        const _op = _IImageDescriptionGenerator.method(6).invoke(this._obj, [operation._obj || operation, DynWinRtValue.i32(image), kind._obj || kind]);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_ImageDescriptionResult.ImageDescriptionResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { ImageDescriptionGenerator };
