// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_ImageObjectExtractorHint = require('./ImageObjectExtractorHint');
const _m_ImageBuffer = require('./ImageBuffer');
const _m_AIFeatureReadyState = require('./AIFeatureReadyState');
const _m_AIFeatureReadyResult = require('./AIFeatureReadyResult');
const _m_SoftwareBitmap = require('./SoftwareBitmap');
const { IID_IClosable } = require('./IClosable');
const _m_IClosable = require('./IClosable');

const IID_IImageObjectExtractor = WinGuid.parse('2919fdc0-d772-5fd9-a8b7-ffb56010c99c');
const IID_IImageObjectExtractorStatics = WinGuid.parse('38fa261e-2c33-54cb-9e10-98d50685743d');

const _IImageObjectExtractor = DynWinRtType.registerInterface(
    "IImageObjectExtractor", IID_IImageObjectExtractor)
    .addMethod("GetSoftwareBitmapObjectMask", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageObjectExtractorHint', WinGuid.parse('1bd8d67c-8a7a-5fe7-98a5-cbdfeb509452'))).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("GetImageBufferObjectMask", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageObjectExtractorHint', WinGuid.parse('1bd8d67c-8a7a-5fe7-98a5-cbdfeb509452'))).addOut(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))));

const _IImageObjectExtractorStatics = DynWinRtType.registerInterface(
    "IImageObjectExtractorStatics", IID_IImageObjectExtractorStatics)
    .addMethod("CreateWithSoftwareBitmapAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageObjectExtractor', WinGuid.parse('2919fdc0-d772-5fd9-a8b7-ffb56010c99c')))))
    .addMethod("CreateWithImageBufferAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageObjectExtractor', WinGuid.parse('2919fdc0-d772-5fd9-a8b7-ffb56010c99c')))))
    .addMethod("GetReadyState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.AIFeatureReadyState', ['Ready', 'NotReady', 'NotSupportedOnCurrentSystem', 'DisabledByUser'], [0, 1, 2, 3])))
    .addMethod("EnsureReadyAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.AIFeatureReadyResult', WinGuid.parse('936a78a6-c242-5937-9814-e512d4193a6d')), DynWinRtType.f64())));

class ImageObjectExtractor {
    static _s_IImageObjectExtractorStatics;
    static s_IImageObjectExtractorStatics() { return ImageObjectExtractor._s_IImageObjectExtractorStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Imaging.ImageObjectExtractor').cast(IID_IImageObjectExtractorStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_IImageObjectExtractor);
    }

    static async createWithSoftwareBitmapAsync(operation) {
        return new ImageObjectExtractor((await _IImageObjectExtractorStatics.method(6).invoke(ImageObjectExtractor.s_IImageObjectExtractorStatics(), [operation._obj || operation]).toPromise()));
    }

    static async createWithImageBufferAsync(operation) {
        return new ImageObjectExtractor((await _IImageObjectExtractorStatics.method(7).invoke(ImageObjectExtractor.s_IImageObjectExtractorStatics(), [operation._obj || operation]).toPromise()));
    }

    static getReadyState() {
        return _IImageObjectExtractorStatics.method(8).invoke(ImageObjectExtractor.s_IImageObjectExtractorStatics(), []).toNumber();
    }

    static ensureReadyAsync() {
        const _op = _IImageObjectExtractorStatics.method(9).invoke(ImageObjectExtractor.s_IImageObjectExtractorStatics(), []);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_AIFeatureReadyResult.AIFeatureReadyResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    getSoftwareBitmapObjectMask(result) {
        return new _m_SoftwareBitmap.SoftwareBitmap(_IImageObjectExtractor.method(6).invoke(this._obj, [result._obj || result]));
    }

    getImageBufferObjectMask(result) {
        return new _m_ImageBuffer.ImageBuffer(_IImageObjectExtractor.method(7).invoke(this._obj, [result._obj || result]));
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { ImageObjectExtractor };
