// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { ImageBuffer } = require('./ImageBuffer');
const { ContentFilterOptions } = require('./ContentFilterOptions');
const { AIFeatureReadyState } = require('./AIFeatureReadyState');
const { AIFeatureReadyResult } = require('./AIFeatureReadyResult');
const { ImageDescriptionResult } = require('./ImageDescriptionResult');
const { ImageDescriptionKind } = require('./ImageDescriptionKind');

const IID_IImageDescriptionGenerator = WinGuid.parse('576b989e-9829-5682-91b0-a7110fa7d51e');
const IID_IImageDescriptionGeneratorStatics = WinGuid.parse('5fb50b2a-5700-55a7-b413-6073b4b7f175');
const IID_IClosable = WinGuid.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e');

const _IImageDescriptionGenerator = DynWinRtType.registerInterface(
    "IImageDescriptionGenerator", IID_IImageDescriptionGenerator)
    .addMethod("DescribeAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addIn(DynWinRtType.enumType('Microsoft.Windows.AI.Imaging.ImageDescriptionKind', ['BriefDescription', 'DetailedDescription', 'DiagramDescription', 'AccessibleDescription'], [0, 1, 2, 3])).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.ContentFilterOptions', WinGuid.parse('6808be9f-80d2-5136-8a8a-1f5c52c824ad'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageDescriptionResult', WinGuid.parse('a066dd0c-110b-5275-a635-52bed7519a2f')), DynWinRtType.hstring())));

const _IImageDescriptionGeneratorStatics = DynWinRtType.registerInterface(
    "IImageDescriptionGeneratorStatics", IID_IImageDescriptionGeneratorStatics)
    .addMethod("GetReadyState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.AIFeatureReadyState', ['Ready', 'NotReady', 'NotSupportedOnCurrentSystem', 'DisabledByUser'], [0, 1, 2, 3])))
    .addMethod("EnsureReadyAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.AIFeatureReadyResult', WinGuid.parse('936a78a6-c242-5937-9814-e512d4193a6d')), DynWinRtType.f64())))
    .addMethod("CreateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.ImageDescriptionGenerator', WinGuid.parse('576b989e-9829-5682-91b0-a7110fa7d51e')))));

const _IClosable = DynWinRtType.registerInterface(
    "IClosable", IID_IClosable)
    .addMethod("Close", new DynWinRtMethodSig());

class ImageDescriptionGenerator {
    static _s_IImageDescriptionGeneratorStatics;
    static s_IImageDescriptionGeneratorStatics() { return ImageDescriptionGenerator._s_IImageDescriptionGeneratorStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Imaging.ImageDescriptionGenerator').cast(IID_IImageDescriptionGeneratorStatics); }

    constructor(obj) {
        this._obj = obj;
    }

    static getReadyState() {
        return _IImageDescriptionGeneratorStatics.method(6).invoke(ImageDescriptionGenerator.s_IImageDescriptionGeneratorStatics(), []).toNumber();
    }

    static async ensureReadyAsync() {
        return new AIFeatureReadyResult((await _IImageDescriptionGeneratorStatics.method(7).invoke(ImageDescriptionGenerator.s_IImageDescriptionGeneratorStatics(), []).toPromise()));
    }

    static async createAsync() {
        return new ImageDescriptionGenerator((await _IImageDescriptionGeneratorStatics.method(8).invoke(ImageDescriptionGenerator.s_IImageDescriptionGeneratorStatics(), []).toPromise()));
    }

    async describeAsync(operation, image, kind) {
        return new ImageDescriptionResult((await _IImageDescriptionGenerator.method(6).invoke(this._obj, [operation._obj || operation, DynWinRtValue.i32(image), kind._obj || kind]).toPromise()));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IClosable {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IClosable(obj.cast(IID_IClosable));
    }

    close() {
        _IClosable.method(6).invoke(this._obj, []);
    }
}
module.exports = { ImageDescriptionGenerator, IClosable };
