// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_ImageDescriptionResultStatus = require('./ImageDescriptionResultStatus');

const IID_IImageDescriptionResult = WinGuid.parse('a066dd0c-110b-5275-a635-52bed7519a2f');

const _IImageDescriptionResult = DynWinRtType.registerInterface(
    "IImageDescriptionResult", IID_IImageDescriptionResult)
    .addMethod("get_Description", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.Imaging.ImageDescriptionResultStatus', ['Complete', 'InProgress', 'BlockedByPolicy', 'ImageBlockedByContentModeration', 'TextInImageBlockedByContentModeration', 'DescriptionTextBlockedByContentModeration', 'ImageHasTooMuchText', 'InternalError'], [0, 1, 2, 3, 4, 5, 6, 7])));

class ImageDescriptionResult {

    constructor(obj) {
        this._obj = obj.cast(IID_IImageDescriptionResult);
    }

    get description() {
        return _IImageDescriptionResult.method(6).invoke(this._obj, []).toString();
    }

    get status() {
        return _IImageDescriptionResult.method(7).invoke(this._obj, []).toNumber();
    }
}
module.exports = { ImageDescriptionResult };
