// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');

const IID_IMapView_String_Object = DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.object()]).iid();

const _IMapView_String_Object = DynWinRtType.registerInterface(
    "IMapView_String_Object", IID_IMapView_String_Object)
    .addMethod("Lookup", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.object()))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("HasKey", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.boolType()))
    .addMethod("Split", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.object()])).addOut(DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.object()])));

class IMapView_String_Object {
    constructor(obj) {
        this._obj = obj.cast(IID_IMapView_String_Object);
    }

    static from(obj) {
        return new IMapView_String_Object(obj.cast(IID_IMapView_String_Object));
    }

    lookup(key) {
        return _IMapView_String_Object.method(6).invoke(this._obj, [DynWinRtValue.hstring(key)]);
    }

    get size() {
        return _IMapView_String_Object.method(7).invoke(this._obj, []).toNumber();
    }

    hasKey(key) {
        return _IMapView_String_Object.method(8).invoke(this._obj, [DynWinRtValue.hstring(key)]).toBool();
    }

    split() {
        _IMapView_String_Object.method(9).invoke(this._obj, []);
    }
}
module.exports = { IID_IMapView_String_Object, IMapView_String_Object };
