// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IMapView_String_Object = require('./IMapView_String_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');

const IID_IMap_String_IVectorView_TextSegment = DynWinRtType.parameterized(WinGuid.parse('3c2925fe-8519-45c1-aa79-197b6718c1c1'), [DynWinRtType.hstring(), DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.structType('Windows.Data.Text.TextSegment', [DynWinRtType.u32(), DynWinRtType.u32()])])]).iid();

const _IMap_String_IVectorView_TextSegment = DynWinRtType.registerInterface(
    "IMap_String_IVectorView_TextSegment", IID_IMap_String_IVectorView_TextSegment)
    .addMethod("Lookup", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.object()))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("HasKey", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.boolType()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.object()])))
    .addMethod("Insert", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.object()).addOut(DynWinRtType.boolType()))
    .addMethod("Remove", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("Clear", new DynWinRtMethodSig());

class IMap_String_IVectorView_TextSegment {
    constructor(obj) {
        this._obj = obj.cast(IID_IMap_String_IVectorView_TextSegment);
    }

    static from(obj) {
        return new IMap_String_IVectorView_TextSegment(obj.cast(IID_IMap_String_IVectorView_TextSegment));
    }

    /**
     * Create a new IMap from parallel arrays of keys and values.
     * Each key/value must be a DynWinRtValue object.
     */
    static create(keys, values) {
        return new IMap_String_IVectorView_TextSegment(DynWinRtValue.createMap(keys.map(k => k._obj || k), values.map(v => v._obj || v), DynWinRtType.hstring(), DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.structType('Windows.Data.Text.TextSegment', [DynWinRtType.u32(), DynWinRtType.u32()])])));
    }

    lookup(key) {
        return _IMap_String_IVectorView_TextSegment.method(6).invoke(this._obj, [DynWinRtValue.hstring(key)]);
    }

    get size() {
        return _IMap_String_IVectorView_TextSegment.method(7).invoke(this._obj, []).toNumber();
    }

    hasKey(key) {
        return _IMap_String_IVectorView_TextSegment.method(8).invoke(this._obj, [DynWinRtValue.hstring(key)]).toBool();
    }

    getView() {
        return new _m_IMapView_String_Object.IMapView_String_Object(_IMap_String_IVectorView_TextSegment.method(9).invoke(this._obj, []));
    }

    insert(key, value) {
        return _IMap_String_IVectorView_TextSegment.method(10).invoke(this._obj, [DynWinRtValue.hstring(key), value._obj || value]).toBool();
    }

    remove(key) {
        _IMap_String_IVectorView_TextSegment.method(11).invoke(this._obj, [DynWinRtValue.hstring(key)]);
    }

    clear() {
        _IMap_String_IVectorView_TextSegment.method(12).invoke(this._obj, []);
    }
}
module.exports = { IID_IMap_String_IVectorView_TextSegment, IMap_String_IVectorView_TextSegment };
