// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IMemoryBufferReference = WinGuid.parse('fbc4dd29-245b-11e4-af98-689423260cf8');

const _IMemoryBufferReference = DynWinRtType.registerInterface(
    "IMemoryBufferReference", IID_IMemoryBufferReference)
    .addMethod("get_Capacity", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("add_Closed", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('fbc4dd29-245b-11e4-af98-689423260cf8')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_Closed", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])));

function _unpackEventRegistrationToken(v) {
    const s = v.asStruct();
    return { value: s.getI64(0) };
}
const _EventRegistrationToken_Type = DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()]);
function _packEventRegistrationToken(v) {
    const s = DynWinRtStruct.create(_EventRegistrationToken_Type);
    s.setI64(0, v.value);
    return s;
}

class IMemoryBufferReference {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IMemoryBufferReference(obj.cast(IID_IMemoryBufferReference));
    }

    get capacity() {
        return _IMemoryBufferReference.method(6).invoke(this._obj, []).toNumber();
    }

    onClosed(callback) {
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES, callback);
        return _IMemoryBufferReference.method(7).invoke(this._obj, [handler.toValue()]);
    }

    offClosed(token) {
        _IMemoryBufferReference.method(8).invoke(this._obj, [token]);
    }
}
module.exports = { IID_IMemoryBufferReference, IMemoryBufferReference };
