// Generated by winrt-meta — do not edit

const IndexerOption = Object.freeze({ UseIndexerWhenAvailable: 0, OnlyUseIndexer: 1, DoNotUseIndexer: 2, OnlyUseIndexerAndOptimizeForIndexedProperties: 3 });
module.exports = { IndexerOption };
