// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { IID_IBuffer, IBuffer } = require('./IBuffer');

const IID_IOutputStream = WinGuid.parse('905a0fe6-bc53-11df-8c49-001e4fc686da');

const _IOutputStream = DynWinRtType.registerInterface(
    "IOutputStream", IID_IOutputStream)
    .addMethod("WriteAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.u32(), DynWinRtType.u32())))
    .addMethod("FlushAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.boolType())));

class IOutputStream {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IOutputStream(obj.cast(IID_IOutputStream));
    }

    async writeAsync(operation) {
        return (await _IOutputStream.method(6).invoke(this._obj, [operation._obj || operation]).toPromise()).toNumber();
    }

    async flushAsync() {
        return (await _IOutputStream.method(7).invoke(this._obj, []).toPromise()).toBool();
    }
}
module.exports = { IID_IOutputStream, IOutputStream };
