// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_IRandomAccessStreamWithContentType, IRandomAccessStreamWithContentType } = require('./IRandomAccessStreamWithContentType');

const IID_IRandomAccessStreamReference = WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b');

const _IRandomAccessStreamReference = DynWinRtType.registerInterface(
    "IRandomAccessStreamReference", IID_IRandomAccessStreamReference)
    .addMethod("OpenReadAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))));

class IRandomAccessStreamReference {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IRandomAccessStreamReference(obj.cast(IID_IRandomAccessStreamReference));
    }

    async openReadAsync() {
        return new IRandomAccessStreamWithContentType((await _IRandomAccessStreamReference.method(6).invoke(this._obj, []).toPromise()));
    }
}
module.exports = { IID_IRandomAccessStreamReference, IRandomAccessStreamReference };
