// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { IID_IOutputStream, IOutputStream } = require('./IOutputStream');
const { IID_IInputStream, IInputStream } = require('./IInputStream');

const IID_IRandomAccessStream = WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da');

const _IRandomAccessStream = DynWinRtType.registerInterface(
    "IRandomAccessStream", IID_IRandomAccessStream)
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u64()))
    .addMethod("put_Size", new DynWinRtMethodSig().addIn(DynWinRtType.u64()))
    .addMethod("GetInputStreamAt", new DynWinRtMethodSig().addIn(DynWinRtType.u64()).addOut(DynWinRtType.interface(WinGuid.parse('905a0fe2-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("GetOutputStreamAt", new DynWinRtMethodSig().addIn(DynWinRtType.u64()).addOut(DynWinRtType.interface(WinGuid.parse('905a0fe6-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("get_Position", new DynWinRtMethodSig().addOut(DynWinRtType.u64()))
    .addMethod("Seek", new DynWinRtMethodSig().addIn(DynWinRtType.u64()))
    .addMethod("CloneStream", new DynWinRtMethodSig().addOut(DynWinRtType.interface(WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("get_CanRead", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_CanWrite", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));

class IRandomAccessStream {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IRandomAccessStream(obj.cast(IID_IRandomAccessStream));
    }

    get size() {
        return _IRandomAccessStream.method(6).invoke(this._obj, []).toI64();
    }

    set size(value) {
        _IRandomAccessStream.method(7).invoke(this._obj, [DynWinRtValue.i64(value)]);
    }

    getInputStreamAt(stream) {
        return new IInputStream(_IRandomAccessStream.method(8).invoke(this._obj, [DynWinRtValue.i64(stream)]));
    }

    getOutputStreamAt(stream) {
        return new IOutputStream(_IRandomAccessStream.method(9).invoke(this._obj, [DynWinRtValue.i64(stream)]));
    }

    get position() {
        return _IRandomAccessStream.method(10).invoke(this._obj, []).toI64();
    }

    seek(position) {
        _IRandomAccessStream.method(11).invoke(this._obj, [DynWinRtValue.i64(position)]);
    }

    cloneStream() {
        return new IRandomAccessStream(_IRandomAccessStream.method(12).invoke(this._obj, []));
    }

    get canRead() {
        return _IRandomAccessStream.method(13).invoke(this._obj, []).toBool();
    }

    get canWrite() {
        return _IRandomAccessStream.method(14).invoke(this._obj, []).toBool();
    }
}
module.exports = { IID_IRandomAccessStream, IRandomAccessStream };
