// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IReference_Int32 = DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.i32()]).iid();

const _IReference_Int32 = DynWinRtType.registerInterface(
    "IReference_Int32", IID_IReference_Int32)
    .addMethod("get_Value", new DynWinRtMethodSig().addOut(DynWinRtType.i32()));

class IReference_Int32 {
    constructor(obj) {
        this._obj = obj.cast(IID_IReference_Int32);
    }

    static from(obj) {
        return new IReference_Int32(obj.cast(IID_IReference_Int32));
    }

    get value() {
        return _IReference_Int32.method(6).invoke(this._obj, []).toNumber();
    }
}
module.exports = { IID_IReference_Int32, IReference_Int32 };
