// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');

const IID_IReference_DateTime = DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])]).iid();

const _IReference_DateTime = DynWinRtType.registerInterface(
    "IReference_DateTime", IID_IReference_DateTime)
    .addMethod("get_Value", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])));

function _unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
function _packDateTime(v) {
    const s = DynWinRtStruct.create(_DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}

class IReference_DateTime {
    constructor(obj) {
        this._obj = obj.cast(IID_IReference_DateTime);
    }

    static from(obj) {
        return new IReference_DateTime(obj.cast(IID_IReference_DateTime));
    }

    get value() {
        return _unpackDateTime(_IReference_DateTime.method(6).invoke(this._obj, []));
    }
}
module.exports = { IID_IReference_DateTime, IReference_DateTime };
