// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const _m_ThumbnailMode = require('./ThumbnailMode');
const _m_ThumbnailOptions = require('./ThumbnailOptions');
const _m_StorageItemThumbnail = require('./StorageItemThumbnail');
const _m_StorageItemContentProperties = require('./StorageItemContentProperties');

const IID_IStorageItemProperties = WinGuid.parse('86664478-8029-46fe-a789-1c2f3e2ffb5c');

const _IStorageItemProperties = DynWinRtType.registerInterface(
    "IStorageItemProperties", IID_IStorageItemProperties)
    .addMethod("GetThumbnailAsyncOverloadDefaultSizeDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
    .addMethod("GetThumbnailAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
    .addMethod("GetThumbnailAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailOptions', ['None', 'ReturnOnlyIfCached', 'ResizeThumbnail', 'UseCurrentScale'], [0, 1, 2, 4])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
    .addMethod("get_DisplayName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_DisplayType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_FolderRelativeId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Properties", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemContentProperties', WinGuid.parse('05294bad-bc38-48bf-85d7-770e0e2ae0ba'))));

class IStorageItemProperties {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageItemProperties(obj.cast(IID_IStorageItemProperties));
    }

    async getThumbnailAsyncOverloadDefaultSizeDefaultOptions(operation) {
        return new _m_StorageItemThumbnail.StorageItemThumbnail((await _IStorageItemProperties.method(6).invoke(this._obj, [DynWinRtValue.i32(operation)]).toPromise()));
    }

    async getThumbnailAsyncOverloadDefaultOptions(operation, mode) {
        return new _m_StorageItemThumbnail.StorageItemThumbnail((await _IStorageItemProperties.method(7).invoke(this._obj, [DynWinRtValue.i32(operation), DynWinRtValue.i32(mode)]).toPromise()));
    }

    async getThumbnailAsync(operation, mode, requestedSize) {
        return new _m_StorageItemThumbnail.StorageItemThumbnail((await _IStorageItemProperties.method(8).invoke(this._obj, [DynWinRtValue.i32(operation), DynWinRtValue.i32(mode), DynWinRtValue.i32(requestedSize)]).toPromise()));
    }

    get displayName() {
        return _IStorageItemProperties.method(9).invoke(this._obj, []).toString();
    }

    get displayType() {
        return _IStorageItemProperties.method(10).invoke(this._obj, []).toString();
    }

    get folderRelativeId() {
        return _IStorageItemProperties.method(11).invoke(this._obj, []).toString();
    }

    get properties() {
        return new _m_StorageItemContentProperties.StorageItemContentProperties(_IStorageItemProperties.method(12).invoke(this._obj, []));
    }
}
module.exports = { IID_IStorageItemProperties, IStorageItemProperties };
