// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVectorView_IStorageItem } = require('./IVectorView_IStorageItem');
const { IVectorView_StorageFile } = require('./IVectorView_StorageFile');
const { IVectorView_StorageFolder } = require('./IVectorView_StorageFolder');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { StorageFolder } = require('./StorageFolder');
const { CreationCollisionOption } = require('./CreationCollisionOption');
const { IID_IStorageItem, IStorageItem } = require('./IStorageItem');
const { StorageFile } = require('./StorageFile');

const IID_IStorageFolder = WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b');

const _IStorageFolder = DynWinRtType.registerInterface(
    "IStorageFolder", IID_IStorageFolder)
    .addMethod("CreateFileAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CreateFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.CreationCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists', 'OpenIfExists'], [0, 1, 2, 3])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CreateFolderAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
    .addMethod("CreateFolderAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.CreationCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists', 'OpenIfExists'], [0, 1, 2, 3])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
    .addMethod("GetFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("GetFolderAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
    .addMethod("GetItemAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30')))))
    .addMethod("GetFilesAsyncOverloadDefaultOptionsStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
    .addMethod("GetFoldersAsyncOverloadDefaultOptionsStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))]))))
    .addMethod("GetItemsAsyncOverloadDefaultStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))]))));

class IStorageFolder {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFolder(obj.cast(IID_IStorageFolder));
    }

    async createFileAsyncOverloadDefaultOptions(operation) {
        return new StorageFile((await _IStorageFolder.method(6).invoke(this._obj, [DynWinRtValue.hstring(operation)]).toPromise()));
    }

    async createFileAsync(operation, desiredName) {
        return new StorageFile((await _IStorageFolder.method(7).invoke(this._obj, [DynWinRtValue.hstring(operation), DynWinRtValue.i32(desiredName)]).toPromise()));
    }

    async createFolderAsyncOverloadDefaultOptions(operation) {
        return new StorageFolder((await _IStorageFolder.method(8).invoke(this._obj, [DynWinRtValue.hstring(operation)]).toPromise()));
    }

    async createFolderAsync(operation, desiredName) {
        return new StorageFolder((await _IStorageFolder.method(9).invoke(this._obj, [DynWinRtValue.hstring(operation), DynWinRtValue.i32(desiredName)]).toPromise()));
    }

    async getFileAsync(operation) {
        return new StorageFile((await _IStorageFolder.method(10).invoke(this._obj, [DynWinRtValue.hstring(operation)]).toPromise()));
    }

    async getFolderAsync(operation) {
        return new StorageFolder((await _IStorageFolder.method(11).invoke(this._obj, [DynWinRtValue.hstring(operation)]).toPromise()));
    }

    async getItemAsync(operation) {
        return new IStorageItem((await _IStorageFolder.method(12).invoke(this._obj, [DynWinRtValue.hstring(operation)]).toPromise()));
    }

    async getFilesAsyncOverloadDefaultOptionsStartAndCount() {
        return new IVectorView_StorageFile((await _IStorageFolder.method(13).invoke(this._obj, []).toPromise()));
    }

    async getFoldersAsyncOverloadDefaultOptionsStartAndCount() {
        return new IVectorView_StorageFolder((await _IStorageFolder.method(14).invoke(this._obj, []).toPromise()));
    }

    async getItemsAsyncOverloadDefaultStartAndCount() {
        return new IVectorView_IStorageItem((await _IStorageFolder.method(15).invoke(this._obj, []).toPromise()));
    }
}
module.exports = { IID_IStorageFolder, IStorageFolder };
