// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const _m_BasicProperties = require('./BasicProperties');
const _m_NameCollisionOption = require('./NameCollisionOption');
const _m_FileAttributes = require('./FileAttributes');
const _m_StorageItemTypes = require('./StorageItemTypes');
const _m_StorageDeleteOption = require('./StorageDeleteOption');

const IID_IStorageItem = WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30');

const _IStorageItem = DynWinRtType.registerInterface(
    "IStorageItem", IID_IStorageItem)
    .addMethod("RenameAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("RenameAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("DeleteAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()))
    .addMethod("DeleteAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageDeleteOption', ['Default', 'PermanentDelete'], [0, 1])).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("GetBasicPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.BasicProperties', WinGuid.parse('d05d55db-785e-4a66-be02-9beec58aea81')))))
    .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Path", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Attributes", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileAttributes', ['Normal', 'ReadOnly', 'Directory', 'Archive', 'Temporary', 'LocallyIncomplete'], [0, 1, 16, 32, 256, 512])))
    .addMethod("get_DateCreated", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("IsOfType", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageItemTypes', ['None', 'File', 'Folder'], [0, 1, 2])).addOut(DynWinRtType.boolType()));

function _unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
function _packDateTime(v) {
    const s = DynWinRtStruct.create(_DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}

class IStorageItem {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageItem(obj.cast(IID_IStorageItem));
    }

    async renameAsyncOverloadDefaultOptions(operation) {
        return (await _IStorageItem.method(6).invoke(this._obj, [DynWinRtValue.hstring(operation)]).toPromise());
    }

    async renameAsync(operation, desiredName) {
        return (await _IStorageItem.method(7).invoke(this._obj, [DynWinRtValue.hstring(operation), DynWinRtValue.i32(desiredName)]).toPromise());
    }

    async deleteAsyncOverloadDefaultOptions() {
        return (await _IStorageItem.method(8).invoke(this._obj, []).toPromise());
    }

    async deleteAsync(operation) {
        return (await _IStorageItem.method(9).invoke(this._obj, [DynWinRtValue.i32(operation)]).toPromise());
    }

    async getBasicPropertiesAsync() {
        return new _m_BasicProperties.BasicProperties((await _IStorageItem.method(10).invoke(this._obj, []).toPromise()));
    }

    get name() {
        return _IStorageItem.method(11).invoke(this._obj, []).toString();
    }

    get path() {
        return _IStorageItem.method(12).invoke(this._obj, []).toString();
    }

    get attributes() {
        return _IStorageItem.method(13).invoke(this._obj, []).toNumber();
    }

    get dateCreated() {
        return _unpackDateTime(_IStorageItem.method(14).invoke(this._obj, []));
    }

    isOfType(value) {
        return _IStorageItem.method(15).invoke(this._obj, [DynWinRtValue.i32(value)]).toBool();
    }
}
module.exports = { IID_IStorageItem, IStorageItem };
