// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IVectorView_RectInt32 = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.structType('Windows.Graphics.RectInt32', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()])]).iid();

const _IVectorView_RectInt32 = DynWinRtType.registerInterface(
    "IVectorView_RectInt32", IID_IVectorView_RectInt32)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.structType('Windows.Graphics.RectInt32', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()])))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Graphics.RectInt32', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()])).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.structType('Windows.Graphics.RectInt32', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()]))).addOut(DynWinRtType.u32()));

function _unpackRectInt32(v) {
    const s = v.asStruct();
    return { x: s.getI32(0), y: s.getI32(1), width: s.getI32(2), height: s.getI32(3) };
}
const _RectInt32_Type = DynWinRtType.structType('Windows.Graphics.RectInt32', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()]);
function _packRectInt32(v) {
    const s = DynWinRtStruct.create(_RectInt32_Type);
    s.setI32(0, v.x);
    s.setI32(1, v.y);
    s.setI32(2, v.width);
    s.setI32(3, v.height);
    return s;
}

class IVectorView_RectInt32 {
    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_RectInt32);
    }

    static from(obj) {
        return new IVectorView_RectInt32(obj.cast(IID_IVectorView_RectInt32));
    }

    getAt(index) {
        return _unpackRectInt32(_IVectorView_RectInt32.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVectorView_RectInt32.method(7).invoke(this._obj, []).toNumber();
    }

    indexOf(value) {
        return _IVectorView_RectInt32.method(8).invoke(this._obj, [_packRectInt32(value).toValue()]).toBool();
    }

    getMany(startIndex, items) {
        return _IVectorView_RectInt32.method(9).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }
}
module.exports = { IID_IVectorView_RectInt32, IVectorView_RectInt32 };
