// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IVectorView_String = require('./IVectorView_String');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');

const IID_IVector_String = DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()]).iid();

const _IVector_String = DynWinRtType.registerInterface(
    "IVector_String", IID_IVector_String)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.hstring()))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.hstring()))
    .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.hstring()))
    .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("Append", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
    .addMethod("Clear", new DynWinRtMethodSig())
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.hstring())).addOut(DynWinRtType.u32()))
    .addMethod("ReplaceAll", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.hstring())));

class IVector_String {
    constructor(obj) {
        this._obj = obj.cast(IID_IVector_String);
    }

    static from(obj) {
        return new IVector_String(obj.cast(IID_IVector_String));
    }

    /**
     * Create a new IVector from an array of items.
     * Each item must be a DynWinRtValue object.
     */
    static create(items) {
        return new IVector_String(DynWinRtValue.createVector(items.map(i => i._obj || i), DynWinRtType.hstring()));
    }

    getAt(index) {
        return _IVector_String.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]).toString();
    }

    get size() {
        return _IVector_String.method(7).invoke(this._obj, []).toNumber();
    }

    getView() {
        return new _m_IVectorView_String.IVectorView_String(_IVector_String.method(8).invoke(this._obj, []));
    }

    indexOf(value) {
        return _IVector_String.method(9).invoke(this._obj, [DynWinRtValue.hstring(value)]).toBool();
    }

    setAt(index, value) {
        _IVector_String.method(10).invoke(this._obj, [DynWinRtValue.i32(index), DynWinRtValue.hstring(value)]);
    }

    insertAt(index, value) {
        _IVector_String.method(11).invoke(this._obj, [DynWinRtValue.i32(index), DynWinRtValue.hstring(value)]);
    }

    removeAt(index) {
        _IVector_String.method(12).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    append(value) {
        _IVector_String.method(13).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    removeAtEnd() {
        _IVector_String.method(14).invoke(this._obj, []);
    }

    clear() {
        _IVector_String.method(15).invoke(this._obj, []);
    }

    getMany(startIndex, items) {
        return _IVector_String.method(16).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }

    replaceAll(items) {
        _IVector_String.method(17).invoke(this._obj, [items.toValue()]);
    }
}
module.exports = { IID_IVector_String, IVector_String };
