// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVectorView_Object } = require('./IVectorView_Object');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IVector_RectInt32 = DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.structType('Windows.Graphics.RectInt32', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()])]).iid();

const _IVector_RectInt32 = DynWinRtType.registerInterface(
    "IVector_RectInt32", IID_IVector_RectInt32)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.object()))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.object()])))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.object()))
    .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.object()))
    .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("Append", new DynWinRtMethodSig().addIn(DynWinRtType.object()))
    .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
    .addMethod("Clear", new DynWinRtMethodSig())
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.object())).addOut(DynWinRtType.u32()))
    .addMethod("ReplaceAll", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.object())));

class IVector_RectInt32 {
    constructor(obj) {
        this._obj = obj.cast(IID_IVector_RectInt32);
    }

    static from(obj) {
        return new IVector_RectInt32(obj.cast(IID_IVector_RectInt32));
    }

    /**
     * Create a new IVector from an array of items.
     * Each item must be a DynWinRtValue object.
     */
    static create(items) {
        return new IVector_RectInt32(DynWinRtValue.createVector(items.map(i => i._obj || i), DynWinRtType.structType('Windows.Graphics.RectInt32', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()])));
    }

    getAt(index) {
        return _IVector_RectInt32.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    get size() {
        return _IVector_RectInt32.method(7).invoke(this._obj, []).toNumber();
    }

    getView() {
        return new IVectorView_Object(_IVector_RectInt32.method(8).invoke(this._obj, []));
    }

    indexOf(value) {
        return _IVector_RectInt32.method(9).invoke(this._obj, [value._obj || value]).toBool();
    }

    setAt(index, value) {
        _IVector_RectInt32.method(10).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    insertAt(index, value) {
        _IVector_RectInt32.method(11).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    removeAt(index) {
        _IVector_RectInt32.method(12).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    append(value) {
        _IVector_RectInt32.method(13).invoke(this._obj, [value._obj || value]);
    }

    removeAtEnd() {
        _IVector_RectInt32.method(14).invoke(this._obj, []);
    }

    clear() {
        _IVector_RectInt32.method(15).invoke(this._obj, []);
    }

    getMany(startIndex, items) {
        return _IVector_RectInt32.method(16).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }

    replaceAll(items) {
        _IVector_RectInt32.method(17).invoke(this._obj, [items.toValue()]);
    }
}
module.exports = { IID_IVector_RectInt32, IVector_RectInt32 };
