// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVectorView_ExecutionProvider } = require('./IVectorView_ExecutionProvider');
const { ExecutionProvider } = require('./ExecutionProvider');

const IID_IVector_ExecutionProvider = DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))]).iid();

const _IVector_ExecutionProvider = DynWinRtType.registerInterface(
    "IVector_ExecutionProvider", IID_IVector_ExecutionProvider)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))])))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))))
    .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))))
    .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("Append", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))))
    .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
    .addMethod("Clear", new DynWinRtMethodSig())
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff')))).addOut(DynWinRtType.u32()))
    .addMethod("ReplaceAll", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff')))));

class IVector_ExecutionProvider {
    constructor(obj) {
        this._obj = obj.cast(IID_IVector_ExecutionProvider);
    }

    static from(obj) {
        return new IVector_ExecutionProvider(obj.cast(IID_IVector_ExecutionProvider));
    }

    /**
     * Create a new IVector from an array of items.
     * Each item must be a DynWinRtValue object.
     */
    static create(items) {
        return new IVector_ExecutionProvider(DynWinRtValue.createVector(items.map(i => i._obj || i), DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))));
    }

    getAt(index) {
        return new ExecutionProvider(_IVector_ExecutionProvider.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVector_ExecutionProvider.method(7).invoke(this._obj, []).toNumber();
    }

    getView() {
        return new IVectorView_ExecutionProvider(_IVector_ExecutionProvider.method(8).invoke(this._obj, []));
    }

    indexOf(value) {
        return _IVector_ExecutionProvider.method(9).invoke(this._obj, [value._obj || value]).toBool();
    }

    setAt(index, value) {
        _IVector_ExecutionProvider.method(10).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    insertAt(index, value) {
        _IVector_ExecutionProvider.method(11).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    removeAt(index) {
        _IVector_ExecutionProvider.method(12).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    append(value) {
        _IVector_ExecutionProvider.method(13).invoke(this._obj, [value._obj || value]);
    }

    removeAtEnd() {
        _IVector_ExecutionProvider.method(14).invoke(this._obj, []);
    }

    clear() {
        _IVector_ExecutionProvider.method(15).invoke(this._obj, []);
    }

    getMany(startIndex, items) {
        return _IVector_ExecutionProvider.method(16).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }

    replaceAll(items) {
        _IVector_ExecutionProvider.method(17).invoke(this._obj, [items.toValue()]);
    }
}
module.exports = { IID_IVector_ExecutionProvider, IVector_ExecutionProvider };
