// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVectorView_Object } = require('./IVectorView_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');

const IID_IVector_SortEntry = DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])]).iid();

const _IVector_SortEntry = DynWinRtType.registerInterface(
    "IVector_SortEntry", IID_IVector_SortEntry)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.object()))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.object()])))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.object()))
    .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.object()))
    .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("Append", new DynWinRtMethodSig().addIn(DynWinRtType.object()))
    .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
    .addMethod("Clear", new DynWinRtMethodSig())
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.object())).addOut(DynWinRtType.u32()))
    .addMethod("ReplaceAll", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.object())));

class IVector_SortEntry {
    constructor(obj) {
        this._obj = obj.cast(IID_IVector_SortEntry);
    }

    static from(obj) {
        return new IVector_SortEntry(obj.cast(IID_IVector_SortEntry));
    }

    /**
     * Create a new IVector from an array of items.
     * Each item must be a DynWinRtValue object.
     */
    static create(items) {
        return new IVector_SortEntry(DynWinRtValue.createVector(items.map(i => i._obj || i), DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])));
    }

    getAt(index) {
        return _IVector_SortEntry.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    get size() {
        return _IVector_SortEntry.method(7).invoke(this._obj, []).toNumber();
    }

    getView() {
        return new IVectorView_Object(_IVector_SortEntry.method(8).invoke(this._obj, []));
    }

    indexOf(value) {
        return _IVector_SortEntry.method(9).invoke(this._obj, [value._obj || value]).toBool();
    }

    setAt(index, value) {
        _IVector_SortEntry.method(10).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    insertAt(index, value) {
        _IVector_SortEntry.method(11).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    removeAt(index) {
        _IVector_SortEntry.method(12).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    append(value) {
        _IVector_SortEntry.method(13).invoke(this._obj, [value._obj || value]);
    }

    removeAtEnd() {
        _IVector_SortEntry.method(14).invoke(this._obj, []);
    }

    clear() {
        _IVector_SortEntry.method(15).invoke(this._obj, []);
    }

    getMany(startIndex, items) {
        return _IVector_SortEntry.method(16).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }

    replaceAll(items) {
        _IVector_SortEntry.method(17).invoke(this._obj, [items.toValue()]);
    }
}
module.exports = { IID_IVector_SortEntry, IVector_SortEntry };
