// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { EmbeddingVector } = require('./EmbeddingVector');

const IID_IVectorView_EmbeddingVector = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))]).iid();

const _IVectorView_EmbeddingVector = DynWinRtType.registerInterface(
    "IVectorView_EmbeddingVector", IID_IVectorView_EmbeddingVector)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c')))).addOut(DynWinRtType.u32()));

class IVectorView_EmbeddingVector {
    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_EmbeddingVector);
    }

    static from(obj) {
        return new IVectorView_EmbeddingVector(obj.cast(IID_IVectorView_EmbeddingVector));
    }

    getAt(index) {
        return new EmbeddingVector(_IVectorView_EmbeddingVector.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVectorView_EmbeddingVector.method(7).invoke(this._obj, []).toNumber();
    }

    indexOf(value) {
        return _IVectorView_EmbeddingVector.method(8).invoke(this._obj, [value._obj || value]).toBool();
    }

    getMany(startIndex, items) {
        return _IVectorView_EmbeddingVector.method(9).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }
}
module.exports = { IID_IVectorView_EmbeddingVector, IVectorView_EmbeddingVector };
