// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVectorView_ModelCatalogSource } = require('./IVectorView_ModelCatalogSource');
const { ModelCatalogSource } = require('./ModelCatalogSource');

const IID_IVector_ModelCatalogSource = DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))]).iid();

const _IVector_ModelCatalogSource = DynWinRtType.registerInterface(
    "IVector_ModelCatalogSource", IID_IVector_ModelCatalogSource)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))])))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))))
    .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))))
    .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("Append", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))))
    .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
    .addMethod("Clear", new DynWinRtMethodSig())
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9')))).addOut(DynWinRtType.u32()))
    .addMethod("ReplaceAll", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9')))));

class IVector_ModelCatalogSource {
    constructor(obj) {
        this._obj = obj.cast(IID_IVector_ModelCatalogSource);
    }

    static from(obj) {
        return new IVector_ModelCatalogSource(obj.cast(IID_IVector_ModelCatalogSource));
    }

    /**
     * Create a new IVector from an array of items.
     * Each item must be a DynWinRtValue object.
     */
    static create(items) {
        return new IVector_ModelCatalogSource(DynWinRtValue.createVector(items.map(i => i._obj || i), DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))));
    }

    getAt(index) {
        return new ModelCatalogSource(_IVector_ModelCatalogSource.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVector_ModelCatalogSource.method(7).invoke(this._obj, []).toNumber();
    }

    getView() {
        return new IVectorView_ModelCatalogSource(_IVector_ModelCatalogSource.method(8).invoke(this._obj, []));
    }

    indexOf(value) {
        return _IVector_ModelCatalogSource.method(9).invoke(this._obj, [value._obj || value]).toBool();
    }

    setAt(index, value) {
        _IVector_ModelCatalogSource.method(10).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    insertAt(index, value) {
        _IVector_ModelCatalogSource.method(11).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    removeAt(index) {
        _IVector_ModelCatalogSource.method(12).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    append(value) {
        _IVector_ModelCatalogSource.method(13).invoke(this._obj, [value._obj || value]);
    }

    removeAtEnd() {
        _IVector_ModelCatalogSource.method(14).invoke(this._obj, []);
    }

    clear() {
        _IVector_ModelCatalogSource.method(15).invoke(this._obj, []);
    }

    getMany(startIndex, items) {
        return _IVector_ModelCatalogSource.method(16).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }

    replaceAll(items) {
        _IVector_ModelCatalogSource.method(17).invoke(this._obj, [items.toValue()]);
    }
}
module.exports = { IID_IVector_ModelCatalogSource, IVector_ModelCatalogSource };
