// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_IStorageItem } = require('./IStorageItem');
const _m_IStorageItem = require('./IStorageItem');

const IID_IVectorView_IStorageItem = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))]).iid();

const _IVectorView_IStorageItem = DynWinRtType.registerInterface(
    "IVectorView_IStorageItem", IID_IVectorView_IStorageItem)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30')))).addOut(DynWinRtType.u32()));

class IVectorView_IStorageItem {
    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_IStorageItem);
    }

    static from(obj) {
        return new IVectorView_IStorageItem(obj.cast(IID_IVectorView_IStorageItem));
    }

    getAt(index) {
        return new _m_IStorageItem.IStorageItem(_IVectorView_IStorageItem.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVectorView_IStorageItem.method(7).invoke(this._obj, []).toNumber();
    }

    indexOf(value) {
        return _IVectorView_IStorageItem.method(8).invoke(this._obj, [value._obj || value]).toBool();
    }

    getMany(startIndex, items) {
        return _IVectorView_IStorageItem.method(9).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }
}
module.exports = { IID_IVectorView_IStorageItem, IVectorView_IStorageItem };
