// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');

const IID_IVectorView_Object = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.object()]).iid();

const _IVectorView_Object = DynWinRtType.registerInterface(
    "IVectorView_Object", IID_IVectorView_Object)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.object()))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.object())).addOut(DynWinRtType.u32()));

class IVectorView_Object {
    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_Object);
    }

    static from(obj) {
        return new IVectorView_Object(obj.cast(IID_IVectorView_Object));
    }

    getAt(index) {
        return _IVectorView_Object.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    get size() {
        return _IVectorView_Object.method(7).invoke(this._obj, []).toNumber();
    }

    indexOf(value) {
        return _IVectorView_Object.method(8).invoke(this._obj, [value._obj || value]).toBool();
    }

    getMany(startIndex, items) {
        return _IVectorView_Object.method(9).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }
}
module.exports = { IID_IVectorView_Object, IVectorView_Object };
