// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_ExecutionProvider = require('./ExecutionProvider');

const IID_IVectorView_ExecutionProvider = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))]).iid();

const _IVectorView_ExecutionProvider = DynWinRtType.registerInterface(
    "IVectorView_ExecutionProvider", IID_IVectorView_ExecutionProvider)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ExecutionProvider', WinGuid.parse('98356468-cf23-504f-b29c-9347781925ff')))).addOut(DynWinRtType.u32()));

class IVectorView_ExecutionProvider {
    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_ExecutionProvider);
    }

    static from(obj) {
        return new IVectorView_ExecutionProvider(obj.cast(IID_IVectorView_ExecutionProvider));
    }

    getAt(index) {
        return new _m_ExecutionProvider.ExecutionProvider(_IVectorView_ExecutionProvider.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVectorView_ExecutionProvider.method(7).invoke(this._obj, []).toNumber();
    }

    indexOf(value) {
        return _IVectorView_ExecutionProvider.method(8).invoke(this._obj, [value._obj || value]).toBool();
    }

    getMany(startIndex, items) {
        return _IVectorView_ExecutionProvider.method(9).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }
}
module.exports = { IID_IVectorView_ExecutionProvider, IVectorView_ExecutionProvider };
