// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');

const IID_IVectorView_SortEntry = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])]).iid();

const _IVectorView_SortEntry = DynWinRtType.registerInterface(
    "IVectorView_SortEntry", IID_IVectorView_SortEntry)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()]))).addOut(DynWinRtType.u32()));

function _unpackSortEntry(v) {
    const s = v.asStruct();
    return { propertyName: s.getHstring(0), ascendingOrder: s.getU8(1) !== 0 };
}
const _SortEntry_Type = DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()]);
function _packSortEntry(v) {
    const s = DynWinRtStruct.create(_SortEntry_Type);
    s.setHstring(0, v.propertyName);
    s.setU8(1, v.ascendingOrder ? 1 : 0);
    return s;
}

class IVectorView_SortEntry {
    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_SortEntry);
    }

    static from(obj) {
        return new IVectorView_SortEntry(obj.cast(IID_IVectorView_SortEntry));
    }

    getAt(index) {
        return _unpackSortEntry(_IVectorView_SortEntry.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVectorView_SortEntry.method(7).invoke(this._obj, []).toNumber();
    }

    indexOf(value) {
        return _IVectorView_SortEntry.method(8).invoke(this._obj, [_packSortEntry(value).toValue()]).toBool();
    }

    getMany(startIndex, items) {
        return _IVectorView_SortEntry.method(9).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }
}
module.exports = { IID_IVectorView_SortEntry, IVectorView_SortEntry };
