// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_ModelCatalogSource = require('./ModelCatalogSource');

const IID_IVectorView_ModelCatalogSource = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))]).iid();

const _IVectorView_ModelCatalogSource = DynWinRtType.registerInterface(
    "IVectorView_ModelCatalogSource", IID_IVectorView_ModelCatalogSource)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.ModelCatalogSource', WinGuid.parse('3117952c-8dc3-54c9-94fa-bf6f38cbfce9')))).addOut(DynWinRtType.u32()));

class IVectorView_ModelCatalogSource {
    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_ModelCatalogSource);
    }

    static from(obj) {
        return new IVectorView_ModelCatalogSource(obj.cast(IID_IVectorView_ModelCatalogSource));
    }

    getAt(index) {
        return new _m_ModelCatalogSource.ModelCatalogSource(_IVectorView_ModelCatalogSource.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVectorView_ModelCatalogSource.method(7).invoke(this._obj, []).toNumber();
    }

    indexOf(value) {
        return _IVectorView_ModelCatalogSource.method(8).invoke(this._obj, [value._obj || value]).toBool();
    }

    getMany(startIndex, items) {
        return _IVectorView_ModelCatalogSource.method(9).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }
}
module.exports = { IID_IVectorView_ModelCatalogSource, IVectorView_ModelCatalogSource };
