// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_CatalogModelInfo = require('./CatalogModelInfo');

const IID_IVectorView_CatalogModelInfo = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))]).iid();

const _IVectorView_CatalogModelInfo = DynWinRtType.registerInterface(
    "IVectorView_CatalogModelInfo", IID_IVectorView_CatalogModelInfo)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4')))).addOut(DynWinRtType.u32()));

class IVectorView_CatalogModelInfo {
    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_CatalogModelInfo);
    }

    static from(obj) {
        return new IVectorView_CatalogModelInfo(obj.cast(IID_IVectorView_CatalogModelInfo));
    }

    getAt(index) {
        return new _m_CatalogModelInfo.CatalogModelInfo(_IVectorView_CatalogModelInfo.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVectorView_CatalogModelInfo.method(7).invoke(this._obj, []).toNumber();
    }

    indexOf(value) {
        return _IVectorView_CatalogModelInfo.method(8).invoke(this._obj, [value._obj || value]).toBool();
    }

    getMany(startIndex, items) {
        return _IVectorView_CatalogModelInfo.method(9).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }
}
module.exports = { IID_IVectorView_CatalogModelInfo, IVectorView_CatalogModelInfo };
