// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVectorView_PointInt32 } = require('./IVectorView_PointInt32');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IVector_PointInt32 = DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()])]).iid();

const _IVector_PointInt32 = DynWinRtType.registerInterface(
    "IVector_PointInt32", IID_IVector_PointInt32)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()])))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()])])))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()])).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()])))
    .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()])))
    .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("Append", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()])))
    .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
    .addMethod("Clear", new DynWinRtMethodSig())
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()]))).addOut(DynWinRtType.u32()))
    .addMethod("ReplaceAll", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()]))));

function _unpackPointInt32(v) {
    const s = v.asStruct();
    return { x: s.getI32(0), y: s.getI32(1) };
}
const _PointInt32_Type = DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()]);
function _packPointInt32(v) {
    const s = DynWinRtStruct.create(_PointInt32_Type);
    s.setI32(0, v.x);
    s.setI32(1, v.y);
    return s;
}

class IVector_PointInt32 {
    constructor(obj) {
        this._obj = obj.cast(IID_IVector_PointInt32);
    }

    static from(obj) {
        return new IVector_PointInt32(obj.cast(IID_IVector_PointInt32));
    }

    /**
     * Create a new IVector from an array of items.
     * Each item must be a DynWinRtValue object.
     */
    static create(items) {
        return new IVector_PointInt32(DynWinRtValue.createVector(items.map(i => i._obj || i), DynWinRtType.structType('Windows.Graphics.PointInt32', [DynWinRtType.i32(), DynWinRtType.i32()])));
    }

    getAt(index) {
        return _unpackPointInt32(_IVector_PointInt32.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVector_PointInt32.method(7).invoke(this._obj, []).toNumber();
    }

    getView() {
        return new IVectorView_PointInt32(_IVector_PointInt32.method(8).invoke(this._obj, []));
    }

    indexOf(value) {
        return _IVector_PointInt32.method(9).invoke(this._obj, [_packPointInt32(value).toValue()]).toBool();
    }

    setAt(index, value) {
        _IVector_PointInt32.method(10).invoke(this._obj, [DynWinRtValue.i32(index), _packPointInt32(value).toValue()]);
    }

    insertAt(index, value) {
        _IVector_PointInt32.method(11).invoke(this._obj, [DynWinRtValue.i32(index), _packPointInt32(value).toValue()]);
    }

    removeAt(index) {
        _IVector_PointInt32.method(12).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    append(value) {
        _IVector_PointInt32.method(13).invoke(this._obj, [_packPointInt32(value).toValue()]);
    }

    removeAtEnd() {
        _IVector_PointInt32.method(14).invoke(this._obj, []);
    }

    clear() {
        _IVector_PointInt32.method(15).invoke(this._obj, []);
    }

    getMany(startIndex, items) {
        return _IVector_PointInt32.method(16).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }

    replaceAll(items) {
        _IVector_PointInt32.method(17).invoke(this._obj, [items.toValue()]);
    }
}
module.exports = { IID_IVector_PointInt32, IVector_PointInt32 };
