// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { ConversationItem } = require('./ConversationItem');

const IID_IVectorView_ConversationItem = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.ConversationItem', WinGuid.parse('957b0b85-4d7e-5788-baae-af7cf256bb8e'))]).iid();

const _IVectorView_ConversationItem = DynWinRtType.registerInterface(
    "IVectorView_ConversationItem", IID_IVectorView_ConversationItem)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.ConversationItem', WinGuid.parse('957b0b85-4d7e-5788-baae-af7cf256bb8e'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.ConversationItem', WinGuid.parse('957b0b85-4d7e-5788-baae-af7cf256bb8e'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.ConversationItem', WinGuid.parse('957b0b85-4d7e-5788-baae-af7cf256bb8e')))).addOut(DynWinRtType.u32()));

class IVectorView_ConversationItem {
    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_ConversationItem);
    }

    static from(obj) {
        return new IVectorView_ConversationItem(obj.cast(IID_IVectorView_ConversationItem));
    }

    getAt(index) {
        return new ConversationItem(_IVectorView_ConversationItem.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVectorView_ConversationItem.method(7).invoke(this._obj, []).toNumber();
    }

    indexOf(value) {
        return _IVectorView_ConversationItem.method(8).invoke(this._obj, [value._obj || value]).toBool();
    }

    getMany(startIndex, items) {
        return _IVectorView_ConversationItem.method(9).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }
}
module.exports = { IID_IVectorView_ConversationItem, IVectorView_ConversationItem };
