// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVectorView_CatalogModelInfo } = require('./IVectorView_CatalogModelInfo');
const { CatalogModelInfo } = require('./CatalogModelInfo');

const IID_IVector_CatalogModelInfo = DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))]).iid();

const _IVector_CatalogModelInfo = DynWinRtType.registerInterface(
    "IVector_CatalogModelInfo", IID_IVector_CatalogModelInfo)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))])))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))))
    .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))))
    .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("Append", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))))
    .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
    .addMethod("Clear", new DynWinRtMethodSig())
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4')))).addOut(DynWinRtType.u32()))
    .addMethod("ReplaceAll", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4')))));

class IVector_CatalogModelInfo {
    constructor(obj) {
        this._obj = obj.cast(IID_IVector_CatalogModelInfo);
    }

    static from(obj) {
        return new IVector_CatalogModelInfo(obj.cast(IID_IVector_CatalogModelInfo));
    }

    /**
     * Create a new IVector from an array of items.
     * Each item must be a DynWinRtValue object.
     */
    static create(items) {
        return new IVector_CatalogModelInfo(DynWinRtValue.createVector(items.map(i => i._obj || i), DynWinRtType.runtimeClass('Microsoft.Windows.AI.MachineLearning.CatalogModelInfo', WinGuid.parse('62057faa-3def-509f-9ed2-aef1e0de21a4'))));
    }

    getAt(index) {
        return new CatalogModelInfo(_IVector_CatalogModelInfo.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]));
    }

    get size() {
        return _IVector_CatalogModelInfo.method(7).invoke(this._obj, []).toNumber();
    }

    getView() {
        return new IVectorView_CatalogModelInfo(_IVector_CatalogModelInfo.method(8).invoke(this._obj, []));
    }

    indexOf(value) {
        return _IVector_CatalogModelInfo.method(9).invoke(this._obj, [value._obj || value]).toBool();
    }

    setAt(index, value) {
        _IVector_CatalogModelInfo.method(10).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    insertAt(index, value) {
        _IVector_CatalogModelInfo.method(11).invoke(this._obj, [DynWinRtValue.i32(index), value._obj || value]);
    }

    removeAt(index) {
        _IVector_CatalogModelInfo.method(12).invoke(this._obj, [DynWinRtValue.i32(index)]);
    }

    append(value) {
        _IVector_CatalogModelInfo.method(13).invoke(this._obj, [value._obj || value]);
    }

    removeAtEnd() {
        _IVector_CatalogModelInfo.method(14).invoke(this._obj, []);
    }

    clear() {
        _IVector_CatalogModelInfo.method(15).invoke(this._obj, []);
    }

    getMany(startIndex, items) {
        return _IVector_CatalogModelInfo.method(16).invoke(this._obj, [DynWinRtValue.i32(startIndex), items.toValue()]).toNumber();
    }

    replaceAll(items) {
        _IVector_CatalogModelInfo.method(17).invoke(this._obj, [items.toValue()]);
    }
}
module.exports = { IID_IVector_CatalogModelInfo, IVector_CatalogModelInfo };
