// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_LanguageModelResponseStatus = require('./LanguageModelResponseStatus');

const IID_ILanguageModelResponseResult = WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e');

const _ILanguageModelResponseResult = DynWinRtType.registerInterface(
    "ILanguageModelResponseResult", IID_ILanguageModelResponseResult)
    .addMethod("get_Text", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.Text.LanguageModelResponseStatus', ['Complete', 'InProgress', 'BlockedByPolicy', 'PromptLargerThanContext', 'PromptBlockedByContentModeration', 'ResponseBlockedByContentModeration', 'Error'], [0, 1, 2, 3, 4, 5, 6])))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.HResult', [DynWinRtType.i32()])));

class LanguageModelResponseResult {

    constructor(obj) {
        this._obj = obj.cast(IID_ILanguageModelResponseResult);
    }

    get text() {
        return _ILanguageModelResponseResult.method(6).invoke(this._obj, []).toString();
    }

    get status() {
        return _ILanguageModelResponseResult.method(7).invoke(this._obj, []).toNumber();
    }

    get extendedError() {
        return _ILanguageModelResponseResult.method(8).invoke(this._obj, []).toNumber();
    }
}
module.exports = { LanguageModelResponseResult };
