// Generated by winrt-meta — do not edit

const LanguageModelResponseStatus = Object.freeze({ Complete: 0, InProgress: 1, BlockedByPolicy: 2, PromptLargerThanContext: 3, PromptBlockedByContentModeration: 4, ResponseBlockedByContentModeration: 5, Error: 6 });
module.exports = { LanguageModelResponseStatus };
