// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_IClosable } = require('./IClosable');
const _m_IClosable = require('./IClosable');

const IID_ILanguageModelContext = WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e');

const _ILanguageModelContext = DynWinRtType.registerInterface(
    "ILanguageModelContext", IID_ILanguageModelContext);

class LanguageModelContext {

    constructor(obj) {
        this._obj = obj.cast(IID_ILanguageModelContext);
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { LanguageModelContext };
