// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const { LowRankAdaptation } = require('./LowRankAdaptation');
const { LanguageModelOptions } = require('./LanguageModelOptions');
const { ContentFilterOptions } = require('./ContentFilterOptions');

const IID_ILanguageModelOptionsExperimental = WinGuid.parse('a6a10830-f03d-5ea9-9bec-65d2601ac8c9');
const IID_ILanguageModelOptionsExperimentalStatics = WinGuid.parse('78c940f7-7ea2-5007-8658-4459fe1dd9e5');

const _ILanguageModelOptionsExperimental = DynWinRtType.registerInterface(
    "ILanguageModelOptionsExperimental", IID_ILanguageModelOptionsExperimental)
    .addMethod("get_Temperature", new DynWinRtMethodSig().addOut(DynWinRtType.f32()))
    .addMethod("put_Temperature", new DynWinRtMethodSig().addIn(DynWinRtType.f32()))
    .addMethod("get_TopP", new DynWinRtMethodSig().addOut(DynWinRtType.f32()))
    .addMethod("put_TopP", new DynWinRtMethodSig().addIn(DynWinRtType.f32()))
    .addMethod("get_TopK", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_TopK", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_ContentFilterOptions", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.ContentFilterOptions', WinGuid.parse('6808be9f-80d2-5136-8a8a-1f5c52c824ad'))))
    .addMethod("put_ContentFilterOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.ContentFilterOptions', WinGuid.parse('6808be9f-80d2-5136-8a8a-1f5c52c824ad'))))
    .addMethod("get_LoraAdapter", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LowRankAdaptation', WinGuid.parse('904dd39a-91d5-5ffb-9dc2-137461e28d63'))))
    .addMethod("put_LoraAdapter", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LowRankAdaptation', WinGuid.parse('904dd39a-91d5-5ffb-9dc2-137461e28d63'))));

const _ILanguageModelOptionsExperimentalStatics = DynWinRtType.registerInterface(
    "ILanguageModelOptionsExperimentalStatics", IID_ILanguageModelOptionsExperimentalStatics)
    .addMethod("GetForLanguageModelOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelOptions', WinGuid.parse('7f380003-5a09-5f1f-afb0-aa483e3670cc'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LanguageModelOptionsExperimental', WinGuid.parse('a6a10830-f03d-5ea9-9bec-65d2601ac8c9'))));

class LanguageModelOptionsExperimental {
    static _s_ILanguageModelOptionsExperimentalStatics;
    static s_ILanguageModelOptionsExperimentalStatics() { return LanguageModelOptionsExperimental._s_ILanguageModelOptionsExperimentalStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Text.Experimental.LanguageModelOptionsExperimental').cast(IID_ILanguageModelOptionsExperimentalStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_ILanguageModelOptionsExperimental);
    }

    static create() {
        return new LanguageModelOptionsExperimental(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Microsoft.Windows.AI.Text.Experimental.LanguageModelOptionsExperimental'), []));
    }

    static getForLanguageModelOptions(result) {
        return new LanguageModelOptionsExperimental(_ILanguageModelOptionsExperimentalStatics.method(6).invoke(LanguageModelOptionsExperimental.s_ILanguageModelOptionsExperimentalStatics(), [result._obj || result]));
    }

    get temperature() {
        return _ILanguageModelOptionsExperimental.method(6).invoke(this._obj, []).toF64();
    }

    set temperature(value) {
        _ILanguageModelOptionsExperimental.method(7).invoke(this._obj, [DynWinRtValue.f32(value)]);
    }

    get topP() {
        return _ILanguageModelOptionsExperimental.method(8).invoke(this._obj, []).toF64();
    }

    set topP(value) {
        _ILanguageModelOptionsExperimental.method(9).invoke(this._obj, [DynWinRtValue.f32(value)]);
    }

    get topK() {
        return _ILanguageModelOptionsExperimental.method(10).invoke(this._obj, []).toNumber();
    }

    set topK(value) {
        _ILanguageModelOptionsExperimental.method(11).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get contentFilterOptions() {
        return new ContentFilterOptions(_ILanguageModelOptionsExperimental.method(12).invoke(this._obj, []));
    }

    set contentFilterOptions(value) {
        _ILanguageModelOptionsExperimental.method(13).invoke(this._obj, [value._obj || value]);
    }

    get loraAdapter() {
        return new LowRankAdaptation(_ILanguageModelOptionsExperimental.method(14).invoke(this._obj, []));
    }

    set loraAdapter(value) {
        _ILanguageModelOptionsExperimental.method(15).invoke(this._obj, [value._obj || value]);
    }
}
module.exports = { LanguageModelOptionsExperimental };
