// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IIterable_EmbeddingVector } = require('./IIterable_EmbeddingVector');
const { LowRankAdaptation } = require('./LowRankAdaptation');
const { LanguageModelContext } = require('./LanguageModelContext');
const { LanguageModelOptionsExperimental } = require('./LanguageModelOptionsExperimental');
const { EmbeddingVector } = require('./EmbeddingVector');
const { LanguageModelResponseResult } = require('./LanguageModelResponseResult');
const { IID_IBuffer, IBuffer } = require('./IBuffer');
const { LanguageModel } = require('./LanguageModel');

const IID_ILanguageModelExperimental = WinGuid.parse('debb7cdd-c981-5d84-9f8d-e42b57c3cefb');
const IID_ILanguageModelExperimentalFactory = WinGuid.parse('6a3b389b-7aa8-549c-8351-c1b8eaf9ef3f');
const IID_IClosable = WinGuid.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e');

const _ILanguageModelExperimental = DynWinRtType.registerInterface(
    "ILanguageModelExperimental", IID_ILanguageModelExperimental)
    .addMethod("LoadAdapter", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LowRankAdaptation', WinGuid.parse('904dd39a-91d5-5ffb-9dc2-137461e28d63'))))
    .addMethod("LoadAdapter2", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LowRankAdaptation', WinGuid.parse('904dd39a-91d5-5ffb-9dc2-137461e28d63'))))
    .addMethod("GenerateResponseAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LanguageModelOptionsExperimental', WinGuid.parse('a6a10830-f03d-5ea9-9bec-65d2601ac8c9'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())))
    .addMethod("GenerateResponseAsync2", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelContext', WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LanguageModelOptionsExperimental', WinGuid.parse('a6a10830-f03d-5ea9-9bec-65d2601ac8c9'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())))
    .addMethod("GenerateResponseFromEmbeddingsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))])).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LanguageModelOptionsExperimental', WinGuid.parse('a6a10830-f03d-5ea9-9bec-65d2601ac8c9'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())))
    .addMethod("GenerateResponseFromEmbeddingsAsync2", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelContext', WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e'))).addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))])).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LanguageModelOptionsExperimental', WinGuid.parse('a6a10830-f03d-5ea9-9bec-65d2601ac8c9'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())));

const _ILanguageModelExperimentalFactory = DynWinRtType.registerInterface(
    "ILanguageModelExperimentalFactory", IID_ILanguageModelExperimentalFactory)
    .addMethod("CreateInstance", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModel', WinGuid.parse('6331c629-8c86-5bfe-8c4e-9ca5573cc14b'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.Experimental.LanguageModelExperimental', WinGuid.parse('debb7cdd-c981-5d84-9f8d-e42b57c3cefb'))));

const _IClosable = DynWinRtType.registerInterface(
    "IClosable", IID_IClosable)
    .addMethod("Close", new DynWinRtMethodSig());

class LanguageModelExperimental {
    static _f_ILanguageModelExperimentalFactory;
    static f_ILanguageModelExperimentalFactory() { return LanguageModelExperimental._f_ILanguageModelExperimentalFactory ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Text.Experimental.LanguageModelExperimental').cast(IID_ILanguageModelExperimentalFactory); }

    constructor(obj) {
        this._obj = obj;
    }

    static createInstance(value) {
        return new LanguageModelExperimental(_ILanguageModelExperimentalFactory.method(6).invoke(LanguageModelExperimental.f_ILanguageModelExperimentalFactory(), [value._obj || value]));
    }

    loadAdapter(result) {
        return new LowRankAdaptation(_ILanguageModelExperimental.method(6).invoke(this._obj, [DynWinRtValue.hstring(result)]));
    }

    loadAdapter2(result) {
        return new LowRankAdaptation(_ILanguageModelExperimental.method(7).invoke(this._obj, [result._obj || result]));
    }

    async generateResponseAsync(operation, prompt) {
        return new LanguageModelResponseResult((await _ILanguageModelExperimental.method(8).invoke(this._obj, [DynWinRtValue.hstring(operation), prompt._obj || prompt]).toPromise()));
    }

    async generateResponseAsync2(operation, context, prompt) {
        return new LanguageModelResponseResult((await _ILanguageModelExperimental.method(9).invoke(this._obj, [operation._obj || operation, DynWinRtValue.hstring(context), prompt._obj || prompt]).toPromise()));
    }

    async generateResponseFromEmbeddingsAsync(operation, promptEmbedding) {
        return new LanguageModelResponseResult((await _ILanguageModelExperimental.method(10).invoke(this._obj, [operation._obj || operation, promptEmbedding._obj || promptEmbedding]).toPromise()));
    }

    async generateResponseFromEmbeddingsAsync2(operation, context, promptEmbedding) {
        return new LanguageModelResponseResult((await _ILanguageModelExperimental.method(11).invoke(this._obj, [operation._obj || operation, context._obj || context, promptEmbedding._obj || promptEmbedding]).toPromise()));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IClosable {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IClosable(obj.cast(IID_IClosable));
    }

    close() {
        _IClosable.method(6).invoke(this._obj, []);
    }
}
module.exports = { LanguageModelExperimental, IClosable };
