// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');

const IID_ILanguageModelContext = WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e');
const IID_IClosable = WinGuid.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e');

const _ILanguageModelContext = DynWinRtType.registerInterface(
    "ILanguageModelContext", IID_ILanguageModelContext);

const _IClosable = DynWinRtType.registerInterface(
    "IClosable", IID_IClosable)
    .addMethod("Close", new DynWinRtMethodSig());

class LanguageModelContext {

    constructor(obj) {
        this._obj = obj;
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IClosable {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IClosable(obj.cast(IID_IClosable));
    }

    close() {
        _IClosable.method(6).invoke(this._obj, []);
    }
}
module.exports = { LanguageModelContext, IClosable };
