// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IIterable_EmbeddingVector = require('./IIterable_EmbeddingVector');
const _m_LanguageModelContext = require('./LanguageModelContext');
const _m_LanguageModelEmbeddingVectorResult = require('./LanguageModelEmbeddingVectorResult');
const _m_LanguageModelOptions = require('./LanguageModelOptions');
const _m_LanguageModelResponseResult = require('./LanguageModelResponseResult');
const _m_AIFeatureReadyState = require('./AIFeatureReadyState');
const _m_EmbeddingVector = require('./EmbeddingVector');
const _m_AIFeatureReadyResult = require('./AIFeatureReadyResult');
const _m_ContentFilterOptions = require('./ContentFilterOptions');
const { IID_IClosable } = require('./IClosable');
const _m_IClosable = require('./IClosable');

const IID_ILanguageModel = WinGuid.parse('6331c629-8c86-5bfe-8c4e-9ca5573cc14b');
const IID_ILanguageModelStatics = WinGuid.parse('8f18f9af-6095-553b-8d9d-6bcc98026546');
const IID_ILanguageModel2 = WinGuid.parse('653b714e-f9b3-51cb-954f-5ea58f63ab89');

const _ILanguageModel = DynWinRtType.registerInterface(
    "ILanguageModel", IID_ILanguageModel);

const _ILanguageModelStatics = DynWinRtType.registerInterface(
    "ILanguageModelStatics", IID_ILanguageModelStatics)
    .addMethod("GetReadyState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.AIFeatureReadyState', ['Ready', 'NotReady', 'NotSupportedOnCurrentSystem', 'DisabledByUser'], [0, 1, 2, 3])))
    .addMethod("EnsureReadyAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.AIFeatureReadyResult', WinGuid.parse('936a78a6-c242-5937-9814-e512d4193a6d')), DynWinRtType.f64())))
    .addMethod("CreateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModel', WinGuid.parse('6331c629-8c86-5bfe-8c4e-9ca5573cc14b')))));

const _ILanguageModel2 = DynWinRtType.registerInterface(
    "ILanguageModel2", IID_ILanguageModel2)
    .addMethod("GenerateResponseAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())))
    .addMethod("GenerateResponseAsync2", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelOptions', WinGuid.parse('7f380003-5a09-5f1f-afb0-aa483e3670cc'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())))
    .addMethod("GenerateResponseAsync3", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelContext', WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelOptions', WinGuid.parse('7f380003-5a09-5f1f-afb0-aa483e3670cc'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())))
    .addMethod("GenerateResponseFromEmbeddingsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))])).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())))
    .addMethod("GenerateResponseFromEmbeddingsAsync2", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))])).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelOptions', WinGuid.parse('7f380003-5a09-5f1f-afb0-aa483e3670cc'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())))
    .addMethod("GenerateResponseFromEmbeddingsAsync3", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelContext', WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e'))).addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))])).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelOptions', WinGuid.parse('7f380003-5a09-5f1f-afb0-aa483e3670cc'))).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())))
    .addMethod("GenerateEmbeddingVectors", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelEmbeddingVectorResult', WinGuid.parse('4dbdb154-ee3c-56f6-a40b-413e95bd5acb'))))
    .addMethod("GenerateEmbeddingVectors2", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.ContentFilterOptions', WinGuid.parse('6808be9f-80d2-5136-8a8a-1f5c52c824ad'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelEmbeddingVectorResult', WinGuid.parse('4dbdb154-ee3c-56f6-a40b-413e95bd5acb'))))
    .addMethod("GetUsablePromptLength", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.u64()))
    .addMethod("GetUsablePromptLength2", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelContext', WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.u64()))
    .addMethod("GetVectorSpaceId", new DynWinRtMethodSig().addOut(DynWinRtType.guidType()))
    .addMethod("CreateContext", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelContext', WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e'))))
    .addMethod("CreateContext2", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelContext', WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e'))))
    .addMethod("CreateContext3", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.ContentFilterOptions', WinGuid.parse('6808be9f-80d2-5136-8a8a-1f5c52c824ad'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelContext', WinGuid.parse('518b305c-7b69-5a33-8129-d47d6b8eec4e'))));

class LanguageModel {
    static _s_ILanguageModelStatics;
    static s_ILanguageModelStatics() { return LanguageModel._s_ILanguageModelStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Text.LanguageModel').cast(IID_ILanguageModelStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_ILanguageModel);
    }

    static getReadyState() {
        return _ILanguageModelStatics.method(6).invoke(LanguageModel.s_ILanguageModelStatics(), []).toNumber();
    }

    static ensureReadyAsync() {
        const _op = _ILanguageModelStatics.method(7).invoke(LanguageModel.s_ILanguageModelStatics(), []);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_AIFeatureReadyResult.AIFeatureReadyResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    static async createAsync() {
        return new LanguageModel((await _ILanguageModelStatics.method(8).invoke(LanguageModel.s_ILanguageModelStatics(), []).toPromise()));
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class ILanguageModel2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new ILanguageModel2(obj.cast(IID_ILanguageModel2));
    }

    generateResponseAsync(operation) {
        const _op = _ILanguageModel2.method(6).invoke(this._obj, [DynWinRtValue.hstring(operation)]);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_LanguageModelResponseResult.LanguageModelResponseResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    generateResponseAsync2(operation, prompt) {
        const _op = _ILanguageModel2.method(7).invoke(this._obj, [DynWinRtValue.hstring(operation), prompt._obj || prompt]);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_LanguageModelResponseResult.LanguageModelResponseResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    generateResponseAsync3(operation, context, prompt) {
        const _op = _ILanguageModel2.method(8).invoke(this._obj, [operation._obj || operation, DynWinRtValue.hstring(context), prompt._obj || prompt]);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_LanguageModelResponseResult.LanguageModelResponseResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    generateResponseFromEmbeddingsAsync(operation) {
        const _op = _ILanguageModel2.method(9).invoke(this._obj, [operation._obj || operation]);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_LanguageModelResponseResult.LanguageModelResponseResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    generateResponseFromEmbeddingsAsync2(operation, promptEmbedding) {
        const _op = _ILanguageModel2.method(10).invoke(this._obj, [operation._obj || operation, promptEmbedding._obj || promptEmbedding]);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_LanguageModelResponseResult.LanguageModelResponseResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    generateResponseFromEmbeddingsAsync3(operation, context, promptEmbedding) {
        const _op = _ILanguageModel2.method(11).invoke(this._obj, [operation._obj || operation, context._obj || context, promptEmbedding._obj || promptEmbedding]);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_LanguageModelResponseResult.LanguageModelResponseResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }

    generateEmbeddingVectors(result) {
        return new _m_LanguageModelEmbeddingVectorResult.LanguageModelEmbeddingVectorResult(_ILanguageModel2.method(12).invoke(this._obj, [DynWinRtValue.hstring(result)]));
    }

    generateEmbeddingVectors2(result, prompt) {
        return new _m_LanguageModelEmbeddingVectorResult.LanguageModelEmbeddingVectorResult(_ILanguageModel2.method(13).invoke(this._obj, [DynWinRtValue.hstring(result), prompt._obj || prompt]));
    }

    getUsablePromptLength(result) {
        return _ILanguageModel2.method(14).invoke(this._obj, [DynWinRtValue.hstring(result)]).toI64();
    }

    getUsablePromptLength2(result, context) {
        return _ILanguageModel2.method(15).invoke(this._obj, [result._obj || result, DynWinRtValue.hstring(context)]).toI64();
    }

    getVectorSpaceId() {
        return _ILanguageModel2.method(16).invoke(this._obj, []).toString();
    }

    createContext() {
        return new _m_LanguageModelContext.LanguageModelContext(_ILanguageModel2.method(17).invoke(this._obj, []));
    }

    createContext2(result) {
        return new _m_LanguageModelContext.LanguageModelContext(_ILanguageModel2.method(18).invoke(this._obj, [DynWinRtValue.hstring(result)]));
    }

    createContext3(result, systemPrompt) {
        return new _m_LanguageModelContext.LanguageModelContext(_ILanguageModel2.method(19).invoke(this._obj, [DynWinRtValue.hstring(result), systemPrompt._obj || systemPrompt]));
    }
}
module.exports = { LanguageModel, ILanguageModel2 };
