// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IVectorView_EmbeddingVector = require('./IVectorView_EmbeddingVector');
const _m_EmbeddingVector = require('./EmbeddingVector');
const _m_LanguageModelResponseStatus = require('./LanguageModelResponseStatus');

const IID_ILanguageModelEmbeddingVectorResult = WinGuid.parse('4dbdb154-ee3c-56f6-a40b-413e95bd5acb');

const _ILanguageModelEmbeddingVectorResult = DynWinRtType.registerInterface(
    "ILanguageModelEmbeddingVectorResult", IID_ILanguageModelEmbeddingVectorResult)
    .addMethod("get_EmbeddingVectors", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Microsoft.Windows.AI.Foundation.EmbeddingVector', WinGuid.parse('07bdaa90-b3d2-5701-97d1-c390ec62799c'))])))
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.Text.LanguageModelResponseStatus', ['Complete', 'InProgress', 'BlockedByPolicy', 'PromptLargerThanContext', 'PromptBlockedByContentModeration', 'ResponseBlockedByContentModeration', 'Error'], [0, 1, 2, 3, 4, 5, 6])))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.HResult', [DynWinRtType.i32()])));

class LanguageModelEmbeddingVectorResult {

    constructor(obj) {
        this._obj = obj.cast(IID_ILanguageModelEmbeddingVectorResult);
    }

    get embeddingVectors() {
        return new _m_IVectorView_EmbeddingVector.IVectorView_EmbeddingVector(_ILanguageModelEmbeddingVectorResult.method(6).invoke(this._obj, []));
    }

    get status() {
        return _ILanguageModelEmbeddingVectorResult.method(7).invoke(this._obj, []).toNumber();
    }

    get extendedError() {
        return _ILanguageModelEmbeddingVectorResult.method(8).invoke(this._obj, []).toNumber();
    }
}
module.exports = { LanguageModelEmbeddingVectorResult };
