// Generated by winrt-meta — do not edit

const LimitedAccessFeatureStatus = Object.freeze({ Unavailable: 0, Available: 1, AvailableWithoutToken: 2, Unknown: 3 });
module.exports = { LimitedAccessFeatureStatus };
