// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_LimitedAccessFeatureRequestResult = require('./LimitedAccessFeatureRequestResult');

const IID_ILimitedAccessFeaturesStatics = WinGuid.parse('8be612d4-302b-5fbf-a632-1a99e43e8925');

const _ILimitedAccessFeaturesStatics = DynWinRtType.registerInterface(
    "ILimitedAccessFeaturesStatics", IID_ILimitedAccessFeaturesStatics)
    .addMethod("TryUnlockFeature", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.ApplicationModel.LimitedAccessFeatureRequestResult', WinGuid.parse('d45156a6-1e24-5ddd-abb4-6188aba4d5bf'))));

class LimitedAccessFeatures {
    static _s_ILimitedAccessFeaturesStatics;
    static s_ILimitedAccessFeaturesStatics() { return LimitedAccessFeatures._s_ILimitedAccessFeaturesStatics ??= DynWinRtValue.activationFactory('Windows.ApplicationModel.LimitedAccessFeatures').cast(IID_ILimitedAccessFeaturesStatics); }

    constructor(obj) {
        this._obj = obj;
    }

    static tryUnlockFeature(result, featureId, token) {
        return new _m_LimitedAccessFeatureRequestResult.LimitedAccessFeatureRequestResult(_ILimitedAccessFeaturesStatics.method(6).invoke(LimitedAccessFeatures.s_ILimitedAccessFeaturesStatics(), [DynWinRtValue.hstring(result), DynWinRtValue.hstring(featureId), DynWinRtValue.hstring(token)]));
    }
}
module.exports = { LimitedAccessFeatures };
