// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IReference_DateTime } = require('./IReference_DateTime');
const { LimitedAccessFeatureStatus } = require('./LimitedAccessFeatureStatus');

const IID_ILimitedAccessFeatureRequestResult = WinGuid.parse('d45156a6-1e24-5ddd-abb4-6188aba4d5bf');

const _ILimitedAccessFeatureRequestResult = DynWinRtType.registerInterface(
    "ILimitedAccessFeatureRequestResult", IID_ILimitedAccessFeatureRequestResult)
    .addMethod("get_FeatureId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.ApplicationModel.LimitedAccessFeatureStatus', ['Unavailable', 'Available', 'AvailableWithoutToken', 'Unknown'], [0, 1, 2, 3])))
    .addMethod("get_EstimatedRemovalDate", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])])));

function _unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
function _packDateTime(v) {
    const s = DynWinRtStruct.create(_DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}

class LimitedAccessFeatureRequestResult {

    constructor(obj) {
        this._obj = obj.cast(IID_ILimitedAccessFeatureRequestResult);
    }

    get featureId() {
        return _ILimitedAccessFeatureRequestResult.method(6).invoke(this._obj, []).toString();
    }

    get status() {
        return _ILimitedAccessFeatureRequestResult.method(7).invoke(this._obj, []).toNumber();
    }

    get estimatedRemovalDate() {
        return new IReference_DateTime(_ILimitedAccessFeatureRequestResult.method(8).invoke(this._obj, []));
    }
}
module.exports = { LimitedAccessFeatureRequestResult };
