// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_IClosable } = require('./IClosable');
const _m_IClosable = require('./IClosable');

const IID_ILowRankAdaptation = WinGuid.parse('904dd39a-91d5-5ffb-9dc2-137461e28d63');

const _ILowRankAdaptation = DynWinRtType.registerInterface(
    "ILowRankAdaptation", IID_ILowRankAdaptation);

class LowRankAdaptation {

    constructor(obj) {
        this._obj = obj.cast(IID_ILowRankAdaptation);
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { LowRankAdaptation };
