// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IIterable_IKeyValuePair_String_Object = require('./IIterable_IKeyValuePair_String_Object');
const _m_IIterable_String = require('./IIterable_String');
const _m_IKeyValuePair_String_Object = require('./IKeyValuePair_String_Object');
const _m_IMap_String_Object = require('./IMap_String_Object');
const _m_IVector_String = require('./IVector_String');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_IStorageItemExtraProperties } = require('./IStorageItemExtraProperties');
const _m_IStorageItemExtraProperties = require('./IStorageItemExtraProperties');

const IID_IMusicProperties = WinGuid.parse('bc8aab62-66ec-419a-bc5d-ca65a4cb46da');

const _IMusicProperties = DynWinRtType.registerInterface(
    "IMusicProperties", IID_IMusicProperties)
    .addMethod("get_Album", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Album", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Artist", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Artist", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Genre", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_TrackNumber", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_TrackNumber", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Title", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Title", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Rating", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Rating", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Duration", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.TimeSpan', [DynWinRtType.i64()])))
    .addMethod("get_Bitrate", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_AlbumArtist", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_AlbumArtist", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Composers", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Conductors", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Subtitle", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Subtitle", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Producers", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Publisher", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Publisher", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Writers", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Year", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Year", new DynWinRtMethodSig().addIn(DynWinRtType.u32()));

function _unpackTimeSpan(v) {
    const s = v.asStruct();
    return { duration: s.getI64(0) };
}
const _TimeSpan_Type = DynWinRtType.structType('Windows.Foundation.TimeSpan', [DynWinRtType.i64()]);
function _packTimeSpan(v) {
    const s = DynWinRtStruct.create(_TimeSpan_Type);
    s.setI64(0, v.duration);
    return s;
}

class MusicProperties {

    constructor(obj) {
        this._obj = obj.cast(IID_IMusicProperties);
    }

    get album() {
        return _IMusicProperties.method(6).invoke(this._obj, []).toString();
    }

    set album(value) {
        _IMusicProperties.method(7).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get artist() {
        return _IMusicProperties.method(8).invoke(this._obj, []).toString();
    }

    set artist(value) {
        _IMusicProperties.method(9).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get genre() {
        return new _m_IVector_String.IVector_String(_IMusicProperties.method(10).invoke(this._obj, []));
    }

    get trackNumber() {
        return _IMusicProperties.method(11).invoke(this._obj, []).toNumber();
    }

    set trackNumber(value) {
        _IMusicProperties.method(12).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get title() {
        return _IMusicProperties.method(13).invoke(this._obj, []).toString();
    }

    set title(value) {
        _IMusicProperties.method(14).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get rating() {
        return _IMusicProperties.method(15).invoke(this._obj, []).toNumber();
    }

    set rating(value) {
        _IMusicProperties.method(16).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get duration() {
        return _unpackTimeSpan(_IMusicProperties.method(17).invoke(this._obj, []));
    }

    get bitrate() {
        return _IMusicProperties.method(18).invoke(this._obj, []).toNumber();
    }

    get albumArtist() {
        return _IMusicProperties.method(19).invoke(this._obj, []).toString();
    }

    set albumArtist(value) {
        _IMusicProperties.method(20).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get composers() {
        return new _m_IVector_String.IVector_String(_IMusicProperties.method(21).invoke(this._obj, []));
    }

    get conductors() {
        return new _m_IVector_String.IVector_String(_IMusicProperties.method(22).invoke(this._obj, []));
    }

    get subtitle() {
        return _IMusicProperties.method(23).invoke(this._obj, []).toString();
    }

    set subtitle(value) {
        _IMusicProperties.method(24).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get producers() {
        return new _m_IVector_String.IVector_String(_IMusicProperties.method(25).invoke(this._obj, []));
    }

    get publisher() {
        return _IMusicProperties.method(26).invoke(this._obj, []).toString();
    }

    set publisher(value) {
        _IMusicProperties.method(27).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get writers() {
        return new _m_IVector_String.IVector_String(_IMusicProperties.method(28).invoke(this._obj, []));
    }

    get year() {
        return _IMusicProperties.method(29).invoke(this._obj, []).toNumber();
    }

    set year(value) {
        _IMusicProperties.method(30).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { MusicProperties };
