// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { ProcessorArchitecture } = require('./ProcessorArchitecture');

const IID_IPackageId = WinGuid.parse('1adb665e-37c7-4790-9980-dd7ae74e8bb2');
const IID_IPackageIdWithMetadata = WinGuid.parse('40577a7c-0c9e-443d-9074-855f5ce0a08d');

const _IPackageId = DynWinRtType.registerInterface(
    "IPackageId", IID_IPackageId)
    .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Version", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.ApplicationModel.PackageVersion', [DynWinRtType.u16(), DynWinRtType.u16(), DynWinRtType.u16(), DynWinRtType.u16()])))
    .addMethod("get_Architecture", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.ProcessorArchitecture', ['X86', 'Arm', 'X64', 'Neutral', 'Arm64', 'X86OnArm64', 'Unknown'], [0, 5, 9, 11, 12, 14, 65535])))
    .addMethod("get_ResourceId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Publisher", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_PublisherId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_FullName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_FamilyName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

const _IPackageIdWithMetadata = DynWinRtType.registerInterface(
    "IPackageIdWithMetadata", IID_IPackageIdWithMetadata)
    .addMethod("get_ProductId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Author", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

function _unpackPackageVersion(v) {
    const s = v.asStruct();
    return { major: s.getU16(0), minor: s.getU16(1), build: s.getU16(2), revision: s.getU16(3) };
}
const _PackageVersion_Type = DynWinRtType.structType('Windows.ApplicationModel.PackageVersion', [DynWinRtType.u16(), DynWinRtType.u16(), DynWinRtType.u16(), DynWinRtType.u16()]);
function _packPackageVersion(v) {
    const s = DynWinRtStruct.create(_PackageVersion_Type);
    s.setU16(0, v.major);
    s.setU16(1, v.minor);
    s.setU16(2, v.build);
    s.setU16(3, v.revision);
    return s;
}

class PackageId {

    constructor(obj) {
        this._obj = obj.cast(IID_IPackageId);
    }

    get name() {
        return _IPackageId.method(6).invoke(this._obj, []).toString();
    }

    get version() {
        return _unpackPackageVersion(_IPackageId.method(7).invoke(this._obj, []));
    }

    get architecture() {
        return _IPackageId.method(8).invoke(this._obj, []).toNumber();
    }

    get resourceId() {
        return _IPackageId.method(9).invoke(this._obj, []).toString();
    }

    get publisher() {
        return _IPackageId.method(10).invoke(this._obj, []).toString();
    }

    get publisherId() {
        return _IPackageId.method(11).invoke(this._obj, []).toString();
    }

    get fullName() {
        return _IPackageId.method(12).invoke(this._obj, []).toString();
    }

    get familyName() {
        return _IPackageId.method(13).invoke(this._obj, []).toString();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IPackageIdWithMetadata {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IPackageIdWithMetadata(obj.cast(IID_IPackageIdWithMetadata));
    }

    get productId() {
        return _IPackageIdWithMetadata.method(6).invoke(this._obj, []).toString();
    }

    get author() {
        return _IPackageIdWithMetadata.method(7).invoke(this._obj, []).toString();
    }
}
module.exports = { PackageId, IPackageIdWithMetadata };
