// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IPixelDataProvider = WinGuid.parse('dd831f25-185c-4595-9fb9-ccbe6ec18a6f');

const _IPixelDataProvider = DynWinRtType.registerInterface(
    "IPixelDataProvider", IID_IPixelDataProvider)
    .addMethod("DetachPixelData", new DynWinRtMethodSig().addOut(DynWinRtType.arrayType(DynWinRtType.u8())));

class PixelDataProvider {

    constructor(obj) {
        this._obj = obj.cast(IID_IPixelDataProvider);
    }

    detachPixelData() {
        return _IPixelDataProvider.method(6).invoke(this._obj, []).asArray().toU8Vec();
    }
}
module.exports = { PixelDataProvider };
