// Generated by winrt-meta — do not edit

const PropertyPrefetchOptions = Object.freeze({ None: 0, MusicProperties: 1, VideoProperties: 2, ImageProperties: 4, DocumentProperties: 8, BasicProperties: 16 });
module.exports = { PropertyPrefetchOptions };
