// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const _m_IIterable_String = require('./IIterable_String');
const _m_IVector_SortEntry = require('./IVector_SortEntry');
const _m_IVector_String = require('./IVector_String');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const _m_FolderDepth = require('./FolderDepth');
const _m_CommonFileQuery = require('./CommonFileQuery');
const _m_ThumbnailMode = require('./ThumbnailMode');
const _m_ThumbnailOptions = require('./ThumbnailOptions');
const _m_CommonFolderQuery = require('./CommonFolderQuery');
const _m_DateStackOption = require('./DateStackOption');
const _m_PropertyPrefetchOptions = require('./PropertyPrefetchOptions');
const _m_IndexerOption = require('./IndexerOption');

const IID_IQueryOptions = WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30');
const IID_IQueryOptionsFactory = WinGuid.parse('032e1f8c-a9c1-4e71-8011-0dee9d4811a3');
const IID_IQueryOptionsWithProviderFilter = WinGuid.parse('5b9d1026-15c4-44dd-b89a-47a59b7d7c4f');

const _IQueryOptions = DynWinRtType.registerInterface(
    "IQueryOptions", IID_IQueryOptions)
    .addMethod("get_FileTypeFilter", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_FolderDepth", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.Search.FolderDepth', ['Shallow', 'Deep'], [0, 1])))
    .addMethod("put_FolderDepth", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.FolderDepth', ['Shallow', 'Deep'], [0, 1])))
    .addMethod("get_ApplicationSearchFilter", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_ApplicationSearchFilter", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_UserSearchFilter", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_UserSearchFilter", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Language", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Language", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_IndexerOption", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.Search.IndexerOption', ['UseIndexerWhenAvailable', 'OnlyUseIndexer', 'DoNotUseIndexer', 'OnlyUseIndexerAndOptimizeForIndexedProperties'], [0, 1, 2, 3])))
    .addMethod("put_IndexerOption", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.IndexerOption', ['UseIndexerWhenAvailable', 'OnlyUseIndexer', 'DoNotUseIndexer', 'OnlyUseIndexerAndOptimizeForIndexedProperties'], [0, 1, 2, 3])))
    .addMethod("get_SortOrder", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])])))
    .addMethod("get_GroupPropertyName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_DateStackOption", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.Search.DateStackOption', ['None', 'Year', 'Month'], [0, 1, 2])))
    .addMethod("SaveToString", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("LoadFromString", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("SetThumbnailPrefetch", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailOptions', ['None', 'ReturnOnlyIfCached', 'ResizeThumbnail', 'UseCurrentScale'], [0, 1, 2, 4])))
    .addMethod("SetPropertyPrefetch", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.PropertyPrefetchOptions', ['None', 'MusicProperties', 'VideoProperties', 'ImageProperties', 'DocumentProperties', 'BasicProperties'], [0, 1, 2, 4, 8, 16])).addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.hstring()])));

const _IQueryOptionsFactory = DynWinRtType.registerInterface(
    "IQueryOptionsFactory", IID_IQueryOptionsFactory)
    .addMethod("CreateCommonFileQuery", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.hstring()])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))))
    .addMethod("CreateCommonFolderQuery", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))));

const _IQueryOptionsWithProviderFilter = DynWinRtType.registerInterface(
    "IQueryOptionsWithProviderFilter", IID_IQueryOptionsWithProviderFilter)
    .addMethod("get_StorageProviderIdFilter", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])));

function _unpackSortEntry(v) {
    const s = v.asStruct();
    return { propertyName: s.getHstring(0), ascendingOrder: s.getU8(1) !== 0 };
}
const _SortEntry_Type = DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()]);
function _packSortEntry(v) {
    const s = DynWinRtStruct.create(_SortEntry_Type);
    s.setHstring(0, v.propertyName);
    s.setU8(1, v.ascendingOrder ? 1 : 0);
    return s;
}

class QueryOptions {
    static _f_IQueryOptionsFactory;
    static f_IQueryOptionsFactory() { return QueryOptions._f_IQueryOptionsFactory ??= DynWinRtValue.activationFactory('Windows.Storage.Search.QueryOptions').cast(IID_IQueryOptionsFactory); }

    constructor(obj) {
        this._obj = obj.cast(IID_IQueryOptions);
    }

    static createDefault() {
        return new QueryOptions(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Windows.Storage.Search.QueryOptions'), []));
    }

    static createCommonFileQuery(queryOptions, query) {
        return new QueryOptions(_IQueryOptionsFactory.method(6).invoke(QueryOptions.f_IQueryOptionsFactory(), [DynWinRtValue.i32(queryOptions), query._obj || query]));
    }

    static createCommonFolderQuery(queryOptions) {
        return new QueryOptions(_IQueryOptionsFactory.method(7).invoke(QueryOptions.f_IQueryOptionsFactory(), [DynWinRtValue.i32(queryOptions)]));
    }

    get fileTypeFilter() {
        return new _m_IVector_String.IVector_String(_IQueryOptions.method(6).invoke(this._obj, []));
    }

    get folderDepth() {
        return _IQueryOptions.method(7).invoke(this._obj, []).toNumber();
    }

    set folderDepth(value) {
        _IQueryOptions.method(8).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get applicationSearchFilter() {
        return _IQueryOptions.method(9).invoke(this._obj, []).toString();
    }

    set applicationSearchFilter(value) {
        _IQueryOptions.method(10).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get userSearchFilter() {
        return _IQueryOptions.method(11).invoke(this._obj, []).toString();
    }

    set userSearchFilter(value) {
        _IQueryOptions.method(12).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get language() {
        return _IQueryOptions.method(13).invoke(this._obj, []).toString();
    }

    set language(value) {
        _IQueryOptions.method(14).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get indexerOption() {
        return _IQueryOptions.method(15).invoke(this._obj, []).toNumber();
    }

    set indexerOption(value) {
        _IQueryOptions.method(16).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get sortOrder() {
        return new _m_IVector_SortEntry.IVector_SortEntry(_IQueryOptions.method(17).invoke(this._obj, []));
    }

    get groupPropertyName() {
        return _IQueryOptions.method(18).invoke(this._obj, []).toString();
    }

    get dateStackOption() {
        return _IQueryOptions.method(19).invoke(this._obj, []).toNumber();
    }

    saveToString() {
        return _IQueryOptions.method(20).invoke(this._obj, []).toString();
    }

    loadFromString(value) {
        _IQueryOptions.method(21).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    setThumbnailPrefetch(mode, requestedSize, options) {
        _IQueryOptions.method(22).invoke(this._obj, [DynWinRtValue.i32(mode), DynWinRtValue.i32(requestedSize), DynWinRtValue.i32(options)]);
    }

    setPropertyPrefetch(options, propertiesToRetrieve) {
        _IQueryOptions.method(23).invoke(this._obj, [DynWinRtValue.i32(options), propertiesToRetrieve._obj || propertiesToRetrieve]);
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IQueryOptionsWithProviderFilter {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IQueryOptionsWithProviderFilter(obj.cast(IID_IQueryOptionsWithProviderFilter));
    }

    get storageProviderIdFilter() {
        return new _m_IVector_String.IVector_String(_IQueryOptionsWithProviderFilter.method(6).invoke(this._obj, []));
    }
}
module.exports = { QueryOptions, IQueryOptionsWithProviderFilter };
