// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IRecognizedWord = WinGuid.parse('6b53daab-3410-5088-826a-0788a1ee3b52');

const _IRecognizedWord = DynWinRtType.registerInterface(
    "IRecognizedWord", IID_IRecognizedWord)
    .addMethod("get_Text", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_BoundingBox", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Microsoft.Windows.AI.Imaging.RecognizedTextBoundingBox', [DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()])])))
    .addMethod("get_MatchConfidence", new DynWinRtMethodSig().addOut(DynWinRtType.f32()));

function _unpackPoint(v) {
    const s = v.asStruct();
    return { x: s.getF32(0), y: s.getF32(1) };
}
const _Point_Type = DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]);
function _packPoint(v) {
    const s = DynWinRtStruct.create(_Point_Type);
    s.setF32(0, v.x);
    s.setF32(1, v.y);
    return s;
}

function _unpackRecognizedTextBoundingBox(v) {
    const s = v.asStruct();
    return { bottomLeft: _unpackPoint(s.getStruct(0).toValue()), bottomRight: _unpackPoint(s.getStruct(1).toValue()), topLeft: _unpackPoint(s.getStruct(2).toValue()), topRight: _unpackPoint(s.getStruct(3).toValue()) };
}
const _RecognizedTextBoundingBox_Type = DynWinRtType.structType('Microsoft.Windows.AI.Imaging.RecognizedTextBoundingBox', [DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()])]);
function _packRecognizedTextBoundingBox(v) {
    const s = DynWinRtStruct.create(_RecognizedTextBoundingBox_Type);
    s.setStruct(0, _packPoint(v.bottomLeft));
    s.setStruct(1, _packPoint(v.bottomRight));
    s.setStruct(2, _packPoint(v.topLeft));
    s.setStruct(3, _packPoint(v.topRight));
    return s;
}

class RecognizedWord {

    constructor(obj) {
        this._obj = obj;
    }

    get text() {
        return _IRecognizedWord.method(6).invoke(this._obj, []).toString();
    }

    get boundingBox() {
        return _unpackRecognizedTextBoundingBox(_IRecognizedWord.method(7).invoke(this._obj, []));
    }

    get matchConfidence() {
        return _IRecognizedWord.method(8).invoke(this._obj, []).toF64();
    }
}
module.exports = { RecognizedWord };
