// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const { RecognizedLine } = require('./RecognizedLine');

const IID_IRecognizedText = WinGuid.parse('ae4766d3-2924-57a6-b3d3-b866f59b9972');

const _IRecognizedText = DynWinRtType.registerInterface(
    "IRecognizedText", IID_IRecognizedText)
    .addMethod("get_Lines", new DynWinRtMethodSig().addOut(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.RecognizedLine', WinGuid.parse('612a6be6-f6bb-53c9-84ce-f0a5e565faa7')))))
    .addMethod("get_TextAngle", new DynWinRtMethodSig().addOut(DynWinRtType.f32()));

class RecognizedText {

    constructor(obj) {
        this._obj = obj.cast(IID_IRecognizedText);
    }

    get lines() {
        return _IRecognizedText.method(6).invoke(this._obj, []).asArray().toValues().map(v => new RecognizedLine(v));
    }

    get textAngle() {
        return _IRecognizedText.method(7).invoke(this._obj, []).toF64();
    }
}
module.exports = { RecognizedText };
