// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_RecognizedWord = require('./RecognizedWord');
const _m_RecognizedLineStyle = require('./RecognizedLineStyle');

const IID_IRecognizedLine = WinGuid.parse('612a6be6-f6bb-53c9-84ce-f0a5e565faa7');

const _IRecognizedLine = DynWinRtType.registerInterface(
    "IRecognizedLine", IID_IRecognizedLine)
    .addMethod("get_Text", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_BoundingBox", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Microsoft.Windows.AI.Imaging.RecognizedTextBoundingBox', [DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()])])))
    .addMethod("get_Words", new DynWinRtMethodSig().addOut(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.RecognizedWord', WinGuid.parse('6b53daab-3410-5088-826a-0788a1ee3b52')))))
    .addMethod("get_Style", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.Imaging.RecognizedLineStyle', ['Handwritten'], [0])))
    .addMethod("get_LineStyleConfidence", new DynWinRtMethodSig().addOut(DynWinRtType.f32()));

function _unpackPoint(v) {
    const s = v.asStruct();
    return { x: s.getF32(0), y: s.getF32(1) };
}
const _Point_Type = DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]);
function _packPoint(v) {
    const s = DynWinRtStruct.create(_Point_Type);
    s.setF32(0, v.x);
    s.setF32(1, v.y);
    return s;
}

function _unpackRecognizedTextBoundingBox(v) {
    const s = v.asStruct();
    return { bottomLeft: _unpackPoint(s.getStruct(0).toValue()), bottomRight: _unpackPoint(s.getStruct(1).toValue()), topLeft: _unpackPoint(s.getStruct(2).toValue()), topRight: _unpackPoint(s.getStruct(3).toValue()) };
}
const _RecognizedTextBoundingBox_Type = DynWinRtType.structType('Microsoft.Windows.AI.Imaging.RecognizedTextBoundingBox', [DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()]), DynWinRtType.structType('Windows.Foundation.Point', [DynWinRtType.f32(), DynWinRtType.f32()])]);
function _packRecognizedTextBoundingBox(v) {
    const s = DynWinRtStruct.create(_RecognizedTextBoundingBox_Type);
    s.setStruct(0, _packPoint(v.bottomLeft));
    s.setStruct(1, _packPoint(v.bottomRight));
    s.setStruct(2, _packPoint(v.topLeft));
    s.setStruct(3, _packPoint(v.topRight));
    return s;
}

class RecognizedLine {

    constructor(obj) {
        this._obj = obj.cast(IID_IRecognizedLine);
    }

    get text() {
        return _IRecognizedLine.method(6).invoke(this._obj, []).toString();
    }

    get boundingBox() {
        return _unpackRecognizedTextBoundingBox(_IRecognizedLine.method(7).invoke(this._obj, []));
    }

    get words() {
        return _IRecognizedLine.method(8).invoke(this._obj, []).asArray().toValues().map(v => new _m_RecognizedWord.RecognizedWord(v));
    }

    get style() {
        return _IRecognizedLine.method(9).invoke(this._obj, []).toNumber();
    }

    get lineStyleConfidence() {
        return _IRecognizedLine.method(10).invoke(this._obj, []).toF64();
    }
}
module.exports = { RecognizedLine };
