// Generated by winrt-meta — do not edit

const ScaleFrameStatus = Object.freeze({ NullPtrBuffer: -1000, InvalidSize: -999, InvalidFormat: -998, InvalidScenario: -997, InvalidData: -996, NotAvailable: -995, MemAllocation: -994, Failure: -993, Success: 0 });
module.exports = { ScaleFrameStatus };
