// Generated by winrt-meta — do not edit

const ScreenRegionLabel = Object.freeze({ Text: 0, Image: 1, Table: 2, Container: 3, Menu: 4, ToolBar: 5, AddressBar: 6, Toolpane: 7, TabBar: 8, TitleBar: 9 });
module.exports = { ScreenRegionLabel };
