// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_BitmapPixelFormat = require('./BitmapPixelFormat');
const _m_BitmapBufferAccessMode = require('./BitmapBufferAccessMode');
const _m_BitmapBuffer = require('./BitmapBuffer');
const _m_BitmapAlphaMode = require('./BitmapAlphaMode');
const { IID_IBuffer } = require('./IBuffer');
const _m_IBuffer = require('./IBuffer');
const { IID_IDirect3DSurface } = require('./IDirect3DSurface');
const _m_IDirect3DSurface = require('./IDirect3DSurface');
const { IID_IClosable } = require('./IClosable');
const _m_IClosable = require('./IClosable');

const IID_ISoftwareBitmap = WinGuid.parse('689e0708-7eef-483f-963f-da938818e073');
const IID_ISoftwareBitmapFactory = WinGuid.parse('c99feb69-2d62-4d47-a6b3-4fdb6a07fdf8');
const IID_ISoftwareBitmapStatics = WinGuid.parse('df0385db-672f-4a9d-806e-c2442f343e86');

const _ISoftwareBitmap = DynWinRtType.registerInterface(
    "ISoftwareBitmap", IID_ISoftwareBitmap)
    .addMethod("get_BitmapPixelFormat", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])))
    .addMethod("get_BitmapAlphaMode", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])))
    .addMethod("get_PixelWidth", new DynWinRtMethodSig().addOut(DynWinRtType.i32()))
    .addMethod("get_PixelHeight", new DynWinRtMethodSig().addOut(DynWinRtType.i32()))
    .addMethod("get_IsReadOnly", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("put_DpiX", new DynWinRtMethodSig().addIn(DynWinRtType.f64()))
    .addMethod("get_DpiX", new DynWinRtMethodSig().addOut(DynWinRtType.f64()))
    .addMethod("put_DpiY", new DynWinRtMethodSig().addIn(DynWinRtType.f64()))
    .addMethod("get_DpiY", new DynWinRtMethodSig().addOut(DynWinRtType.f64()))
    .addMethod("LockBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapBufferAccessMode', ['Read', 'ReadWrite', 'Write'], [0, 1, 2])).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.BitmapBuffer', WinGuid.parse('a53e04c4-399c-438c-b28f-a63a6b83d1a1'))))
    .addMethod("CopyTo", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("CopyFromBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("CopyToBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("GetReadOnlyView", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))));

const _ISoftwareBitmapFactory = DynWinRtType.registerInterface(
    "ISoftwareBitmapFactory", IID_ISoftwareBitmapFactory)
    .addMethod("Create", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.i32()).addIn(DynWinRtType.i32()).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("CreateWithAlpha", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.i32()).addIn(DynWinRtType.i32()).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))));

const _ISoftwareBitmapStatics = DynWinRtType.registerInterface(
    "ISoftwareBitmapStatics", IID_ISoftwareBitmapStatics)
    .addMethod("Copy", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("Convert", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("ConvertWithAlpha", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("CreateCopyFromBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.i32()).addIn(DynWinRtType.i32()).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("CreateCopyWithAlphaFromBuffer", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('905a0fe0-bc53-11df-8c49-001e4fc686da'))).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapPixelFormat', ['Unknown', 'Rgba16', 'Rgba8', 'Gray16', 'Gray8', 'Bgra8', 'Nv12', 'P010', 'Yuy2'], [0, 12, 30, 57, 62, 87, 103, 104, 107])).addIn(DynWinRtType.i32()).addIn(DynWinRtType.i32()).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])).addOut(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073'))))
    .addMethod("CreateCopyFromSurfaceAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('0bf4a146-13c1-4694-bee3-7abf15eaf586'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073')))))
    .addMethod("CreateCopyWithAlphaFromSurfaceAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('0bf4a146-13c1-4694-bee3-7abf15eaf586'))).addIn(DynWinRtType.enumType('Windows.Graphics.Imaging.BitmapAlphaMode', ['Premultiplied', 'Straight', 'Ignore'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Graphics.Imaging.SoftwareBitmap', WinGuid.parse('689e0708-7eef-483f-963f-da938818e073')))));

class SoftwareBitmap {
    static _f_ISoftwareBitmapFactory;
    static f_ISoftwareBitmapFactory() { return SoftwareBitmap._f_ISoftwareBitmapFactory ??= DynWinRtValue.activationFactory('Windows.Graphics.Imaging.SoftwareBitmap').cast(IID_ISoftwareBitmapFactory); }
    static _s_ISoftwareBitmapStatics;
    static s_ISoftwareBitmapStatics() { return SoftwareBitmap._s_ISoftwareBitmapStatics ??= DynWinRtValue.activationFactory('Windows.Graphics.Imaging.SoftwareBitmap').cast(IID_ISoftwareBitmapStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_ISoftwareBitmap);
    }

    static create(value, format, width) {
        return new SoftwareBitmap(_ISoftwareBitmapFactory.method(6).invoke(SoftwareBitmap.f_ISoftwareBitmapFactory(), [DynWinRtValue.i32(value), DynWinRtValue.i32(format), DynWinRtValue.i32(width)]));
    }

    static createWithAlpha(value, format, width, height) {
        return new SoftwareBitmap(_ISoftwareBitmapFactory.method(7).invoke(SoftwareBitmap.f_ISoftwareBitmapFactory(), [DynWinRtValue.i32(value), DynWinRtValue.i32(format), DynWinRtValue.i32(width), DynWinRtValue.i32(height)]));
    }

    static copy(value) {
        return new SoftwareBitmap(_ISoftwareBitmapStatics.method(6).invoke(SoftwareBitmap.s_ISoftwareBitmapStatics(), [value._obj || value]));
    }

    static convert(value, source) {
        return new SoftwareBitmap(_ISoftwareBitmapStatics.method(7).invoke(SoftwareBitmap.s_ISoftwareBitmapStatics(), [value._obj || value, DynWinRtValue.i32(source)]));
    }

    static convertWithAlpha(value, source, format) {
        return new SoftwareBitmap(_ISoftwareBitmapStatics.method(8).invoke(SoftwareBitmap.s_ISoftwareBitmapStatics(), [value._obj || value, DynWinRtValue.i32(source), DynWinRtValue.i32(format)]));
    }

    static createCopyFromBuffer(value, source, format, width) {
        return new SoftwareBitmap(_ISoftwareBitmapStatics.method(9).invoke(SoftwareBitmap.s_ISoftwareBitmapStatics(), [value._obj || value, DynWinRtValue.i32(source), DynWinRtValue.i32(format), DynWinRtValue.i32(width)]));
    }

    static createCopyWithAlphaFromBuffer(value, source, format, width, height) {
        return new SoftwareBitmap(_ISoftwareBitmapStatics.method(10).invoke(SoftwareBitmap.s_ISoftwareBitmapStatics(), [value._obj || value, DynWinRtValue.i32(source), DynWinRtValue.i32(format), DynWinRtValue.i32(width), DynWinRtValue.i32(height)]));
    }

    static async createCopyFromSurfaceAsync(value) {
        return new SoftwareBitmap((await _ISoftwareBitmapStatics.method(11).invoke(SoftwareBitmap.s_ISoftwareBitmapStatics(), [value._obj || value]).toPromise()));
    }

    static async createCopyWithAlphaFromSurfaceAsync(value, surface) {
        return new SoftwareBitmap((await _ISoftwareBitmapStatics.method(12).invoke(SoftwareBitmap.s_ISoftwareBitmapStatics(), [value._obj || value, DynWinRtValue.i32(surface)]).toPromise()));
    }

    get bitmapPixelFormat() {
        return _ISoftwareBitmap.method(6).invoke(this._obj, []).toNumber();
    }

    get bitmapAlphaMode() {
        return _ISoftwareBitmap.method(7).invoke(this._obj, []).toNumber();
    }

    get pixelWidth() {
        return _ISoftwareBitmap.method(8).invoke(this._obj, []).toNumber();
    }

    get pixelHeight() {
        return _ISoftwareBitmap.method(9).invoke(this._obj, []).toNumber();
    }

    get isReadOnly() {
        return _ISoftwareBitmap.method(10).invoke(this._obj, []).toBool();
    }

    set dpiX(value) {
        _ISoftwareBitmap.method(11).invoke(this._obj, [DynWinRtValue.f64(value)]);
    }

    get dpiX() {
        return _ISoftwareBitmap.method(12).invoke(this._obj, []).toF64();
    }

    set dpiY(value) {
        _ISoftwareBitmap.method(13).invoke(this._obj, [DynWinRtValue.f64(value)]);
    }

    get dpiY() {
        return _ISoftwareBitmap.method(14).invoke(this._obj, []).toF64();
    }

    lockBuffer(value) {
        return new _m_BitmapBuffer.BitmapBuffer(_ISoftwareBitmap.method(15).invoke(this._obj, [DynWinRtValue.i32(value)]));
    }

    copyTo(bitmap) {
        _ISoftwareBitmap.method(16).invoke(this._obj, [bitmap._obj || bitmap]);
    }

    copyFromBuffer(buffer) {
        _ISoftwareBitmap.method(17).invoke(this._obj, [buffer._obj || buffer]);
    }

    copyToBuffer(buffer) {
        _ISoftwareBitmap.method(18).invoke(this._obj, [buffer._obj || buffer]);
    }

    getReadOnlyView() {
        return new SoftwareBitmap(_ISoftwareBitmap.method(19).invoke(this._obj, []));
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { SoftwareBitmap };
