// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');

const IID_IStorageProvider = WinGuid.parse('e705eed4-d478-47d6-ba46-1a8ebe114a20');
const IID_IStorageProvider2 = WinGuid.parse('010d1917-3404-414b-9fd7-cd44472eaa39');

const _IStorageProvider = DynWinRtType.registerInterface(
    "IStorageProvider", IID_IStorageProvider)
    .addMethod("get_Id", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_DisplayName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

const _IStorageProvider2 = DynWinRtType.registerInterface(
    "IStorageProvider2", IID_IStorageProvider2)
    .addMethod("IsPropertySupportedForPartialFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.boolType())));

class StorageProvider {

    constructor(obj) {
        this._obj = obj;
    }

    get id() {
        return _IStorageProvider.method(6).invoke(this._obj, []).toString();
    }

    get displayName() {
        return _IStorageProvider.method(7).invoke(this._obj, []).toString();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IStorageProvider2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageProvider2(obj.cast(IID_IStorageProvider2));
    }

    async isPropertySupportedForPartialFileAsync(operation) {
        return (await _IStorageProvider2.method(6).invoke(this._obj, [DynWinRtValue.hstring(operation)]).toPromise()).toBool();
    }
}
module.exports = { StorageProvider, IStorageProvider2 };
