// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IVectorView_StorageLibraryChange = require('./IVectorView_StorageLibraryChange');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const _m_StorageLibraryChange = require('./StorageLibraryChange');

const IID_IStorageLibraryChangeReader = WinGuid.parse('f205bc83-fca2-41f9-8954-ee2e991eb96f');
const IID_IStorageLibraryChangeReader2 = WinGuid.parse('abf4868b-fbcc-4a4f-999e-e7ab7c646dbe');

const _IStorageLibraryChangeReader = DynWinRtType.registerInterface(
    "IStorageLibraryChangeReader", IID_IStorageLibraryChangeReader)
    .addMethod("ReadBatchAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageLibraryChange', WinGuid.parse('00980b23-2be2-4909-aa48-159f5203a51e'))]))))
    .addMethod("AcceptChangesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()));

const _IStorageLibraryChangeReader2 = DynWinRtType.registerInterface(
    "IStorageLibraryChangeReader2", IID_IStorageLibraryChangeReader2)
    .addMethod("GetLastChangeId", new DynWinRtMethodSig().addOut(DynWinRtType.u64()));

class StorageLibraryChangeReader {

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageLibraryChangeReader);
    }

    async readBatchAsync() {
        return new _m_IVectorView_StorageLibraryChange.IVectorView_StorageLibraryChange((await _IStorageLibraryChangeReader.method(6).invoke(this._obj, []).toPromise()));
    }

    async acceptChangesAsync() {
        return (await _IStorageLibraryChangeReader.method(7).invoke(this._obj, []).toPromise());
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IStorageLibraryChangeReader2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageLibraryChangeReader2(obj.cast(IID_IStorageLibraryChangeReader2));
    }

    getLastChangeId() {
        return _IStorageLibraryChangeReader2.method(6).invoke(this._obj, []).toI64();
    }
}
module.exports = { StorageLibraryChangeReader, IStorageLibraryChangeReader2 };
