// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IMap_String_IVectorView_TextSegment = require('./IMap_String_IVectorView_TextSegment');
const _m_IVectorView_StorageFile = require('./IVectorView_StorageFile');
const _m_IVectorView_TextSegment = require('./IVectorView_TextSegment');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const _m_StorageFile = require('./StorageFile');
const _m_StorageFolder = require('./StorageFolder');
const { IID_IStorageQueryResultBase } = require('./IStorageQueryResultBase');
const _m_IStorageQueryResultBase = require('./IStorageQueryResultBase');
const _m_QueryOptions = require('./QueryOptions');

const IID_IStorageFileQueryResult = WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e');
const IID_IStorageFileQueryResult2 = WinGuid.parse('4e5db9dd-7141-46c4-8be3-e9dc9e27275c');

const _IStorageFileQueryResult = DynWinRtType.registerInterface(
    "IStorageFileQueryResult", IID_IStorageFileQueryResult)
    .addMethod("GetFilesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
    .addMethod("GetFilesAsyncDefaultStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))));

const _IStorageQueryResultBase = DynWinRtType.registerInterface(
    "IStorageQueryResultBase", IID_IStorageQueryResultBase)
    .addMethod("GetItemCountAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.u32())))
    .addMethod("get_Folder", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))))
    .addMethod("add_ContentsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('c297d70d-7353-47ab-ba58-8c61425dc54b')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_ContentsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_OptionsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('c297d70d-7353-47ab-ba58-8c61425dc54b')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_OptionsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("FindStartIndexAsync", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.u32())))
    .addMethod("GetCurrentQueryOptions", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))))
    .addMethod("ApplyNewQueryOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))));

const _IStorageFileQueryResult2 = DynWinRtType.registerInterface(
    "IStorageFileQueryResult2", IID_IStorageFileQueryResult2)
    .addMethod("GetMatchingPropertiesWithRanges", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addOut(DynWinRtType.parameterized(WinGuid.parse('3c2925fe-8519-45c1-aa79-197b6718c1c1'), [DynWinRtType.hstring(), DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.structType('Windows.Data.Text.TextSegment', [DynWinRtType.u32(), DynWinRtType.u32()])])])));

function _unpackEventRegistrationToken(v) {
    const s = v.asStruct();
    return { value: s.getI64(0) };
}
const _EventRegistrationToken_Type = DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()]);
function _packEventRegistrationToken(v) {
    const s = DynWinRtStruct.create(_EventRegistrationToken_Type);
    s.setI64(0, v.value);
    return s;
}

function _unpackTextSegment(v) {
    const s = v.asStruct();
    return { startPosition: s.getU32(0), length: s.getU32(1) };
}
const _TextSegment_Type = DynWinRtType.structType('Windows.Data.Text.TextSegment', [DynWinRtType.u32(), DynWinRtType.u32()]);
function _packTextSegment(v) {
    const s = DynWinRtStruct.create(_TextSegment_Type);
    s.setU32(0, v.startPosition);
    s.setU32(1, v.length);
    return s;
}

class StorageFileQueryResult {

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageFileQueryResult);
    }

    async getFilesAsync(operation, startIndex) {
        return new _m_IVectorView_StorageFile.IVectorView_StorageFile((await _IStorageFileQueryResult.method(6).invoke(this._obj, [DynWinRtValue.i32(operation), DynWinRtValue.i32(startIndex)]).toPromise()));
    }

    async getFilesAsyncDefaultStartAndCount() {
        return new _m_IVectorView_StorageFile.IVectorView_StorageFile((await _IStorageFileQueryResult.method(7).invoke(this._obj, []).toPromise()));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IStorageFileQueryResult2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFileQueryResult2(obj.cast(IID_IStorageFileQueryResult2));
    }

    getMatchingPropertiesWithRanges(result) {
        return new _m_IMap_String_IVectorView_TextSegment.IMap_String_IVectorView_TextSegment(_IStorageFileQueryResult2.method(6).invoke(this._obj, [result._obj || result]));
    }
}
module.exports = { StorageFileQueryResult, IStorageFileQueryResult2 };
