// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_IRandomAccessStream } = require('./IRandomAccessStream');
const _m_IRandomAccessStream = require('./IRandomAccessStream');
const { IID_IClosable } = require('./IClosable');
const _m_IClosable = require('./IClosable');

const IID_IStorageStreamTransaction = WinGuid.parse('f67cf363-a53d-4d94-ae2c-67232d93acdd');

const _IStorageStreamTransaction = DynWinRtType.registerInterface(
    "IStorageStreamTransaction", IID_IStorageStreamTransaction)
    .addMethod("get_Stream", new DynWinRtMethodSig().addOut(DynWinRtType.interface(WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da'))))
    .addMethod("CommitAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()));

class StorageStreamTransaction {

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageStreamTransaction);
    }

    get stream() {
        return new _m_IRandomAccessStream.IRandomAccessStream(_IStorageStreamTransaction.method(6).invoke(this._obj, []));
    }

    async commitAsync() {
        return (await _IStorageStreamTransaction.method(7).invoke(this._obj, []).toPromise());
    }

    close() {
        _m_IClosable.IClosable.from(this._obj).close();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { StorageStreamTransaction };
