// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const _m_ThumbnailMode = require('./ThumbnailMode');
const { IID_IRandomAccessStream } = require('./IRandomAccessStream');
const _m_IRandomAccessStream = require('./IRandomAccessStream');
const _m_ThumbnailOptions = require('./ThumbnailOptions');
const { IID_IStorageFile } = require('./IStorageFile');
const _m_IStorageFile = require('./IStorageFile');
const _m_FileAccessMode = require('./FileAccessMode');
const _m_User = require('./User');
const _m_StorageFolder = require('./StorageFolder');
const _m_StorageItemThumbnail = require('./StorageItemThumbnail');
const { IID_IStorageItem } = require('./IStorageItem');
const _m_IStorageItem = require('./IStorageItem');
const _m_StorageOpenOptions = require('./StorageOpenOptions');
const { IID_IStorageFolder } = require('./IStorageFolder');
const _m_IStorageFolder = require('./IStorageFolder');
const _m_NameCollisionOption = require('./NameCollisionOption');
const _m_Uri = require('./Uri');
const { IID_IRandomAccessStreamWithContentType } = require('./IRandomAccessStreamWithContentType');
const _m_IRandomAccessStreamWithContentType = require('./IRandomAccessStreamWithContentType');
const { IID_IInputStream } = require('./IInputStream');
const _m_IInputStream = require('./IInputStream');
const _m_FileAttributes = require('./FileAttributes');
const { IID_IRandomAccessStreamReference } = require('./IRandomAccessStreamReference');
const _m_IRandomAccessStreamReference = require('./IRandomAccessStreamReference');
const _m_BasicProperties = require('./BasicProperties');
const _m_StorageItemTypes = require('./StorageItemTypes');
const _m_StorageStreamTransaction = require('./StorageStreamTransaction');
const _m_StorageDeleteOption = require('./StorageDeleteOption');
const _m_StorageProvider = require('./StorageProvider');
const _m_StorageItemContentProperties = require('./StorageItemContentProperties');
const { IID_IStorageItemProperties } = require('./IStorageItemProperties');
const _m_IStorageItemProperties = require('./IStorageItemProperties');
const { IID_IStorageItemProperties2 } = require('./IStorageItemProperties2');
const _m_IStorageItemProperties2 = require('./IStorageItemProperties2');
const { IID_IStorageItem2 } = require('./IStorageItem2');
const _m_IStorageItem2 = require('./IStorageItem2');
const { IID_IStorageItemPropertiesWithProvider } = require('./IStorageItemPropertiesWithProvider');
const _m_IStorageItemPropertiesWithProvider = require('./IStorageItemPropertiesWithProvider');

const IID_IStorageFileStatics2 = WinGuid.parse('5c76a781-212e-4af9-8f04-740cae108974');
const IID_IStorageFileStatics = WinGuid.parse('5984c710-daf2-43c8-8bb4-a4d3eacfd03f');
const IID_IInputStreamReference = WinGuid.parse('43929d18-5ec9-4b5a-919c-4205b0c804b6');
const IID_IStorageFilePropertiesWithAvailability = WinGuid.parse('afcbbe9b-582b-4133-9648-e44ca46ee491');
const IID_IStorageFile2 = WinGuid.parse('954e4bcf-0a77-42fb-b777-c2ed58a52e44');

const _IStorageFile = DynWinRtType.registerInterface(
    "IStorageFile", IID_IStorageFile)
    .addMethod("get_FileType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_ContentType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("OpenAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileAccessMode', ['Read', 'ReadWrite'], [0, 1])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da')))))
    .addMethod("OpenTransactedWriteAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageStreamTransaction', WinGuid.parse('f67cf363-a53d-4d94-ae2c-67232d93acdd')))))
    .addMethod("CopyOverloadDefaultNameAndOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CopyOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CopyOverload", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CopyAndReplaceAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("MoveOverloadDefaultNameAndOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("MoveOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("MoveOverload", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("MoveAndReplaceAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addOut(DynWinRtType.iAsyncAction()));

const _IStorageFileStatics2 = DynWinRtType.registerInterface(
    "IStorageFileStatics2", IID_IStorageFileStatics2)
    .addMethod("GetFileFromPathForUserAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))));

const _IStorageFileStatics = DynWinRtType.registerInterface(
    "IStorageFileStatics", IID_IStorageFileStatics)
    .addMethod("GetFileFromPathAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("GetFileFromApplicationUriAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CreateStreamedFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.interface(WinGuid.parse('fef6a824-2fe1-4d07-a35b-b77c50b5f4cc'))).addIn(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("ReplaceWithStreamedFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addIn(DynWinRtType.interface(WinGuid.parse('fef6a824-2fe1-4d07-a35b-b77c50b5f4cc'))).addIn(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CreateStreamedFileFromUriAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))).addIn(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("ReplaceWithStreamedFileFromUriAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addIn(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))).addIn(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))));

const _IInputStreamReference = DynWinRtType.registerInterface(
    "IInputStreamReference", IID_IInputStreamReference)
    .addMethod("OpenSequentialReadAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('905a0fe2-bc53-11df-8c49-001e4fc686da')))));

const _IRandomAccessStreamReference = DynWinRtType.registerInterface(
    "IRandomAccessStreamReference", IID_IRandomAccessStreamReference)
    .addMethod("OpenReadAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))));

const _IStorageFilePropertiesWithAvailability = DynWinRtType.registerInterface(
    "IStorageFilePropertiesWithAvailability", IID_IStorageFilePropertiesWithAvailability)
    .addMethod("get_IsAvailable", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));

const _IStorageFile2 = DynWinRtType.registerInterface(
    "IStorageFile2", IID_IStorageFile2)
    .addMethod("OpenWithOptionsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileAccessMode', ['Read', 'ReadWrite'], [0, 1])).addIn(DynWinRtType.enumType('Windows.Storage.StorageOpenOptions', ['None', 'AllowOnlyReaders', 'AllowReadersAndWriters'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da')))))
    .addMethod("OpenTransactedWriteWithOptionsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageOpenOptions', ['None', 'AllowOnlyReaders', 'AllowReadersAndWriters'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageStreamTransaction', WinGuid.parse('f67cf363-a53d-4d94-ae2c-67232d93acdd')))));

function _unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
function _packDateTime(v) {
    const s = DynWinRtStruct.create(_DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}

class StorageFile {
    static _s_IStorageFileStatics2;
    static s_IStorageFileStatics2() { return StorageFile._s_IStorageFileStatics2 ??= DynWinRtValue.activationFactory('Windows.Storage.StorageFile').cast(IID_IStorageFileStatics2); }
    static _s_IStorageFileStatics;
    static s_IStorageFileStatics() { return StorageFile._s_IStorageFileStatics ??= DynWinRtValue.activationFactory('Windows.Storage.StorageFile').cast(IID_IStorageFileStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageFile);
    }

    static async getFileFromPathForUserAsync(operation, user) {
        return new StorageFile((await _IStorageFileStatics2.method(6).invoke(StorageFile.s_IStorageFileStatics2(), [operation._obj || operation, DynWinRtValue.hstring(user)]).toPromise()));
    }

    static async getFileFromPathAsync(operation) {
        return new StorageFile((await _IStorageFileStatics.method(6).invoke(StorageFile.s_IStorageFileStatics(), [DynWinRtValue.hstring(operation)]).toPromise()));
    }

    static async getFileFromApplicationUriAsync(operation) {
        return new StorageFile((await _IStorageFileStatics.method(7).invoke(StorageFile.s_IStorageFileStatics(), [operation._obj || operation]).toPromise()));
    }

    static async createStreamedFileAsync(operation, displayNameWithExtension, dataRequested) {
        return new StorageFile((await _IStorageFileStatics.method(8).invoke(StorageFile.s_IStorageFileStatics(), [DynWinRtValue.hstring(operation), displayNameWithExtension._obj || displayNameWithExtension, dataRequested._obj || dataRequested]).toPromise()));
    }

    static async replaceWithStreamedFileAsync(operation, fileToReplace, dataRequested) {
        return new StorageFile((await _IStorageFileStatics.method(9).invoke(StorageFile.s_IStorageFileStatics(), [operation._obj || operation, fileToReplace._obj || fileToReplace, dataRequested._obj || dataRequested]).toPromise()));
    }

    static async createStreamedFileFromUriAsync(operation, displayNameWithExtension, uri) {
        return new StorageFile((await _IStorageFileStatics.method(10).invoke(StorageFile.s_IStorageFileStatics(), [DynWinRtValue.hstring(operation), displayNameWithExtension._obj || displayNameWithExtension, uri._obj || uri]).toPromise()));
    }

    static async replaceWithStreamedFileFromUriAsync(operation, fileToReplace, uri) {
        return new StorageFile((await _IStorageFileStatics.method(11).invoke(StorageFile.s_IStorageFileStatics(), [operation._obj || operation, fileToReplace._obj || fileToReplace, uri._obj || uri]).toPromise()));
    }

    get fileType() {
        return _IStorageFile.method(6).invoke(this._obj, []).toString();
    }

    get contentType() {
        return _IStorageFile.method(7).invoke(this._obj, []).toString();
    }

    async openAsync(operation) {
        return new _m_IRandomAccessStream.IRandomAccessStream((await _IStorageFile.method(8).invoke(this._obj, [DynWinRtValue.i32(operation)]).toPromise()));
    }

    async openTransactedWriteAsync() {
        return new _m_StorageStreamTransaction.StorageStreamTransaction((await _IStorageFile.method(9).invoke(this._obj, []).toPromise()));
    }

    async copyOverloadDefaultNameAndOptions(operation) {
        return new StorageFile((await _IStorageFile.method(10).invoke(this._obj, [operation._obj || operation]).toPromise()));
    }

    async copyOverloadDefaultOptions(operation, destinationFolder) {
        return new StorageFile((await _IStorageFile.method(11).invoke(this._obj, [operation._obj || operation, DynWinRtValue.hstring(destinationFolder)]).toPromise()));
    }

    async copyOverload(operation, destinationFolder, desiredNewName) {
        return new StorageFile((await _IStorageFile.method(12).invoke(this._obj, [operation._obj || operation, DynWinRtValue.hstring(destinationFolder), DynWinRtValue.i32(desiredNewName)]).toPromise()));
    }

    async copyAndReplaceAsync(operation) {
        return (await _IStorageFile.method(13).invoke(this._obj, [operation._obj || operation]).toPromise());
    }

    async moveOverloadDefaultNameAndOptions(operation) {
        return (await _IStorageFile.method(14).invoke(this._obj, [operation._obj || operation]).toPromise());
    }

    async moveOverloadDefaultOptions(operation, destinationFolder) {
        return (await _IStorageFile.method(15).invoke(this._obj, [operation._obj || operation, DynWinRtValue.hstring(destinationFolder)]).toPromise());
    }

    async moveOverload(operation, destinationFolder, desiredNewName) {
        return (await _IStorageFile.method(16).invoke(this._obj, [operation._obj || operation, DynWinRtValue.hstring(destinationFolder), DynWinRtValue.i32(desiredNewName)]).toPromise());
    }

    async moveAndReplaceAsync(operation) {
        return (await _IStorageFile.method(17).invoke(this._obj, [operation._obj || operation]).toPromise());
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IInputStreamReference {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IInputStreamReference(obj.cast(IID_IInputStreamReference));
    }

    async openSequentialReadAsync() {
        return new _m_IInputStream.IInputStream((await _IInputStreamReference.method(6).invoke(this._obj, []).toPromise()));
    }
}

class IStorageFilePropertiesWithAvailability {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFilePropertiesWithAvailability(obj.cast(IID_IStorageFilePropertiesWithAvailability));
    }

    get isAvailable() {
        return _IStorageFilePropertiesWithAvailability.method(6).invoke(this._obj, []).toBool();
    }
}

class IStorageFile2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFile2(obj.cast(IID_IStorageFile2));
    }

    async openWithOptionsAsync(operation, accessMode) {
        return new _m_IRandomAccessStream.IRandomAccessStream((await _IStorageFile2.method(6).invoke(this._obj, [DynWinRtValue.i32(operation), DynWinRtValue.i32(accessMode)]).toPromise()));
    }

    async openTransactedWriteWithOptionsAsync(operation) {
        return new _m_StorageStreamTransaction.StorageStreamTransaction((await _IStorageFile2.method(7).invoke(this._obj, [DynWinRtValue.i32(operation)]).toPromise()));
    }
}
module.exports = { StorageFile, IInputStreamReference, IStorageFilePropertiesWithAvailability, IStorageFile2 };
