// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IVectorView_IStorageItem = require('./IVectorView_IStorageItem');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_IStorageQueryResultBase } = require('./IStorageQueryResultBase');
const _m_IStorageQueryResultBase = require('./IStorageQueryResultBase');
const _m_QueryOptions = require('./QueryOptions');
const _m_StorageFolder = require('./StorageFolder');
const { IID_IStorageItem } = require('./IStorageItem');
const _m_IStorageItem = require('./IStorageItem');

const IID_IStorageItemQueryResult = WinGuid.parse('e8948079-9d58-47b8-b2b2-41b07f4795f9');

const _IStorageItemQueryResult = DynWinRtType.registerInterface(
    "IStorageItemQueryResult", IID_IStorageItemQueryResult)
    .addMethod("GetItemsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))]))))
    .addMethod("GetItemsAsyncDefaultStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))]))));

const _IStorageQueryResultBase = DynWinRtType.registerInterface(
    "IStorageQueryResultBase", IID_IStorageQueryResultBase)
    .addMethod("GetItemCountAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.u32())))
    .addMethod("get_Folder", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))))
    .addMethod("add_ContentsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('c297d70d-7353-47ab-ba58-8c61425dc54b')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_ContentsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_OptionsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('c297d70d-7353-47ab-ba58-8c61425dc54b')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_OptionsChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("FindStartIndexAsync", new DynWinRtMethodSig().addIn(DynWinRtType.object()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.u32())))
    .addMethod("GetCurrentQueryOptions", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))))
    .addMethod("ApplyNewQueryOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))));

function _unpackEventRegistrationToken(v) {
    const s = v.asStruct();
    return { value: s.getI64(0) };
}
const _EventRegistrationToken_Type = DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()]);
function _packEventRegistrationToken(v) {
    const s = DynWinRtStruct.create(_EventRegistrationToken_Type);
    s.setI64(0, v.value);
    return s;
}

class StorageItemQueryResult {

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageItemQueryResult);
    }

    async getItemsAsync(operation, startIndex) {
        return new _m_IVectorView_IStorageItem.IVectorView_IStorageItem((await _IStorageItemQueryResult.method(6).invoke(this._obj, [DynWinRtValue.i32(operation), DynWinRtValue.i32(startIndex)]).toPromise()));
    }

    async getItemsAsyncDefaultStartAndCount() {
        return new _m_IVectorView_IStorageItem.IVectorView_IStorageItem((await _IStorageItemQueryResult.method(7).invoke(this._obj, []).toPromise()));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
module.exports = { StorageItemQueryResult };
