// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const _m_StorageLibraryChangeTrackerOptions = require('./StorageLibraryChangeTrackerOptions');
const _m_StorageLibraryChangeReader = require('./StorageLibraryChangeReader');

const IID_IStorageLibraryChangeTracker = WinGuid.parse('9e157316-6073-44f6-9681-7492d1286c90');
const IID_IStorageLibraryChangeTracker2 = WinGuid.parse('cd051c3b-0f9f-42f9-8fb3-158d82e13821');

const _IStorageLibraryChangeTracker = DynWinRtType.registerInterface(
    "IStorageLibraryChangeTracker", IID_IStorageLibraryChangeTracker)
    .addMethod("GetChangeReader", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageLibraryChangeReader', WinGuid.parse('f205bc83-fca2-41f9-8954-ee2e991eb96f'))))
    .addMethod("Enable", new DynWinRtMethodSig())
    .addMethod("Reset", new DynWinRtMethodSig());

const _IStorageLibraryChangeTracker2 = DynWinRtType.registerInterface(
    "IStorageLibraryChangeTracker2", IID_IStorageLibraryChangeTracker2)
    .addMethod("EnableWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.StorageLibraryChangeTrackerOptions', WinGuid.parse('bb52bcd4-1a6d-59c0-ad2a-823a20532483'))))
    .addMethod("Disable", new DynWinRtMethodSig());

class StorageLibraryChangeTracker {

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageLibraryChangeTracker);
    }

    getChangeReader() {
        return new _m_StorageLibraryChangeReader.StorageLibraryChangeReader(_IStorageLibraryChangeTracker.method(6).invoke(this._obj, []));
    }

    enable() {
        _IStorageLibraryChangeTracker.method(7).invoke(this._obj, []);
    }

    reset() {
        _IStorageLibraryChangeTracker.method(8).invoke(this._obj, []);
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IStorageLibraryChangeTracker2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageLibraryChangeTracker2(obj.cast(IID_IStorageLibraryChangeTracker2));
    }

    enableWithOptions(options) {
        _IStorageLibraryChangeTracker2.method(6).invoke(this._obj, [options._obj || options]);
    }

    disable() {
        _IStorageLibraryChangeTracker2.method(7).invoke(this._obj, []);
    }
}
module.exports = { StorageLibraryChangeTracker, IStorageLibraryChangeTracker2 };
