// Generated by winrt-meta — do not edit (delegate)
const { DynWinRtType, WinGuid } = require('dynwinrt-js');

const IID_StreamedFileDataRequestedHandler = DynWinRtType.parameterized(WinGuid.parse('fef6a824-2fe1-4d07-a35b-b77c50b5f4cc'), [DynWinRtType.runtimeClass('Windows.Storage.StreamedFileDataRequest', WinGuid.parse('905a0fe6-bc53-11df-8c49-001e4fc686da'))]).iid();
const StreamedFileDataRequestedHandler_PARAM_TYPES = [DynWinRtType.runtimeClass('Windows.Storage.StreamedFileDataRequest', WinGuid.parse('905a0fe6-bc53-11df-8c49-001e4fc686da'))];
module.exports = { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES };
