// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const { SeverityLevel } = require('./SeverityLevel');

const IID_ITextContentFilterSeverity = WinGuid.parse('68c1ee47-c35c-5f4c-a647-b0c0f64aa0d5');
const IID_ITextContentFilterSeverityFactory = WinGuid.parse('e0ca501e-4004-501e-8984-442d091607d4');

const _ITextContentFilterSeverity = DynWinRtType.registerInterface(
    "ITextContentFilterSeverity", IID_ITextContentFilterSeverity)
    .addMethod("get_Hate", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.ContentSafety.SeverityLevel', ['Minimum', 'Low', 'Medium', 'High'], [10, 11, 12, 13])))
    .addMethod("put_Hate", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Microsoft.Windows.AI.ContentSafety.SeverityLevel', ['Minimum', 'Low', 'Medium', 'High'], [10, 11, 12, 13])))
    .addMethod("get_Sexual", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.ContentSafety.SeverityLevel', ['Minimum', 'Low', 'Medium', 'High'], [10, 11, 12, 13])))
    .addMethod("put_Sexual", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Microsoft.Windows.AI.ContentSafety.SeverityLevel', ['Minimum', 'Low', 'Medium', 'High'], [10, 11, 12, 13])))
    .addMethod("get_Violent", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.ContentSafety.SeverityLevel', ['Minimum', 'Low', 'Medium', 'High'], [10, 11, 12, 13])))
    .addMethod("put_Violent", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Microsoft.Windows.AI.ContentSafety.SeverityLevel', ['Minimum', 'Low', 'Medium', 'High'], [10, 11, 12, 13])))
    .addMethod("get_SelfHarm", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.ContentSafety.SeverityLevel', ['Minimum', 'Low', 'Medium', 'High'], [10, 11, 12, 13])))
    .addMethod("put_SelfHarm", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Microsoft.Windows.AI.ContentSafety.SeverityLevel', ['Minimum', 'Low', 'Medium', 'High'], [10, 11, 12, 13])));

const _ITextContentFilterSeverityFactory = DynWinRtType.registerInterface(
    "ITextContentFilterSeverityFactory", IID_ITextContentFilterSeverityFactory)
    .addMethod("CreateInstance", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Microsoft.Windows.AI.ContentSafety.SeverityLevel', ['Minimum', 'Low', 'Medium', 'High'], [10, 11, 12, 13])).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.ContentSafety.TextContentFilterSeverity', WinGuid.parse('68c1ee47-c35c-5f4c-a647-b0c0f64aa0d5'))));

class TextContentFilterSeverity {
    static _f_ITextContentFilterSeverityFactory;
    static f_ITextContentFilterSeverityFactory() { return TextContentFilterSeverity._f_ITextContentFilterSeverityFactory ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.ContentSafety.TextContentFilterSeverity').cast(IID_ITextContentFilterSeverityFactory); }

    constructor(obj) {
        this._obj = obj;
    }

    static createDefault() {
        return new TextContentFilterSeverity(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Microsoft.Windows.AI.ContentSafety.TextContentFilterSeverity'), []));
    }

    static createInstance(value) {
        return new TextContentFilterSeverity(_ITextContentFilterSeverityFactory.method(6).invoke(TextContentFilterSeverity.f_ITextContentFilterSeverityFactory(), [DynWinRtValue.i32(value)]));
    }

    get hate() {
        return _ITextContentFilterSeverity.method(6).invoke(this._obj, []).toNumber();
    }

    set hate(value) {
        _ITextContentFilterSeverity.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get sexual() {
        return _ITextContentFilterSeverity.method(8).invoke(this._obj, []).toNumber();
    }

    set sexual(value) {
        _ITextContentFilterSeverity.method(9).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get violent() {
        return _ITextContentFilterSeverity.method(10).invoke(this._obj, []).toNumber();
    }

    set violent(value) {
        _ITextContentFilterSeverity.method(11).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get selfHarm() {
        return _ITextContentFilterSeverity.method(12).invoke(this._obj, []).toNumber();
    }

    set selfHarm(value) {
        _ITextContentFilterSeverity.method(13).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }
}
module.exports = { TextContentFilterSeverity };
