// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');
const _m_RecognizedText = require('./RecognizedText');
const _m_ImageBuffer = require('./ImageBuffer');
const _m_AIFeatureReadyResult = require('./AIFeatureReadyResult');
const _m_TextRecognizerOptions = require('./TextRecognizerOptions');
const _m_AIFeatureReadyState = require('./AIFeatureReadyState');

const IID_ITextRecognizer = WinGuid.parse('be7bf6c0-30f6-570d-bd92-3ffe5665d933');
const IID_ITextRecognizerStatics = WinGuid.parse('3788c2fd-e496-53ab-85a7-e54a135824e9');
const IID_ITextRecognizer2 = WinGuid.parse('90f766f1-2127-53a2-847a-a2a25dde62df');
const IID_IClosable = WinGuid.parse('30d5a829-7fa4-4026-83bb-d75bae4ea99e');

const _ITextRecognizer = DynWinRtType.registerInterface(
    "ITextRecognizer", IID_ITextRecognizer)
    .addMethod("RecognizeTextFromImageAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.RecognizedText', WinGuid.parse('ae4766d3-2924-57a6-b3d3-b866f59b9972')))))
    .addMethod("RecognizeTextFromImage", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.RecognizedText', WinGuid.parse('ae4766d3-2924-57a6-b3d3-b866f59b9972'))));

const _ITextRecognizerStatics = DynWinRtType.registerInterface(
    "ITextRecognizerStatics", IID_ITextRecognizerStatics)
    .addMethod("GetReadyState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Microsoft.Windows.AI.AIFeatureReadyState', ['Ready', 'NotReady', 'NotSupportedOnCurrentSystem', 'DisabledByUser'], [0, 1, 2, 3])))
    .addMethod("EnsureReadyAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.AIFeatureReadyResult', WinGuid.parse('936a78a6-c242-5937-9814-e512d4193a6d')), DynWinRtType.f64())))
    .addMethod("CreateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.TextRecognizer', WinGuid.parse('be7bf6c0-30f6-570d-bd92-3ffe5665d933')))));

const _ITextRecognizer2 = DynWinRtType.registerInterface(
    "ITextRecognizer2", IID_ITextRecognizer2)
    .addMethod("RecognizeTextFromImageAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.TextRecognizerOptions', WinGuid.parse('e2d33788-8ef0-513c-a3a9-5055251c8c4e'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.RecognizedText', WinGuid.parse('ae4766d3-2924-57a6-b3d3-b866f59b9972')))))
    .addMethod("RecognizeTextFromImage", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Graphics.Imaging.ImageBuffer', WinGuid.parse('3baabd0b-1854-51f1-bd2a-74c87858f461'))).addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.TextRecognizerOptions', WinGuid.parse('e2d33788-8ef0-513c-a3a9-5055251c8c4e'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Imaging.RecognizedText', WinGuid.parse('ae4766d3-2924-57a6-b3d3-b866f59b9972'))));

const _IClosable = DynWinRtType.registerInterface(
    "IClosable", IID_IClosable)
    .addMethod("Close", new DynWinRtMethodSig());

class TextRecognizer {
    static _s_ITextRecognizerStatics;
    static s_ITextRecognizerStatics() { return TextRecognizer._s_ITextRecognizerStatics ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Imaging.TextRecognizer').cast(IID_ITextRecognizerStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_ITextRecognizer);
    }

    static getReadyState() {
        return _ITextRecognizerStatics.method(6).invoke(TextRecognizer.s_ITextRecognizerStatics(), []).toNumber();
    }

    static async ensureReadyAsync() {
        return new _m_AIFeatureReadyResult.AIFeatureReadyResult((await _ITextRecognizerStatics.method(7).invoke(TextRecognizer.s_ITextRecognizerStatics(), []).toPromise()));
    }

    static async createAsync() {
        return new TextRecognizer((await _ITextRecognizerStatics.method(8).invoke(TextRecognizer.s_ITextRecognizerStatics(), []).toPromise()));
    }

    async recognizeTextFromImageAsync(operation) {
        return new _m_RecognizedText.RecognizedText((await _ITextRecognizer.method(6).invoke(this._obj, [operation._obj || operation]).toPromise()));
    }

    recognizeTextFromImage(result) {
        return new _m_RecognizedText.RecognizedText(_ITextRecognizer.method(7).invoke(this._obj, [result._obj || result]));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class ITextRecognizer2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new ITextRecognizer2(obj.cast(IID_ITextRecognizer2));
    }

    async recognizeTextFromImageAsync(operation, imageBuffer) {
        return new _m_RecognizedText.RecognizedText((await _ITextRecognizer2.method(6).invoke(this._obj, [operation._obj || operation, imageBuffer._obj || imageBuffer]).toPromise()));
    }

    recognizeTextFromImage(result, imageBuffer) {
        return new _m_RecognizedText.RecognizedText(_ITextRecognizer2.method(7).invoke(this._obj, [result._obj || result, imageBuffer._obj || imageBuffer]));
    }
}

class IClosable {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IClosable(obj.cast(IID_IClosable));
    }

    close() {
        _IClosable.method(6).invoke(this._obj, []);
    }
}
module.exports = { TextRecognizer, ITextRecognizer2, IClosable };
