// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { TextRewriteTone } = require('./TextRewriteTone');
const { LanguageModel } = require('./LanguageModel');
const { LanguageModelResponseResult } = require('./LanguageModelResponseResult');

const IID_ITextRewriter = WinGuid.parse('eb1e7cf0-e110-506c-b0ea-7a288d8e7778');
const IID_ITextRewriterFactory = WinGuid.parse('f452e60d-ef50-5bc9-b483-217d5b4e7151');
const IID_ITextRewriter2 = WinGuid.parse('7937d261-13ce-5b24-b17c-fe5cd0be23b6');
const IID_ITextRewriter3 = WinGuid.parse('622eb80a-ed1a-5525-80d8-c6e80236a195');

const _ITextRewriter = DynWinRtType.registerInterface(
    "ITextRewriter", IID_ITextRewriter)
    .addMethod("RewriteAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())));

const _ITextRewriterFactory = DynWinRtType.registerInterface(
    "ITextRewriterFactory", IID_ITextRewriterFactory)
    .addMethod("CreateInstance", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModel', WinGuid.parse('6331c629-8c86-5bfe-8c4e-9ca5573cc14b'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.TextRewriter', WinGuid.parse('eb1e7cf0-e110-506c-b0ea-7a288d8e7778'))));

const _ITextRewriter2 = DynWinRtType.registerInterface(
    "ITextRewriter2", IID_ITextRewriter2)
    .addMethod("RewriteAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Microsoft.Windows.AI.Text.TextRewriteTone', ['Default', 'General', 'Casual', 'Concise', 'Formal'], [0, 1, 2, 3, 4])).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())));

const _ITextRewriter3 = DynWinRtType.registerInterface(
    "ITextRewriter3", IID_ITextRewriter3)
    .addMethod("RewriteCustomAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModelResponseResult', WinGuid.parse('3a256fff-a426-5d3b-8e4b-3ac84162471e')), DynWinRtType.hstring())));

class TextRewriter {
    static _f_ITextRewriterFactory;
    static f_ITextRewriterFactory() { return TextRewriter._f_ITextRewriterFactory ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Text.TextRewriter').cast(IID_ITextRewriterFactory); }

    constructor(obj) {
        this._obj = obj;
    }

    static createInstance(value) {
        return new TextRewriter(_ITextRewriterFactory.method(6).invoke(TextRewriter.f_ITextRewriterFactory(), [value._obj || value]));
    }

    async rewriteAsync(operation) {
        return new LanguageModelResponseResult((await _ITextRewriter.method(6).invoke(this._obj, [DynWinRtValue.hstring(operation)]).toPromise()));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class ITextRewriter2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new ITextRewriter2(obj.cast(IID_ITextRewriter2));
    }

    async rewriteAsync(operation, text) {
        return new LanguageModelResponseResult((await _ITextRewriter2.method(6).invoke(this._obj, [DynWinRtValue.hstring(operation), DynWinRtValue.i32(text)]).toPromise()));
    }
}

class ITextRewriter3 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new ITextRewriter3(obj.cast(IID_ITextRewriter3));
    }

    async rewriteCustomAsync(operation, text) {
        return new LanguageModelResponseResult((await _ITextRewriter3.method(6).invoke(this._obj, [DynWinRtValue.hstring(operation), DynWinRtValue.hstring(text)]).toPromise()));
    }
}
module.exports = { TextRewriter, ITextRewriter2, ITextRewriter3 };
