// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_LanguageModel = require('./LanguageModel');
const _m_TextToTableResponseResult = require('./TextToTableResponseResult');

const IID_ITextToTableConverter = WinGuid.parse('a008d9ad-25ce-5a6b-9ceb-d8e95d04e10b');
const IID_ITextToTableConverterFactory = WinGuid.parse('bb84cbb5-19c8-5857-b65d-705aa1486404');

const _ITextToTableConverter = DynWinRtType.registerInterface(
    "ITextToTableConverter", IID_ITextToTableConverter)
    .addMethod("ConvertAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperationWithProgress(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.TextToTableResponseResult', WinGuid.parse('391fbf11-59cd-575d-834a-9ef823116f98')), DynWinRtType.hstring())));

const _ITextToTableConverterFactory = DynWinRtType.registerInterface(
    "ITextToTableConverterFactory", IID_ITextToTableConverterFactory)
    .addMethod("CreateInstance", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.LanguageModel', WinGuid.parse('6331c629-8c86-5bfe-8c4e-9ca5573cc14b'))).addOut(DynWinRtType.runtimeClass('Microsoft.Windows.AI.Text.TextToTableConverter', WinGuid.parse('a008d9ad-25ce-5a6b-9ceb-d8e95d04e10b'))));

class TextToTableConverter {
    static _f_ITextToTableConverterFactory;
    static f_ITextToTableConverterFactory() { return TextToTableConverter._f_ITextToTableConverterFactory ??= DynWinRtValue.activationFactory('Microsoft.Windows.AI.Text.TextToTableConverter').cast(IID_ITextToTableConverterFactory); }

    constructor(obj) {
        this._obj = obj.cast(IID_ITextToTableConverter);
    }

    static createInstance(value) {
        return new TextToTableConverter(_ITextToTableConverterFactory.method(6).invoke(TextToTableConverter.f_ITextToTableConverterFactory(), [value._obj || value]));
    }

    convertAsync(operation) {
        const _op = _ITextToTableConverter.method(6).invoke(this._obj, [DynWinRtValue.hstring(operation)]);
        const _w = {
            progress(cb) { _op.onProgress(cb); return _w; },
            async toPromise() { return new _m_TextToTableResponseResult.TextToTableResponseResult(await _op.toPromise()); },
            then(res, rej) { return _w.toPromise().then(res, rej); },
        };
        return _w;
    }
}
module.exports = { TextToTableConverter };
