// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');

const IID_ITextToTableRow = WinGuid.parse('036294fe-e53c-5e66-93d2-7c92338db881');

const _ITextToTableRow = DynWinRtType.registerInterface(
    "ITextToTableRow", IID_ITextToTableRow)
    .addMethod("GetColumns", new DynWinRtMethodSig().addOut(DynWinRtType.arrayType(DynWinRtType.hstring())));

class TextToTableRow {

    constructor(obj) {
        this._obj = obj.cast(IID_ITextToTableRow);
    }

    getColumns() {
        return _ITextToTableRow.method(6).invoke(this._obj, []).asArray().toStringVec();
    }
}
module.exports = { TextToTableRow };
