// Generated by winrt-meta — do not edit

const ThumbnailMode = Object.freeze({ PicturesView: 0, VideosView: 1, MusicView: 2, DocumentsView: 3, ListView: 4, SingleItem: 5 });
module.exports = { ThumbnailMode };
