// Generated by winrt-meta — do not edit (delegate)
const { DynWinRtType, WinGuid } = require('dynwinrt-js');

const IID_TypedEventHandler_UserWatcher_Object = DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.object()]).iid();
const TypedEventHandler_UserWatcher_Object_PARAM_TYPES = [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.object()];
module.exports = { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES };
