// Generated by winrt-meta — do not edit (delegate)
const { DynWinRtType, WinGuid } = require('dynwinrt-js');

const IID_TypedEventHandler_IMemoryBufferReference_Object = DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.interface(WinGuid.parse('fbc4dd29-245b-11e4-af98-689423260cf8')), DynWinRtType.object()]).iid();
const TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES = [DynWinRtType.interface(WinGuid.parse('fbc4dd29-245b-11e4-af98-689423260cf8')), DynWinRtType.object()];
module.exports = { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES };
