// Generated by winrt-meta — do not edit

const UserAuthenticationStatus = Object.freeze({ Unauthenticated: 0, LocallyAuthenticated: 1, RemotelyAuthenticated: 2 });
module.exports = { UserAuthenticationStatus };
