// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const _m_User = require('./User');
const _m_UserAuthenticationStatusChangeDeferral = require('./UserAuthenticationStatusChangeDeferral');
const _m_UserAuthenticationStatus = require('./UserAuthenticationStatus');

const IID_IUserAuthenticationStatusChangingEventArgs = WinGuid.parse('8c030f28-a711-4c1e-ab48-04179c15938f');

const _IUserAuthenticationStatusChangingEventArgs = DynWinRtType.registerInterface(
    "IUserAuthenticationStatusChangingEventArgs", IID_IUserAuthenticationStatusChangingEventArgs)
    .addMethod("GetDeferral", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.System.UserAuthenticationStatusChangeDeferral', WinGuid.parse('88b59568-bb30-42fb-a270-e9902e40efa7'))))
    .addMethod("get_User", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))))
    .addMethod("get_NewStatus", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserAuthenticationStatus', ['Unauthenticated', 'LocallyAuthenticated', 'RemotelyAuthenticated'], [0, 1, 2])))
    .addMethod("get_CurrentStatus", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserAuthenticationStatus', ['Unauthenticated', 'LocallyAuthenticated', 'RemotelyAuthenticated'], [0, 1, 2])));

class UserAuthenticationStatusChangingEventArgs {

    constructor(obj) {
        this._obj = obj.cast(IID_IUserAuthenticationStatusChangingEventArgs);
    }

    getDeferral() {
        return new _m_UserAuthenticationStatusChangeDeferral.UserAuthenticationStatusChangeDeferral(_IUserAuthenticationStatusChangingEventArgs.method(6).invoke(this._obj, []));
    }

    get user() {
        return new _m_User.User(_IUserAuthenticationStatusChangingEventArgs.method(7).invoke(this._obj, []));
    }

    get newStatus() {
        return _IUserAuthenticationStatusChangingEventArgs.method(8).invoke(this._obj, []).toNumber();
    }

    get currentStatus() {
        return _IUserAuthenticationStatusChangingEventArgs.method(9).invoke(this._obj, []).toNumber();
    }
}
module.exports = { UserAuthenticationStatusChangingEventArgs };
