// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');

const IID_IUserAuthenticationStatusChangeDeferral = WinGuid.parse('88b59568-bb30-42fb-a270-e9902e40efa7');

const _IUserAuthenticationStatusChangeDeferral = DynWinRtType.registerInterface(
    "IUserAuthenticationStatusChangeDeferral", IID_IUserAuthenticationStatusChangeDeferral)
    .addMethod("Complete", new DynWinRtMethodSig());

class UserAuthenticationStatusChangeDeferral {

    constructor(obj) {
        this._obj = obj.cast(IID_IUserAuthenticationStatusChangeDeferral);
    }

    complete() {
        _IUserAuthenticationStatusChangeDeferral.method(6).invoke(this._obj, []);
    }
}
module.exports = { UserAuthenticationStatusChangeDeferral };
