// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { UserChangedEventArgs } = require('./UserChangedEventArgs');
const { UserWatcherStatus } = require('./UserWatcherStatus');
const { UserAuthenticationStatusChangingEventArgs } = require('./UserAuthenticationStatusChangingEventArgs');

const IID_IUserWatcher = WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb');

const _IUserWatcher = DynWinRtType.registerInterface(
    "IUserWatcher", IID_IUserWatcher)
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserWatcherStatus', ['Created', 'Started', 'EnumerationCompleted', 'Stopping', 'Stopped', 'Aborted'], [0, 1, 2, 3, 4, 5])))
    .addMethod("Start", new DynWinRtMethodSig())
    .addMethod("Stop", new DynWinRtMethodSig())
    .addMethod("add_Added", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_Added", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_Removed", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_Removed", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_Updated", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_Updated", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_AuthenticationStatusChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_AuthenticationStatusChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_AuthenticationStatusChanging", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserAuthenticationStatusChangingEventArgs', WinGuid.parse('8c030f28-a711-4c1e-ab48-04179c15938f'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_AuthenticationStatusChanging", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_EnumerationCompleted", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_EnumerationCompleted", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_Stopped", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_Stopped", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])));

function _unpackEventRegistrationToken(v) {
    const s = v.asStruct();
    return { value: s.getI64(0) };
}
const _EventRegistrationToken_Type = DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()]);
function _packEventRegistrationToken(v) {
    const s = DynWinRtStruct.create(_EventRegistrationToken_Type);
    s.setI64(0, v.value);
    return s;
}

class UserWatcher {

    constructor(obj) {
        this._obj = obj;
    }

    get status() {
        return _IUserWatcher.method(6).invoke(this._obj, []).toNumber();
    }

    start() {
        _IUserWatcher.method(7).invoke(this._obj, []);
    }

    stop() {
        _IUserWatcher.method(8).invoke(this._obj, []);
    }

    onAdded(callback) {
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES, callback);
        return _IUserWatcher.method(9).invoke(this._obj, [handler.toValue()]);
    }

    offAdded(token) {
        _IUserWatcher.method(10).invoke(this._obj, [token]);
    }

    onRemoved(callback) {
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES, callback);
        return _IUserWatcher.method(11).invoke(this._obj, [handler.toValue()]);
    }

    offRemoved(token) {
        _IUserWatcher.method(12).invoke(this._obj, [token]);
    }

    onUpdated(callback) {
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES, callback);
        return _IUserWatcher.method(13).invoke(this._obj, [handler.toValue()]);
    }

    offUpdated(token) {
        _IUserWatcher.method(14).invoke(this._obj, [token]);
    }

    onAuthenticationStatusChanged(callback) {
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES, callback);
        return _IUserWatcher.method(15).invoke(this._obj, [handler.toValue()]);
    }

    offAuthenticationStatusChanged(token) {
        _IUserWatcher.method(16).invoke(this._obj, [token]);
    }

    onAuthenticationStatusChanging(callback) {
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES, callback);
        return _IUserWatcher.method(17).invoke(this._obj, [handler.toValue()]);
    }

    offAuthenticationStatusChanging(token) {
        _IUserWatcher.method(18).invoke(this._obj, [token]);
    }

    onEnumerationCompleted(callback) {
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES, callback);
        return _IUserWatcher.method(19).invoke(this._obj, [handler.toValue()]);
    }

    offEnumerationCompleted(token) {
        _IUserWatcher.method(20).invoke(this._obj, [token]);
    }

    onStopped(callback) {
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES, callback);
        return _IUserWatcher.method(21).invoke(this._obj, [handler.toValue()]);
    }

    offStopped(token) {
        _IUserWatcher.method(22).invoke(this._obj, [token]);
    }
}
module.exports = { UserWatcher };
