// Generated by winrt-meta — do not edit

const UserAgeConsentResult = Object.freeze({ NotEnforced: 0, Included: 1, NotIncluded: 2, Unknown: 3, Ambiguous: 4 });
module.exports = { UserAgeConsentResult };
