// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const { IVectorView_String } = require('./IVectorView_String');
const { IVectorView_User } = require('./IVectorView_User');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { UserAuthenticationStatus } = require('./UserAuthenticationStatus');
const { UserAgeConsentGroup } = require('./UserAgeConsentGroup');
const { UserWatcher } = require('./UserWatcher');
const { UserAgeConsentResult } = require('./UserAgeConsentResult');
const { UserType } = require('./UserType');
const { IID_IRandomAccessStreamReference, IRandomAccessStreamReference } = require('./IRandomAccessStreamReference');
const { UserPictureSize } = require('./UserPictureSize');
const { IID_IPropertySet, IPropertySet } = require('./IPropertySet');

const IID_IUser = WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b');
const IID_IUserStatics = WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fdd');
const IID_IUserStatics2 = WinGuid.parse('74a37e11-2eb5-4487-b0d5-2c6790e013e9');
const IID_IUser2 = WinGuid.parse('98ba5628-a6e3-518e-89d9-d3b2b1991a10');

const _IUser = DynWinRtType.registerInterface(
    "IUser", IID_IUser)
    .addMethod("get_NonRoamableId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_AuthenticationStatus", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserAuthenticationStatus', ['Unauthenticated', 'LocallyAuthenticated', 'RemotelyAuthenticated'], [0, 1, 2])))
    .addMethod("get_Type", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserType', ['LocalUser', 'RemoteUser', 'LocalGuest', 'RemoteGuest', 'SystemManaged'], [0, 1, 2, 3, 4])))
    .addMethod("GetPropertyAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.object())))
    .addMethod("GetPropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('8a43ed9f-f4e6-4421-acf9-1dab2986820c')))))
    .addMethod("GetPictureAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.System.UserPictureSize', ['Size64x64', 'Size208x208', 'Size424x424', 'Size1080x1080'], [0, 1, 2, 3])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b')))));

const _IUserStatics = DynWinRtType.registerInterface(
    "IUserStatics", IID_IUserStatics)
    .addMethod("CreateWatcher", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb'))))
    .addMethod("FindAllAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))]))))
    .addMethod("FindAllAsyncByType", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.System.UserType', ['LocalUser', 'RemoteUser', 'LocalGuest', 'RemoteGuest', 'SystemManaged'], [0, 1, 2, 3, 4])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))]))))
    .addMethod("FindAllAsyncByTypeAndStatus", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.System.UserType', ['LocalUser', 'RemoteUser', 'LocalGuest', 'RemoteGuest', 'SystemManaged'], [0, 1, 2, 3, 4])).addIn(DynWinRtType.enumType('Windows.System.UserAuthenticationStatus', ['Unauthenticated', 'LocallyAuthenticated', 'RemotelyAuthenticated'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))]))))
    .addMethod("GetFromId", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))));

const _IUserStatics2 = DynWinRtType.registerInterface(
    "IUserStatics2", IID_IUserStatics2)
    .addMethod("GetDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))));

const _IUser2 = DynWinRtType.registerInterface(
    "IUser2", IID_IUser2)
    .addMethod("CheckUserAgeConsentGroupAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.System.UserAgeConsentGroup', ['Child', 'Minor', 'Adult'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.enumType('Windows.System.UserAgeConsentResult', ['NotEnforced', 'Included', 'NotIncluded', 'Unknown', 'Ambiguous'], [0, 1, 2, 3, 4]))));

class User {
    static _s_IUserStatics;
    static s_IUserStatics() { return User._s_IUserStatics ??= DynWinRtValue.activationFactory('Windows.System.User').cast(IID_IUserStatics); }
    static _s_IUserStatics2;
    static s_IUserStatics2() { return User._s_IUserStatics2 ??= DynWinRtValue.activationFactory('Windows.System.User').cast(IID_IUserStatics2); }

    constructor(obj) {
        this._obj = obj.cast(IID_IUser);
    }

    static createWatcher() {
        return new UserWatcher(_IUserStatics.method(6).invoke(User.s_IUserStatics(), []));
    }

    static async findAllAsync() {
        return new IVectorView_User((await _IUserStatics.method(7).invoke(User.s_IUserStatics(), []).toPromise()));
    }

    static async findAllAsyncByType(operation) {
        return new IVectorView_User((await _IUserStatics.method(8).invoke(User.s_IUserStatics(), [DynWinRtValue.i32(operation)]).toPromise()));
    }

    static async findAllAsyncByTypeAndStatus(operation, type) {
        return new IVectorView_User((await _IUserStatics.method(9).invoke(User.s_IUserStatics(), [DynWinRtValue.i32(operation), DynWinRtValue.i32(type)]).toPromise()));
    }

    static getFromId(result) {
        return new User(_IUserStatics.method(10).invoke(User.s_IUserStatics(), [DynWinRtValue.hstring(result)]));
    }

    static getDefault() {
        return new User(_IUserStatics2.method(6).invoke(User.s_IUserStatics2(), []));
    }

    get nonRoamableId() {
        return _IUser.method(6).invoke(this._obj, []).toString();
    }

    get authenticationStatus() {
        return _IUser.method(7).invoke(this._obj, []).toNumber();
    }

    get type() {
        return _IUser.method(8).invoke(this._obj, []).toNumber();
    }

    async getPropertyAsync(operation) {
        return (await _IUser.method(9).invoke(this._obj, [DynWinRtValue.hstring(operation)]).toPromise());
    }

    async getPropertiesAsync(operation) {
        return new IPropertySet((await _IUser.method(10).invoke(this._obj, [operation._obj || operation]).toPromise()));
    }

    async getPictureAsync(operation) {
        return new IRandomAccessStreamReference((await _IUser.method(11).invoke(this._obj, [DynWinRtValue.i32(operation)]).toPromise()));
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IUser2 {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IUser2(obj.cast(IID_IUser2));
    }

    async checkUserAgeConsentGroupAsync(operation) {
        return (await _IUser2.method(6).invoke(this._obj, [DynWinRtValue.i32(operation)]).toPromise()).toNumber();
    }
}
module.exports = { User, IUser2 };
