// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));
const { IVector_RectInt32 } = require('./IVector_RectInt32');
const { IID_TypedEventHandler_IMemoryBufferReference_Object, TypedEventHandler_IMemoryBufferReference_Object_PARAM_TYPES } = require('./TypedEventHandler_IMemoryBufferReference_Object');

const IID_IVideoScalerOptions = WinGuid.parse('c255ab80-b7cf-54e4-8703-e34bbeaa47d4');

const _IVideoScalerOptions = DynWinRtType.registerInterface(
    "IVideoScalerOptions", IID_IVideoScalerOptions)
    .addMethod("get_RegionOfInterests", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.structType('Windows.Graphics.RectInt32', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()])])));

function _unpackRectInt32(v) {
    const s = v.asStruct();
    return { x: s.getI32(0), y: s.getI32(1), width: s.getI32(2), height: s.getI32(3) };
}
const _RectInt32_Type = DynWinRtType.structType('Windows.Graphics.RectInt32', [DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32(), DynWinRtType.i32()]);
function _packRectInt32(v) {
    const s = DynWinRtStruct.create(_RectInt32_Type);
    s.setI32(0, v.x);
    s.setI32(1, v.y);
    s.setI32(2, v.width);
    s.setI32(3, v.height);
    return s;
}

class VideoScalerOptions {

    constructor(obj) {
        this._obj = obj;
    }

    static create() {
        return new VideoScalerOptions(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Microsoft.Windows.AI.Video.VideoScalerOptions'), []));
    }

    get regionOfInterests() {
        return new IVector_RectInt32(_IVideoScalerOptions.method(6).invoke(this._obj, []));
    }
}
module.exports = { VideoScalerOptions };
