// Generated by winrt-meta — do not edit
const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');
const _m_IIterable_IKeyValuePair_String_Object = require('./IIterable_IKeyValuePair_String_Object');
const _m_IIterable_String = require('./IIterable_String');
const _m_IKeyValuePair_String_Object = require('./IKeyValuePair_String_Object');
const _m_IMap_String_Object = require('./IMap_String_Object');
const _m_IReference_Double = require('./IReference_Double');
const _m_IVector_String = require('./IVector_String');
const { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_Object');
const { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs');
const { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } = require('./TypedEventHandler_UserWatcher_UserChangedEventArgs');
const { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } = require('./TypedEventHandler_IStorageQueryResultBase_Object');
const { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } = require('./StreamedFileDataRequestedHandler');
const _m_VideoOrientation = require('./VideoOrientation');

const IID_IVideoProperties = WinGuid.parse('719ae507-68de-4db8-97de-49998c059f2f');
const IID_IStorageItemExtraProperties = WinGuid.parse('c54361b2-54cd-432b-bdbc-4b19c4b470d7');

const _IVideoProperties = DynWinRtType.registerInterface(
    "IVideoProperties", IID_IVideoProperties)
    .addMethod("get_Rating", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Rating", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Keywords", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Width", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Height", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Duration", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.TimeSpan', [DynWinRtType.i64()])))
    .addMethod("get_Latitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_Longitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_Title", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Title", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Subtitle", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Subtitle", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Producers", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Publisher", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Publisher", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Writers", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Year", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Year", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Bitrate", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Directors", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Orientation", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileProperties.VideoOrientation', ['Normal', 'Rotate90', 'Rotate180', 'Rotate270'], [0, 90, 180, 270])));

const _IStorageItemExtraProperties = DynWinRtType.registerInterface(
    "IStorageItemExtraProperties", IID_IStorageItemExtraProperties)
    .addMethod("RetrievePropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.hstring()])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('3c2925fe-8519-45c1-aa79-197b6718c1c1'), [DynWinRtType.hstring(), DynWinRtType.object()]))))
    .addMethod("SavePropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.parameterized(WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500'), [DynWinRtType.hstring(), DynWinRtType.object()])])).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("SavePropertiesAsyncOverloadDefault", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()));

function _unpackTimeSpan(v) {
    const s = v.asStruct();
    return { duration: s.getI64(0) };
}
const _TimeSpan_Type = DynWinRtType.structType('Windows.Foundation.TimeSpan', [DynWinRtType.i64()]);
function _packTimeSpan(v) {
    const s = DynWinRtStruct.create(_TimeSpan_Type);
    s.setI64(0, v.duration);
    return s;
}

class VideoProperties {

    constructor(obj) {
        this._obj = obj.cast(IID_IVideoProperties);
    }

    get rating() {
        return _IVideoProperties.method(6).invoke(this._obj, []).toNumber();
    }

    set rating(value) {
        _IVideoProperties.method(7).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get keywords() {
        return new _m_IVector_String.IVector_String(_IVideoProperties.method(8).invoke(this._obj, []));
    }

    get width() {
        return _IVideoProperties.method(9).invoke(this._obj, []).toNumber();
    }

    get height() {
        return _IVideoProperties.method(10).invoke(this._obj, []).toNumber();
    }

    get duration() {
        return _unpackTimeSpan(_IVideoProperties.method(11).invoke(this._obj, []));
    }

    get latitude() {
        return new _m_IReference_Double.IReference_Double(_IVideoProperties.method(12).invoke(this._obj, []));
    }

    get longitude() {
        return new _m_IReference_Double.IReference_Double(_IVideoProperties.method(13).invoke(this._obj, []));
    }

    get title() {
        return _IVideoProperties.method(14).invoke(this._obj, []).toString();
    }

    set title(value) {
        _IVideoProperties.method(15).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get subtitle() {
        return _IVideoProperties.method(16).invoke(this._obj, []).toString();
    }

    set subtitle(value) {
        _IVideoProperties.method(17).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get producers() {
        return new _m_IVector_String.IVector_String(_IVideoProperties.method(18).invoke(this._obj, []));
    }

    get publisher() {
        return _IVideoProperties.method(19).invoke(this._obj, []).toString();
    }

    set publisher(value) {
        _IVideoProperties.method(20).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }

    get writers() {
        return new _m_IVector_String.IVector_String(_IVideoProperties.method(21).invoke(this._obj, []));
    }

    get year() {
        return _IVideoProperties.method(22).invoke(this._obj, []).toNumber();
    }

    set year(value) {
        _IVideoProperties.method(23).invoke(this._obj, [DynWinRtValue.i32(value)]);
    }

    get bitrate() {
        return _IVideoProperties.method(24).invoke(this._obj, []).toNumber();
    }

    get directors() {
        return new _m_IVector_String.IVector_String(_IVideoProperties.method(25).invoke(this._obj, []));
    }

    get orientation() {
        return _IVideoProperties.method(26).invoke(this._obj, []).toNumber();
    }

    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}

class IStorageItemExtraProperties {
    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageItemExtraProperties(obj.cast(IID_IStorageItemExtraProperties));
    }

    async retrievePropertiesAsync(operation) {
        return new _m_IMap_String_Object.IMap_String_Object((await _IStorageItemExtraProperties.method(6).invoke(this._obj, [operation._obj || operation]).toPromise()));
    }

    async savePropertiesAsync(operation) {
        return (await _IStorageItemExtraProperties.method(7).invoke(this._obj, [operation._obj || operation]).toPromise());
    }

    async savePropertiesAsyncOverloadDefault() {
        return (await _IStorageItemExtraProperties.method(8).invoke(this._obj, []).toPromise());
    }
}
module.exports = { VideoProperties, IStorageItemExtraProperties };
